/* ============================================================================
   RoamWise EVENTS CALENDAR — edit this file to add or correct events.
   ============================================================================
   HONESTY RULE: `when` is what we tell the user, and `verified` says how much
   to trust it.
     verified:'confirmed'  -> dates announced by the organiser
     verified:'typical'    -> it runs around this time most years, NOT announced
   The app SHOWS this distinction, because someone may book a flight on it.
   Never mark something 'confirmed' unless you have actually checked.
   ========================================================================= */
window.RW_EVENTS = [

  /* ---------------- MUSIC ---------------- */
  { id:'ziro', roi:{prof:2,money:-1,mind:5,cult:5,fun:5,cost:3,drain:3}, cat:'music', name:'Ziro Festival of Music', place:'Ziro Valley, Arunachal Pradesh',
    country:'India', start:'2026-09-24', end:'2026-09-27', verified:'confirmed',
    vibe:'Indie & folk in a Himalayan rice-paddy valley. Camping, bamboo stages, no cars.',
    tips:['Inner Line Permit needed for Arunachal — apply online well before you go.',
          'Nearest railhead Naharlagun, then a long shared-taxi ride. Budget a full travel day each way.',
          'It rains. Bring a poncho, not an umbrella, and boots you can lose.'] },
  { id:'nh7', roi:{prof:1,money:-1,mind:3,cult:3,fun:5,cost:2,drain:2}, cat:'music', name:'NH7 Weekender', place:'Pune / multi-city', country:'India',
    month:11, verified:'typical', vibe:'India\u2019s long-running multi-stage indie festival.',
    tips:['Multi-city editions — check which city before booking.'] },
  { id:'sunburn', roi:{prof:0,money:-2,mind:1,cult:1,fun:4,cost:4,drain:4}, cat:'music', name:'Sunburn', place:'Goa', country:'India',
    month:12, verified:'typical', vibe:'Large EDM festival over the year-end week.',
    tips:['Goa accommodation triples in price that week. Book far ahead or stay inland.'] },
  { id:'magnetic', roi:{prof:2,money:-2,mind:4,cult:4,fun:4,cost:4,drain:2}, cat:'music', name:'Magnetic Fields', place:'Alsisar, Rajasthan', country:'India',
    month:12, verified:'typical', vibe:'Electronic music inside a desert palace.',
    tips:['Desert nights are genuinely cold in December — pack layers.'] },
  { id:'hornbill', roi:{prof:1,money:-1,mind:4,cult:5,fun:4,cost:2,drain:2}, cat:'music', name:'Hornbill Festival', place:'Kisama, Nagaland', country:'India',
    start:'2026-12-01', end:'2026-12-10', verified:'typical',
    vibe:'Culture, tribal music and food across ten days.',
    tips:['Permit rules apply for some areas — check current requirements.'] },
  { id:'glasto', roi:{prof:1,money:-2,mind:4,cult:5,fun:5,cost:5,drain:4}, cat:'music', name:'Glastonbury', place:'Somerset', country:'UK',
    month:6, verified:'typical', vibe:'The benchmark. Ballot months in advance.',
    tips:['Tickets sell out in minutes and need pre-registration with a photo.'] },
  { id:'fujirock', roi:{prof:1,money:-2,mind:4,cult:4,fun:5,cost:4,drain:2}, cat:'music', name:'Fuji Rock', place:'Naeba, Niigata', country:'Japan',
    month:7, verified:'typical', vibe:'Mountain forest stages, famously well-run.',
    tips:['Shinkansen to Echigo-Yuzawa, then a shuttle.'] },

  /* ---------------- STARTUP / TECH ---------------- */
  { id:'tcdisrupt', roi:{prof:5,money:4,mind:2,cult:2,fun:2,cost:5,drain:3}, cat:'startup', name:'TechCrunch Disrupt', place:'San Francisco', country:'USA',
    month:10, verified:'typical', vibe:'Startup Battlefield, investor floor, heavy side-event scene.',
    tips:['The side events matter more than the main stage. Plan those first.'] },
  { id:'startupmahakumbh', roi:{prof:5,money:4,mind:3,cult:3,fun:2,cost:1,drain:2}, cat:'startup', name:'Startup Mahakumbh', place:'Bharat Mandapam, New Delhi',
    country:'India', month:4, verified:'typical',
    vibe:'India\u2019s largest startup gathering — founders, funds, policy.',
    tips:['Bharat Mandapam is huge. Pick two halls and go deep rather than wandering.',
          'Delhi metro to Supreme Court station beats driving.'] },
  { id:'tie', roi:{prof:4,money:4,mind:3,cult:2,fun:2,cost:2,drain:2}, cat:'startup', name:'TiE Global Summit', place:'varies (often Bengaluru/Delhi)',
    country:'India', month:12, verified:'typical', vibe:'Founder-investor matchmaking at scale.',
    tips:['Book 1:1 mentor slots the day registration opens — they go instantly.'] },
  { id:'websummit', roi:{prof:4,money:3,mind:2,cult:3,fun:3,cost:5,drain:4}, cat:'startup', name:'Web Summit', place:'Lisbon', country:'Portugal',
    month:11, verified:'typical', vibe:'70k+ attendees, huge investor presence.',
    tips:['Stay near a metro line, not near the venue — it is cheaper and faster.'] },
  { id:'ces', roi:{prof:3,money:2,mind:2,cult:2,fun:3,cost:5,drain:5}, cat:'startup', name:'CES', place:'Las Vegas', country:'USA',
    month:1, verified:'typical', vibe:'Consumer tech at enormous scale.',
    tips:['Hotels spike ~4x. Book the moment dates are announced.'] },

  /* ---------------- SPORTS ---------------- */
  { id:'indiangp', roi:{prof:0,money:-1,mind:2,cult:2,fun:5,cost:3,drain:2}, cat:'sports', name:'MotoGP Bharat', place:'Buddh International Circuit, Greater Noida',
    country:'India', month:9, verified:'typical', vibe:'MotoGP round on the BIC.',
    tips:['Stay in Noida rather than central Delhi — the circuit is far east.'] },
  { id:'ipl', roi:{prof:0,money:-1,mind:2,cult:4,fun:5,cost:2,drain:1}, cat:'sports', name:'IPL season', place:'multi-city', country:'India',
    month:4, verified:'typical', vibe:'Two months of cricket across ten cities.',
    tips:['Tickets go through the home franchise, not a single portal.'] },
  { id:'ladakh-marathon', roi:{prof:1,money:-1,mind:5,cult:4,fun:4,cost:3,drain:4}, cat:'sports', name:'Ladakh Marathon', place:'Leh, Ladakh', country:'India',
    month:9, verified:'typical', vibe:'The world\u2019s highest marathon.',
    tips:['Arrive at least 5\u20137 days early to acclimatise. This is not optional.',
          'Do not attempt without prior altitude experience.'] },
  { id:'tourdefrance', roi:{prof:0,money:-1,mind:3,cult:4,fun:4,cost:3,drain:2}, cat:'sports', name:'Tour de France', place:'route varies', country:'France',
    month:7, verified:'typical', vibe:'Three weeks, mountain stages are the spectacle.',
    tips:['Pick one mountain stage and camp the col the night before.'] },
  { id:'f1mc', roi:{prof:2,money:-2,mind:1,cult:3,fun:5,cost:5,drain:3}, cat:'sports', name:'Monaco Grand Prix', place:'Monte Carlo', country:'Monaco',
    month:5, verified:'typical', vibe:'F1\u2019s most famous street circuit.',
    tips:['Stay in Nice and take the train in — Monaco hotels are brutal.'] },

  /* ---------------- AUTOMOBILE ---------------- */
  { id:'autoexpo', roi:{prof:3,money:1,mind:2,cult:3,fun:4,cost:1,drain:2}, cat:'auto', name:'Bharat Mobility Global Expo', place:'Bharat Mandapam & Yashobhoomi, Delhi',
    country:'India', month:1, verified:'typical',
    vibe:'India\u2019s biggest auto and mobility show.',
    tips:['Public days are packed — go on the first public morning, right at opening.'] },
  { id:'rreride', roi:{prof:1,money:-1,mind:4,cult:4,fun:5,cost:2,drain:2}, cat:'auto', name:'Rider Mania (Royal Enfield)', place:'Goa', country:'India',
    month:11, verified:'typical', vibe:'Thousands of Enfields, dirt track, live music.',
    tips:['Ride down if you can — the convoy is half the experience.'] },
  { id:'goodwood', roi:{prof:2,money:0,mind:3,cult:4,fun:5,cost:4,drain:2}, cat:'auto', name:'Goodwood Festival of Speed', place:'West Sussex', country:'UK',
    month:7, verified:'typical', vibe:'Hillclimb, historic cars, manufacturer reveals.',
    tips:['General admission is fine; grandstand seats are rarely worth it.'] },
  { id:'tokyoms', roi:{prof:3,money:1,mind:3,cult:4,fun:4,cost:4,drain:2}, cat:'auto', name:'Japan Mobility Show', place:'Tokyo Big Sight', country:'Japan',
    month:10, verified:'typical', vibe:'Concept cars and Japanese domestic market culture.',
    tips:['Pair it with a Daikoku PA night if you like car culture.'] },
/* ---------------- TECH / AI (for builders) ---------------- */
  { id:'aidevday', roi:{prof:5,money:4,mind:3,cult:2,fun:2,cost:4,drain:2},
    cat:'tech', name:'OpenAI DevDay', place:'San Francisco', country:'USA',
    month:10, verified:'typical', vibe:'API launches, hands-on labs, dense builder crowd.',
    tips:['Tickets are limited and go fast \u2014 watch the developer blog, not social.',
          'The unofficial hallway track and after-parties are where the hiring happens.'] },
  { id:'anthropicdev', roi:{prof:5,money:4,mind:4,cult:2,fun:2,cost:4,drain:2},
    cat:'tech', name:'Anthropic developer events', place:'San Francisco / online', country:'USA',
    month:5, verified:'typical', vibe:'Claude platform sessions, agent tooling, safety-minded builders.',
    tips:['Many sessions stream free \u2014 check before booking a flight.',
          'Bring a working demo, not slides. This crowd reads code.'] },
  { id:'googleio', roi:{prof:4,money:3,mind:3,cult:2,fun:3,cost:3,drain:2},
    cat:'tech', name:'Google I/O', place:'Mountain View, CA', country:'USA',
    month:5, verified:'typical', vibe:'Android, AI and web platform announcements.',
    tips:['The livestream covers the keynotes free; go in person only for the labs.'] },
  { id:'reinvent', roi:{prof:4,money:3,mind:2,cult:1,fun:2,cost:5,drain:5},
    cat:'tech', name:'AWS re:Invent', place:'Las Vegas', country:'USA',
    month:12, verified:'typical', vibe:'Enormous cloud conference, 60k+ attendees.',
    tips:['Sessions book out weeks early \u2014 reserve the moment the catalogue opens.',
          'Vegas in December is cheap to fly to, expensive to sleep in.'] },
  { id:'wwdc', roi:{prof:4,money:3,mind:2,cult:2,fun:2,cost:4,drain:2},
    cat:'tech', name:'Apple WWDC', place:'Cupertino / online', country:'USA',
    month:6, verified:'typical', vibe:'Apple platform releases; mostly online now.',
    tips:['Online is genuinely equivalent for most developers \u2014 save the airfare.'] },
  { id:'neurips', roi:{prof:5,money:3,mind:5,cult:2,fun:2,cost:5,drain:4},
    cat:'tech', name:'NeurIPS', place:'varies (often Vancouver/New Orleans)', country:'varies',
    month:12, verified:'typical', vibe:'The main ML research conference.',
    tips:['Register the day it opens \u2014 it sells out.',
          'Workshops on the final days are where the useful conversations happen.'] },
  { id:'gtc', roi:{prof:4,money:3,mind:3,cult:1,fun:2,cost:4,drain:3},
    cat:'tech', name:'NVIDIA GTC', place:'San Jose / online', country:'USA',
    month:3, verified:'typical', vibe:'GPU, AI infrastructure and robotics.',
    tips:['The free online pass covers most of the value.'] },
  { id:'nasscom', roi:{prof:4,money:4,mind:2,cult:3,fun:2,cost:1,drain:2},
    cat:'tech', name:'NASSCOM Technology & Leadership Forum', place:'Mumbai', country:'India',
    month:2, verified:'typical', vibe:'India\u2019s flagship enterprise-tech gathering.',
    tips:['Strong for enterprise buyers and services partnerships, weaker for consumer startups.'] },
  { id:'gdc', roi:{prof:4,money:3,mind:3,cult:3,fun:3,cost:5,drain:4},
    cat:'tech', name:'Game Developers Conference', place:'San Francisco', country:'USA',
    month:3, verified:'typical', vibe:'Games industry: craft talks and hiring.',
    tips:['The expo pass is far cheaper and still gets you the floor and parties.'] },
/* ---------------- WORLD MOMENTS (migrated from the legacy Discover "Event
     Radar" — these are trip TRIGGERS with travel-arbitrage insight, not
     single-venue events, hence their own category) ---------------- */
  { id:'fifa26', roi:{prof:0,money:-2,mind:3,cult:5,fun:5,cost:5,drain:3},
    cat:'moments', name:'FIFA World Cup 2026', place:'USA \u00b7 Mexico \u00b7 Canada, 16 host cities',
    country:'Multi', start:'2026-06-11', end:'2026-07-19', verified:'confirmed',
    vibe:'The first 48-team World Cup, across three countries.',
    tips:['Fan-fest cities beat stadium cities on price \u2014 watch group games in Mexico City (electric and cheap), save NYC for the semis atmosphere.',
          'Book stays 40km out on transit lines: roughly half price, 30 minutes in.'] },
  { id:'la28', roi:{prof:0,money:-2,mind:3,cult:5,fun:5,cost:5,drain:3},
    cat:'moments', name:'LA Olympics 2028', place:'Los Angeles', country:'USA',
    start:'2028-07-14', end:'2028-07-30', verified:'typical',
    vibe:'The Games return to Los Angeles.',
    tips:['Olympic cities empty out AROUND the venues \u2014 Santa Monica and Malibu often run below normal occupancy while Downtown surges. Stay coastal, train in.'] },
  { id:'wc27', roi:{prof:0,money:-1,mind:4,cult:5,fun:4,cost:4,drain:3},
    cat:'moments', name:'ICC Cricket World Cup 2027', place:'South Africa \u00b7 Zimbabwe \u00b7 Namibia',
    country:'Multi', start:'2027-10-01', end:'2027-11-15', verified:'typical',
    vibe:'The first African ODI World Cup in decades.',
    tips:['Combine Newlands cricket with the Garden Route.',
          'Book Cape Town stays 9+ months out \u2014 match-week prices triple.'] },
  { id:'concerts', roi:{prof:0,money:3,mind:3,cult:4,fun:5,cost:2,drain:2},
    cat:'moments', name:'Stadium tour season', place:'Global stadium tours', country:'Multi',
    month:6, verified:'typical', vibe:'Pop\u2019s biggest names on world tours, May\u2013Sept.',
    tips:['Concert arbitrage: the same world tour often costs 40\u201360% less in Warsaw, Bangkok or S\u00e3o Paulo than London or NYC \u2014 fly there, see the show, and the holiday is effectively free.'] },
  { id:'f1season', roi:{prof:1,money:-1,mind:2,cult:4,fun:5,cost:4,drain:2},
    cat:'moments', name:'F1 season flyaways', place:'Singapore \u00b7 Monaco \u00b7 Suzuka', country:'Multi',
    month:9, verified:'typical', vibe:'The travel-worthy rounds of the F1 calendar.',
    tips:['Singapore\u2019s night GP is the most tourist-perfect race \u2014 the track wraps the city, so a regular hotel IS a grandstand.',
          'Book Marina Bay view rooms about 6 months out.'] },
  { id:'motorvalley', roi:{prof:1,money:0,mind:4,cult:5,fun:5,cost:3,drain:1},
    cat:'moments', name:'Italy\u2019s Motor Valley pilgrimage', place:'Sant\u2019Agata \u00b7 Maranello \u00b7 Bologna',
    country:'Italy', month:4, verified:'typical',
    vibe:'Ferrari, Lamborghini and Ducati within an hour of each other.',
    tips:['One base near Bologna covers three legendary marques \u2014 factory museums and test-track days cluster there. Best in spring.'] },
  { id:'skyline', roi:{prof:1,money:0,mind:3,cult:4,fun:3,cost:3,drain:2},
    cat:'moments', name:'Mega-tower & expo watch', place:'Jeddah \u00b7 Riyadh', country:'Saudi Arabia',
    month:10, verified:'typical', vibe:'Skyline tourism while a city is being built.',
    tips:['Jeddah Tower aims to take the world-tallest crown \u2014 the construction-boom years are the cheap years to see a city being born.'] },
  { id:'launchweek', roi:{prof:1,money:2,mind:1,cult:2,fun:3,cost:3,drain:2},
    cat:'moments', name:'Flagship phone launch week', place:'Dubai \u00b7 Singapore \u00b7 NYC',
    country:'Multi', month:9, verified:'typical', vibe:'Launch-day tourism is a real thing.',
    tips:['Dubai Mall and Singapore Orchard get first stock hours ahead of the West \u2014 pair a city break with a day-one pickup and skip home-country markups.'] }
,
  /* ---------------- CAMPUS / STUDENT (partnership: E-Cell NMIMS Mumbai) ---------------- */
  { id:'nmims-esummit', roi:{prof:5,money:3,mind:3,cult:3,fun:4,cost:1,drain:2},
    cat:'startup', name:'E-Summit \u2014 E-Cell NMIMS Mumbai', place:'NMIMS, Vile Parle, Mumbai',
    country:'India', month:1, verified:'typical',
    vibe:'The flagship: Shark Tank-style pitching, Business Mela, 800\u20131000 attendees.',
    tips:['The single best campus event in Mumbai for meeting founders and early investors.',
          'Come with a working demo on your phone \u2014 it beats a pitch deck at a student event.'] },
  { id:'nmims-startupgarage', roi:{prof:5,money:2,mind:4,cult:2,fun:3,cost:1,drain:1},
    cat:'startup', name:'Startup Garage \u2014 E-Cell NMIMS', place:'NMIMS, Mumbai',
    country:'India', month:9, verified:'typical',
    vibe:'Founder-led speaker sessions, 200\u2013250 students.',
    tips:['Smaller and more useful than the big summits \u2014 you actually get to talk to people.'] },
  { id:'nmims-venturesome', roi:{prof:4,money:2,mind:3,cult:2,fun:4,cost:1,drain:1},
    cat:'startup', name:'Venturesome \u2014 E-Cell NMIMS', place:'NMIMS, Mumbai',
    country:'India', month:10, verified:'typical',
    vibe:'Student entrepreneurship competition, 150\u2013200 participants.',
    tips:['Good for spotting talent \u2014 several of the best interns come from these rooms.'] },
  { id:'nmims-ibl', roi:{prof:4,money:2,mind:4,cult:2,fun:3,cost:1,drain:2},
    cat:'startup', name:'Indian Business League \u2014 E-Cell NMIMS', place:'NMIMS, Mumbai',
    country:'India', month:11, verified:'typical',
    vibe:'National-level business case competition, 50+ colleges.',
    tips:['National reach \u2014 a good place for a brand to be seen by students outside Mumbai too.'] }
];

window.RW_EVENT_CATS = [
  { id:'music',   label:'Music',      icon:'\ud83c\udfb8', color:'#C084FC' },
  { id:'startup', label:'Startup',    icon:'\ud83d\ude80', color:'#4ADE80' },
  { id:'sports',  label:'Sports',     icon:'\ud83c\udfc3', color:'#38BDF8' },
  { id:'auto',    label:'Automobile', icon:'\ud83d\ude97', color:'#F0A63B' },
  { id:'tech',    label:'Tech & AI',  icon:'\ud83e\udde0', color:'#7C6BFF' },
  { id:'moments', label:'World moments', icon:'\ud83c\udf0d', color:'#FB7185' },
];
