/* ============================================================================
   RW_REGIONS — states, regions and circuits people actually search for.
   ============================================================================
   Febin's bug: searching "Kerala" said "No match", which reads as
   "Kerala isn't available". A region is not a city, so it was in no list.
   These make broad searches resolve, and each carries the honest local truth
   that makes RoamWise different from a generic planner.
   ========================================================================= */
window.RW_REGIONS = [
  { name:'Kerala', alias:['gods own country','god\'s own country'], terrain:'coastal',
    blurb:'Backwaters, hills and coast',
    bases:['Kochi','Alleppey','Munnar','Varkala','Wayanad'],
    truth:'Kochi to Munnar is 4-5 hours on hill roads, not the 3 hours maps suggest. Backwater houseboats are cheapest booked in Alleppey itself, not online.' },
  { name:'Rajasthan', alias:['marwar','desert circuit'], terrain:'desert',
    blurb:'Forts, desert and palaces',
    bases:['Jaipur','Jodhpur','Udaipur','Jaisalmer','Pushkar'],
    truth:'Distances are long and flat — Jaipur to Jaisalmer is 10+ hours. Overnight trains save a day. Avoid April-June; 45C is not sightseeing weather.' },
  { name:'Himachal Pradesh', alias:['himachal','hp'], terrain:'himalayan',
    blurb:'Mountains, valleys and high passes',
    bases:['Manali','Shimla','Kasol','Dharamshala','Spiti'],
    truth:'Mountain roads run at ~22-32 km/h, not highway speed. Spiti is only open roughly May-October. Never trust a same-day plan across two valleys.' },
  { name:'Goa', alias:['north goa','south goa'], terrain:'coastal',
    blurb:'Beaches, Portuguese heritage and nightlife',
    bases:['Anjuna','Calangute','Palolem','Panaji','Arambol'],
    truth:'North Goa is busy and social; South Goa is quiet. Scooter is the only sane transport. Taxi cartels mean rates are fixed and high — factor it in.' },
  { name:'Uttarakhand', alias:['garhwal','kumaon','devbhoomi'], terrain:'himalayan',
    blurb:'Himalayan pilgrimage, rivers and hill towns',
    bases:['Rishikesh','Nainital','Almora','Mussoorie','Auli'],
    truth:'Char Dham roads are seasonal and crowded May-June. Rishikesh to Almora is 7-8 hours, not 4. Book Valley of Flowers permits before you travel.' },
  { name:'Ladakh', alias:['leh','leh ladakh'], terrain:'himalayan',
    blurb:'High-altitude desert and passes',
    bases:['Leh','Nubra','Pangong','Kargil'],
    truth:'Altitude is the real constraint: budget 2 full days in Leh acclimatising before any pass. Inner Line Permits needed for Nubra and Pangong.' },
  { name:'Northeast India', alias:['north east','seven sisters','ne india'], terrain:'hill',
    blurb:'Living root bridges, valleys and tribal culture',
    bases:['Shillong','Guwahati','Tawang','Ziro','Kaziranga'],
    truth:'Arunachal needs an Inner Line Permit. Roads are slow and beautiful — Guwahati to Tawang is a 2-day drive, not one. Monsoon here is serious.' },
  { name:'Kashmir', alias:['jammu and kashmir','srinagar valley'], terrain:'himalayan',
    blurb:'Valleys, lakes and alpine meadows',
    bases:['Srinagar','Gulmarg','Pahalgam','Sonmarg'],
    truth:'Check current advisories before booking. Srinagar houseboats vary hugely — see photos of the actual boat, not the category.' },
  { name:'Karnataka', alias:['coorg','kodagu','bengaluru'], terrain:'ghats',
    blurb:'Coffee hills, coast and heritage ruins',
    bases:['Bengaluru','Coorg','Hampi','Gokarna','Chikmagalur'],
    truth:'Hampi is best October-February; summer is brutal. Coorg roads are winding — 100km takes 3 hours.' },
  { name:'Tamil Nadu', alias:['ooty','nilgiris','chennai'], terrain:'plains',
    blurb:'Temples, hill stations and coast',
    bases:['Chennai','Ooty','Kodaikanal','Madurai','Pondicherry'],
    truth:'Temple towns need modest dress and early starts. The Nilgiri Mountain Railway must be booked well ahead.' },
  { name:'Maharashtra', alias:['mumbai','konkan','sahyadri'], terrain:'ghats',
    blurb:'Forts, Western Ghats and coastline',
    bases:['Mumbai','Lonavala','Mahabaleshwar','Konkan coast'],
    truth:'Monsoon (June-Sept) is when the Ghats are spectacular and also when trekking gets genuinely dangerous. Pick your side.' },
  { name:'Andaman Islands', alias:['andaman','havelock','port blair'], terrain:'coastal',
    blurb:'Islands, reefs and quiet beaches',
    bases:['Port Blair','Havelock','Neil Island'],
    truth:'Inter-island ferries are the whole itinerary — book them first, everything else fits around. Mobile data is poor; download offline.' },
  { name:'Meghalaya', alias:['shillong','cherrapunji','sohra'], terrain:'hill',
    blurb:'Waterfalls, caves and root bridges',
    bases:['Shillong','Cherrapunji','Dawki','Mawlynnong'],
    truth:'The double-decker root bridge is a 3,000-step round trip — it is a hike, not a viewpoint. Wettest place on Earth; plan for rain regardless of month.' },
  { name:'Sikkim', alias:['gangtok','north sikkim'], terrain:'himalayan',
    blurb:'Monasteries, high lakes and Kanchenjunga views',
    bases:['Gangtok','Pelling','Lachung','Yuksom'],
    truth:'North Sikkim needs permits arranged through a registered operator. Roads close often — always keep a buffer day.' },
  { name:'Punjab', alias:['amritsar','chandigarh'], terrain:'plains',
    blurb:'Golden Temple, food and border ceremony',
    bases:['Amritsar','Chandigarh','Patiala'],
    truth:'Golden Temple langar is free and open to everyone. Wagah border ceremony fills up hours early — go by 3pm.' }
];
