/* AUTO-GENERATED by .github/workflows/tusk-daily.yml — do not edit by hand.
   Places real users asked about that Tusk did not know, resolved once
   against OpenStreetMap so they work offline from now on.
   Last updated: 2026-09-03  */
window.RW_LEARNED_PLACES = {
}
;
