/* RoamWise Cinematic Map V5.1
 * Correctness first: never invent/fallback a day coordinate just to draw a line.
 * Renderer: MapLibre GL JS loaded only when Cinematic mode actually mounts.
 * Default tiles: OpenFreeMap. Future static PMTiles can be selected in RW_CONFIG.maps.
 */
(function(){'use strict';
const CFG=()=>Object.assign({styleUrl:'https://tiles.openfreemap.org/styles/liberty',maplibreJs:'https://unpkg.com/maplibre-gl@5/dist/maplibre-gl.js',maplibreCss:'https://unpkg.com/maplibre-gl@5/dist/maplibre-gl.css'},window.RW_CONFIG?.maps||{});
const cache={};let mainMap=null,anim=0,watcher=null;
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const norm=v=>clean(v).toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,' ').trim();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function hav(a,b){const R=6371,p=Math.PI/180,dlat=(b.lat-a.lat)*p,dlon=(b.lng-a.lng)*p,x=Math.sin(dlat/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(dlon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function dbCenter(name){try{const n=norm(name),d=(window.DB||[]).find(x=>norm(x.name)===n||norm(x.name).includes(n)||n.includes(norm(x.name)));if(d&&isFinite(+d.lat)&&isFinite(+d.lon))return{lat:+d.lat,lng:+d.lon,name:d.name,source:'db'}}catch(_){}return null}
function tripDestination(){return clean(document.querySelector('#destInput')?.value||window._lastItin?.name||window._lastItin?.destination||'')}
function wideTrip(dest){return /\b(india|japan|vietnam|thailand|italy|greece|iceland|turkey|türkiye|egypt|nepal|bhutan|sri lanka|new zealand|kenya|tanzania|circuit|grand|road trip|northeast|north east)\b|\/|&/.test(norm(dest))}
function maxRadius(dest){return wideTrip(dest)?1500:450}
function loadCss(url){if(document.querySelector('link[data-rw-maplibre]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href=url;l.dataset.rwMaplibre='1';document.head.appendChild(l)}
function loadMapLibre(){if(window.maplibregl)return Promise.resolve(window.maplibregl);if(window.__rwMapLibrePromise)return window.__rwMapLibrePromise;const c=CFG();loadCss(c.maplibreCss);window.__rwMapLibrePromise=new Promise((res,rej)=>{const s=document.createElement('script');s.src=c.maplibreJs;s.async=true;s.dataset.rwMaplibre='1';s.onload=()=>res(window.maplibregl);s.onerror=()=>rej(new Error('MapLibre unavailable'));document.head.appendChild(s)});return window.__rwMapLibrePromise}
function cacheGet(k){if(cache[k])return cache[k];try{return JSON.parse(sessionStorage.getItem('rw_geo_v51_'+k)||'null')}catch(_){return null}}
function cacheSet(k,v){cache[k]=v;try{sessionStorage.setItem('rw_geo_v51_'+k,JSON.stringify(v))}catch(_){}return v}
function choose(cands,center,radius){const sane=cands.filter(x=>isFinite(x.lat)&&isFinite(x.lng));if(!sane.length)return null;if(!center)return sane[0];const ranked=sane.map(x=>({...x,km:hav(center,x)})).sort((a,b)=>a.km-b.km);return ranked[0].km<=radius?ranked[0]:null}
async function geocode(q,center,radius){q=clean(q);if(!q)return null;const key=norm(q)+'_'+Math.round(center?.lat||0)+'_'+Math.round(center?.lng||0),hit=cacheGet(key);if(hit!==null)return hit||null;
  try{const u='https://geocoding-api.open-meteo.com/v1/search?name='+encodeURIComponent(q)+'&count=8&language=en&format=json',r=await fetch(u,{cache:'force-cache'});if(r.ok){const js=await r.json(),c=(js.results||[]).map(x=>({lat:+x.latitude,lng:+x.longitude,name:x.name,admin:[x.admin1,x.country].filter(Boolean).join(', '),source:'open-meteo'})),best=choose(c,center,radius);if(best)return cacheSet(key,best)}}catch(_){}
  try{const u='https://photon.komoot.io/api/?limit=6&q='+encodeURIComponent(q),r=await fetch(u,{cache:'force-cache',headers:{Accept:'application/json'}});if(r.ok){const js=await r.json(),c=(js.features||[]).map(f=>({lat:+f.geometry.coordinates[1],lng:+f.geometry.coordinates[0],name:f.properties?.name||q,admin:[f.properties?.state,f.properties?.country].filter(Boolean).join(', '),source:'photon'})),best=choose(c,center,radius);if(best)return cacheSet(key,best)}}catch(_){}
  cacheSet(key,false);return null;
}
function titleStop(day,dest){const raw=clean(day?.place||day?.location||day?.title||day?.name||'');if(!raw)return dest;let a=raw.split(/→|->|\bto\b/i).map(clean).filter(Boolean),x=a[a.length-1]||raw;x=x.replace(/^day\s*\d+\s*[:.\-–—]?\s*/i,'').replace(/^(arrival|departure|rest day|free day|buffer day)$/i,'');return clean(x)||dest}
function days(){return Array.isArray(window._lastItin?.days)?window._lastItin.days:[]}
async function resolveDays(){const dest=tripDestination(),center=dbCenter(dest)||await geocode(dest,null,20000),rad=maxRadius(dest),out=[];for(let i=0;i<days().length;i++){const d=days()[i],name=titleStop(d,dest);let geo=null;if(norm(name)===norm(dest))geo=center;else geo=await geocode(name+', '+dest,center,rad)||await geocode(name,center,rad);out.push({day:Number(d.day||d.n||i+1),name,geo});}return{dest,center,points:out}}
async function osrm(a,b){const straight=hav(a,b);if(straight<.05)return{coords:[[a.lng,a.lat],[b.lng,b.lat]],distance:straight*1000,kind:'local'};if(straight>1800)return{coords:[[a.lng,a.lat],[b.lng,b.lat]],distance:straight*1000,kind:'transfer'};for(const base of ['https://router.project-osrm.org/route/v1/driving/','https://routing.openstreetmap.de/routed-car/route/v1/driving/']){try{const url=base+[a,b].map(p=>p.lng.toFixed(6)+','+p.lat.toFixed(6)).join(';')+'?overview=full&geometries=geojson',r=await fetch(url,{cache:'force-cache'});if(!r.ok)continue;const rt=(await r.json()).routes?.[0];if(!rt?.geometry?.coordinates?.length)continue;const roadKm=(rt.distance||0)/1000;if(roadKm>0&&roadKm<=Math.max(straight*7,straight+250))return{coords:rt.geometry.coordinates,distance:rt.distance,kind:'road'}}catch(_){}}return{coords:[[a.lng,a.lat],[b.lng,b.lat]],distance:straight*1000,kind:'estimate'}
}
async function segments(points){const out=[];for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i];if(!a.geo||!b.geo)continue;/* crucial: only consecutive resolved days connect */if(Number(b.day)!==Number(a.day)+1)continue;out.push({from:a,to:b,route:await osrm(a.geo,b.geo)})}return out}
function style(){return CFG().styleUrl}
function runnerSvg(){return '<div class="rw-v51-runner" aria-hidden="true"><svg viewBox="0 0 44 44"><path d="M19 5c5-4 12 0 10 7-1 4-5 6-9 4-4-2-4-8-1-11Z"/><path d="M15 12 30 9l8-5-3 8-7 4Z" class="band"/><path d="M20 17c5-1 9 3 8 8l-2 5 8 7-4 4-10-8-5 8-6-2 7-12-6-4 3-5 7 4Z"/><path d="M15 22 6 30l-3-4 9-10Z"/></svg></div>'}
function addBaseStyles(){if(document.querySelector('#rwV51MapCss'))return;const s=document.createElement('style');s.id='rwV51MapCss';s.textContent=`#rwV5LiveMap.rw-v51-map,.rw-v51-daymap{position:relative;min-height:360px;overflow:hidden;border-radius:18px;background:#0a0d13}.rw-v51-daymap{min-height:260px}.rw-v51-badge{position:absolute;z-index:4;left:10px;top:10px;padding:6px 9px;border-radius:99px;background:rgba(7,9,15,.82);border:1px solid rgba(255,255,255,.14);color:#eee;font:700 10px/1.2 system-ui;backdrop-filter:blur(8px)}.rw-v51-note{padding:18px;color:#aaa;font:12px/1.5 system-ui}.rw-v51-runner{width:34px;height:34px;border-radius:50%;display:grid;place-items:center;background:rgba(9,9,12,.92);box-shadow:0 0 0 2px rgba(255,55,65,.5),0 8px 22px #0008}.rw-v51-runner svg{width:27px;height:27px;fill:#e8e5df}.rw-v51-runner .band{fill:#ef3442}.maplibregl-marker.rw-v51-daypin{font:800 10px system-ui;color:#fff;background:#c52c36;border:2px solid #fff3;border-radius:99px;padding:5px 7px;box-shadow:0 5px 16px #0008}@media(prefers-reduced-motion:reduce){.rw-v51-runner{display:none}}`;document.head.appendChild(s)}
function fallbackSvg(host,points,segs){const valid=points.filter(p=>p.geo);if(!valid.length){host.innerHTML='<div class="rw-v51-note">No validated route coordinates were returned. The itinerary remains available without drawing a misleading route.</div>';return}const xs=valid.map(p=>p.geo.lng),ys=valid.map(p=>p.geo.lat),minx=Math.min(...xs),maxx=Math.max(...xs),miny=Math.min(...ys),maxy=Math.max(...ys),px=x=>30+(x-minx)/(maxx-minx||1)*540,py=y=>300-(y-miny)/(maxy-miny||1)*260;host.innerHTML='<svg viewBox="0 0 600 340" style="width:100%;height:100%;background:#090c13"><g stroke="#202735" stroke-width="1">'+Array.from({length:9},(_,i)=>`<path d="M0 ${i*42}H600M${i*75} 0V340"/>`).join('')+'</g>'+segs.map(s=>`<path d="${s.route.coords.map((c,i)=>(i?'L':'M')+px(c[0]).toFixed(1)+' '+py(c[1]).toFixed(1)).join(' ')}" fill="none" stroke="${s.route.kind==='road'?'#ef3946':'#e7b65e'}" stroke-width="3" ${s.route.kind!=='road'?'stroke-dasharray="7 7"':''}/>`).join('')+valid.map(p=>`<g><circle cx="${px(p.geo.lng)}" cy="${py(p.geo.lat)}" r="8" fill="#c52c36"/><text x="${px(p.geo.lng)}" y="${py(p.geo.lat)-13}" fill="#fff" text-anchor="middle" font-size="11">D${p.day}</text></g>`).join('')+'</svg>'}
async function renderMap(host,points,segs,small=false){if(!host)return;addBaseStyles();host.innerHTML='';host.classList.add(small?'rw-v51-daymap':'rw-v51-map');try{const ml=await loadMapLibre(),map=new ml.Map({container:host,style:style(),center:[points.find(p=>p.geo)?.geo.lng||0,points.find(p=>p.geo)?.geo.lat||0],zoom:4,attributionControl:true});if(!small)mainMap=map;map.on('load',()=>{const lineFeatures=segs.map((s,i)=>({type:'Feature',properties:{kind:s.route.kind,i},geometry:{type:'LineString',coordinates:s.route.coords}}));map.addSource('rw-routes',{type:'geojson',data:{type:'FeatureCollection',features:lineFeatures}});map.addLayer({id:'rw-transfer',type:'line',source:'rw-routes',filter:['!=',['get','kind'],'road'],paint:{'line-color':'#e7b65e','line-width':2.5,'line-dasharray':[2,2],'line-opacity':.8}});map.addLayer({id:'rw-road',type:'line',source:'rw-routes',filter:['==',['get','kind'],'road'],paint:{'line-color':'#ef3946','line-width':4,'line-opacity':.9}});const valid=points.filter(p=>p.geo);valid.forEach(p=>{const e=document.createElement('div');e.className='rw-v51-daypin';e.textContent=small?'•':'D'+p.day;new ml.Marker({element:e}).setLngLat([p.geo.lng,p.geo.lat]).setPopup(new ml.Popup({offset:18}).setHTML('<b>'+esc(p.name)+'</b>')).addTo(map)});if(valid.length>1){const b=new ml.LngLatBounds();valid.forEach(p=>b.extend([p.geo.lng,p.geo.lat]));map.fitBounds(b,{padding:small?35:55,maxZoom:small?12:9,duration:0})}if(!small)animateRunner(map,segs)});return map}catch(_){fallbackSvg(host,points,segs);return null}}
function animateRunner(map,segs){cancelAnimationFrame(anim);if(matchMedia('(prefers-reduced-motion: reduce)').matches||navigator.connection?.saveData)return;const coords=segs.flatMap((s,i)=>s.route.coords.slice(i?1:0));if(coords.length<2)return;const ml=window.maplibregl,e=document.createElement('div');e.innerHTML=runnerSvg();const marker=new ml.Marker({element:e.firstElementChild}).setLngLat(coords[0]).addTo(map);let i=0,last=0;function tick(t){if(!map||!map.getCanvas?.isConnected)return; if(t-last<80){anim=requestAnimationFrame(tick);return}last=t;i=(i+1)%coords.length;marker.setLngLat(coords[i]);anim=requestAnimationFrame(tick)}anim=requestAnimationFrame(tick)}
async function renderMain(){const host=document.querySelector('#rwV5LiveMap');if(!host||host.dataset.rwV51==='1')return;host.dataset.rwV51='1';host.innerHTML='<div class="rw-v51-note">Validating day locations before drawing the route…</div>';const r=await resolveDays(),segs=await segments(r.points);await renderMap(host,r.points,segs,false);const st=document.querySelector('#rwV5MapStatus');if(st){const missing=r.points.filter(p=>!p.geo).length,road=segs.filter(s=>s.route.kind==='road').length;st.textContent=`Validated map · ${road}/${segs.length} road legs${missing?' · '+missing+' unresolved stop'+(missing>1?'s':'')+' omitted':''}`}}
function phaseTexts(card){return Array.from(card.querySelectorAll('.rw-v5-phase')).map(x=>clean(x.querySelector('p')?.textContent)).filter(Boolean)}
function candidates(text){return (String(text).match(/\b[A-Z][A-Za-zÀ-ÿ'’.-]*(?:\s+(?:[A-Z][A-Za-zÀ-ÿ'’.-]*|of|the|&)){0,3}/g)||[]).map(clean).filter(x=>x.length>2&&!/^(Morning|Afternoon|Evening|Drive|Walk|Visit|Explore|Breakfast|Lunch|Dinner|Day|The|A|An)$/.test(x)).slice(0,3)}
async function renderDay(card,host){host.hidden=false;host.innerHTML='<div class="rw-v51-note">Validating local POIs…</div>';const dest=tripDestination(),dayNo=Number(card.dataset.rwDay||0),base=(await resolveDays()).points.find(p=>p.day===dayNo)?.geo||dbCenter(dest),names=[];for(const t of phaseTexts(card)){for(const n of candidates(t))if(!names.some(x=>norm(x)===norm(n)))names.push(n)}const pts=[];for(const n of names.slice(0,6)){const g=await geocode(n+', '+dest,base,100)||await geocode(n,base,100);if(g&&!pts.some(p=>hav(p.geo,g)<.08))pts.push({day:dayNo,name:n,geo:g})}if(base&&!pts.length)pts.push({day:dayNo,name:titleStop(days()[dayNo-1]||{},dest),geo:base});if(pts.length<2){host.innerHTML='<div class="rw-v51-note"><b>No safe local path drawn.</b><br>RoamWise could not validate at least two distinct POIs within the day area, so it is refusing to show a wrong connecting line.</div>';return}const segs=[];for(let i=1;i<pts.length;i++)segs.push({from:pts[i-1],to:pts[i],route:await osrm(pts[i-1].geo,pts[i].geo)});await renderMap(host,pts,segs,true)}
function interceptDayMaps(){document.addEventListener('click',e=>{const b=e.target.closest?.('[data-rw-day-map]');if(!b)return;const card=b.closest('.rw-v5-day'),host=card?.querySelector('.rw-v5-day-route');if(!card||!host)return;e.preventDefault();e.stopImmediatePropagation();if(host.dataset.rwV51Open==='1'){host.hidden=true;host.dataset.rwV51Open='0';return}host.dataset.rwV51Open='1';renderDay(card,host)},true)}
function observe(){if(watcher)return;watcher=new MutationObserver(()=>{if(document.querySelector('#rwCinematicMount #rwV5LiveMap'))renderMain()});watcher.observe(document.documentElement,{childList:true,subtree:true});renderMain()}
window.RW_CINEMATIC_MAP_V51={renderMain,geocode,resolveDays,version:'5.1.0'};addBaseStyles();interceptDayMaps();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',observe);else observe();
})();
