/* Cross-device auth/payment compatibility. Loaded independently so legacy app.js stays stable. */
(function(){'use strict';
function isApp(){return location.protocol==='file:'||!!window.RW||/RoamWiseApp/i.test(navigator.userAgent)}
function mobile(){return /Android|iPhone|iPad|Mobile/i.test(navigator.userAgent)}
function show(msg){try{if(typeof showToast==='function')showToast(msg);else alert(msg)}catch(e){}}
function helpLink(){return 'https://www.roamwise.co.in/help/payment-login.html'}
function boot(){if(typeof firebase==='undefined'||!firebase.auth){setTimeout(boot,250);return}
 var busy=false;
 function err(e){var c=e&&e.code||'';if(c==='auth/cancelled-popup-request')return show('Another sign-in was already opening. Please tap once and wait.');try{if(typeof authError==='function')authError((typeof friendly==='function'?friendly(e):(e.message||c)));else show(e.message||c)}catch(x){show('Sign-in failed. See Help for recovery steps.')}}
 function provider(kind){if(kind==='google')return new firebase.auth.GoogleAuthProvider();if(kind==='facebook')return new firebase.auth.FacebookAuthProvider();return new firebase.auth.OAuthProvider('apple.com')}
 function sign(kind){if(busy)return show('Sign-in is already opening — please wait.');if(isApp()){show('Secure social sign-in opens best in a full browser. Use Email here, or open RoamWise Help for device-specific steps.');try{var em=document.getElementById('authEmail');if(em)em.focus()}catch(e){}return}busy=true;var p=provider(kind);if(kind==='google'&&p.setCustomParameters)p.setCustomParameters({prompt:'select_account'});var done=function(){busy=false;try{if(typeof closeAuth==='function')closeAuth()}catch(e){}show('Signed in ✓')};var fail=function(e){busy=false;err(e)};try{if(mobile()&&location.protocol.indexOf('http')===0)firebase.auth().signInWithRedirect(p).catch(fail);else firebase.auth().signInWithPopup(p).then(done).catch(function(e){var c=e&&e.code||'';if(location.protocol.indexOf('http')===0&&(c==='auth/popup-blocked'||c==='auth/operation-not-supported-in-this-environment'))firebase.auth().signInWithRedirect(p).catch(fail);else fail(e)})}catch(e){fail(e)}}
 window.loginGoogle=function(){sign('google')};window.loginSocial=function(k){sign(k)};
 if(typeof window.payVia==='function'){var oldPay=window.payVia;window.payVia=function(app){if(isApp()&&!(typeof PLAY_MODE!=='undefined'&&PLAY_MODE&&window.RWBilling)){var amt=encodeURIComponent(String(window.UPI_AMT||'100'));var u='https://www.roamwise.co.in/pay/?amount='+amt+'&method='+encodeURIComponent(app||'upi');try{if(typeof openExternally==='function')openExternally(u);else if(window.RW&&RW.openExternal)RW.openExternal(u);else window.open(u,'_blank','noopener')}catch(e){window.location.href=u}show('Opening secure payment handoff in your device browser…');return}return oldPay.apply(this,arguments)}}
 if(typeof window.openGumroad==='function'){var oldG=window.openGumroad;window.openGumroad=function(){if(isApp()){var u='';try{u=localStorage.getItem('rw_gum_url')||''}catch(e){};if(!u)return oldG();try{if(typeof openExternally==='function')openExternally(u);else window.open(u,'_blank','noopener')}catch(e){window.open(u,'_blank','noopener')}return false}return oldG.apply(this,arguments)}}
 inject();}
function inject(){[['authOverlay','Having trouble signing in?'],['payOverlay','Payment not opening?']].forEach(function(x){var b=document.querySelector('#'+x[0]+' .modal-body');if(!b||b.querySelector('.rw-device-help'))return;var a=document.createElement('a');a.className='rw-device-help';a.href=helpLink();a.target='_blank';a.rel='noopener';a.textContent=x[1]+' Open self-help guide';a.style.cssText='display:block;text-align:center;margin:14px 0 2px;color:#bf8cff;font-size:12px';b.appendChild(a)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();