import {routePayment,shouldFallback,safeId} from './router-core.mjs';
import {verifyRazorpay,verifyCashfree,verifyStripe,verifyPayPal} from './webhook-verify.mjs';

const JSON_HEADERS={'content-type':'application/json; charset=utf-8','cache-control':'no-store'};
const TWO_DECIMAL=new Set(['INR','USD','EUR','GBP','AUD','CAD','SGD','NZD','AED','THB','CHF']);
function out(body,status=200,extra={}){return new Response(JSON.stringify(body),{status,headers:{...JSON_HEADERS,...extra}})}
function allowedOrigin(req,env){var o=req.headers.get('origin')||'';var allow=String(env.ALLOWED_ORIGINS||'https://roamwise.co.in,https://www.roamwise.co.in').split(',').map(x=>x.trim());return allow.includes(o)?o:''}
function cors(req,env){var o=allowedOrigin(req,env);return o?{'access-control-allow-origin':o,'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,x-idempotency-key','access-control-max-age':'86400','vary':'Origin'}:{}}
function major(amountMinor,currency){currency=String(currency||'INR').toUpperCase();if(!TWO_DECIMAL.has(currency))throw new Error('Configure currency exponent before enabling '+currency);return (Number(amountMinor)/100).toFixed(2)}
function catalog(env){try{return JSON.parse(env.PRODUCT_CATALOG_JSON||'{}')}catch(e){return{}}}
function productPrice(p,currency){if(!p)return 0;if(p.prices&&p.prices[currency]!=null)return Math.round(Number(p.prices[currency]));if(String(p.currency||'').toUpperCase()===currency&&p.amountMinor!=null)return Math.round(Number(p.amountMinor));return 0}
function basic(a,b){return'Basic '+btoa(a+':'+b)}
function idempotency(req){return safeId(req.headers.get('x-idempotency-key')||crypto.randomUUID())||crypto.randomUUID()}
async function readJson(req){try{return await req.json()}catch(e){throw Object.assign(new Error('Invalid JSON body'),{status:400})}}
async function logAttempt(env,row){if(!env.PAYMENTS_DB)return;try{await env.PAYMENTS_DB.prepare('INSERT OR IGNORE INTO payment_attempts(id, product_id, provider, amount_minor, currency, status, provider_ref, created_at) VALUES(?,?,?,?,?,?,?,?)').bind(row.id,row.productId,row.provider,row.amountMinor,row.currency,row.status,row.providerRef||'',new Date().toISOString()).run()}catch(e){}}

async function razorpay(input,env,key){var receipt=safeId('rw_'+key).slice(0,40),r=await fetch('https://api.razorpay.com/v1/orders',{method:'POST',headers:{Authorization:basic(env.RAZORPAY_KEY_ID,env.RAZORPAY_KEY_SECRET),'content-type':'application/json'},body:JSON.stringify({amount:input.amountMinor,currency:input.currency,receipt,notes:{product_id:input.productId,roamwise_key:key}})}),j=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(j.error&&j.error.description||'Razorpay order failed'),{provider:'razorpay',status:r.status});return{provider:'razorpay',providerRef:j.id,checkout:{kind:'razorpay_order',orderId:j.id,keyId:env.RAZORPAY_KEY_ID,amount:j.amount,currency:j.currency}}}
async function cashfree(input,env,key){if(!input.customer||!String(input.customer.phone||'').trim())throw Object.assign(new Error('Cashfree route needs customer.phone'),{provider:'cashfree',status:422});var live=String(env.CASHFREE_ENV||'sandbox')==='live',base=live?'https://api.cashfree.com':'https://sandbox.cashfree.com',body={order_id:safeId('rw_'+key),order_amount:Number(major(input.amountMinor,input.currency)),order_currency:input.currency,customer_details:{customer_id:safeId(input.customer.id||'rw_'+key),customer_phone:String(input.customer.phone).replace(/\s+/g,'').slice(0,20)}};if(input.customer.email)body.customer_details.customer_email=String(input.customer.email).slice(0,160);if(env.PAYMENT_RETURN_URL)body.order_meta={return_url:env.PAYMENT_RETURN_URL};var r=await fetch(base+'/pg/orders',{method:'POST',headers:{'content-type':'application/json','x-api-version':env.CASHFREE_API_VERSION||'2026-01-01','x-client-id':env.CASHFREE_APP_ID,'x-client-secret':env.CASHFREE_SECRET_KEY,'x-request-id':key,'x-idempotency-key':key},body:JSON.stringify(body)}),j=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(j.message||'Cashfree order failed'),{provider:'cashfree',status:r.status});return{provider:'cashfree',providerRef:j.order_id||String(j.cf_order_id||''),checkout:{kind:'cashfree_session',paymentSessionId:j.payment_session_id,orderId:j.order_id,environment:live?'production':'sandbox'}}}
async function stripe(input,env,key){var b=new URLSearchParams();b.set('amount',String(input.amountMinor));b.set('currency',input.currency.toLowerCase());b.set('automatic_payment_methods[enabled]','true');b.set('metadata[product_id]',input.productId);b.set('metadata[roamwise_key]',key);if(input.customer&&input.customer.email)b.set('receipt_email',String(input.customer.email).slice(0,160));var r=await fetch('https://api.stripe.com/v1/payment_intents',{method:'POST',headers:{Authorization:'Bearer '+env.STRIPE_SECRET_KEY,'content-type':'application/x-www-form-urlencoded','Idempotency-Key':key},body:b}),j=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(j.error&&j.error.message||'Stripe PaymentIntent failed'),{provider:'stripe',status:r.status});return{provider:'stripe',providerRef:j.id,checkout:{kind:'stripe_payment_intent',clientSecret:j.client_secret,paymentIntentId:j.id}}}
async function paypalToken(env){var base=String(env.PAYPAL_ENV||'sandbox')==='live'?'https://api-m.paypal.com':'https://api-m.sandbox.paypal.com',r=await fetch(base+'/v1/oauth2/token',{method:'POST',headers:{Authorization:basic(env.PAYPAL_CLIENT_ID,env.PAYPAL_CLIENT_SECRET),'content-type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials'}),j=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error('PayPal OAuth failed'),{provider:'paypal',status:r.status});return{base,token:j.access_token}}
async function paypal(input,env,key){var a=await paypalToken(env),body={intent:'CAPTURE',purchase_units:[{reference_id:key,custom_id:input.productId,amount:{currency_code:input.currency,value:major(input.amountMinor,input.currency)}}]},r=await fetch(a.base+'/v2/checkout/orders',{method:'POST',headers:{Authorization:'Bearer '+a.token,'content-type':'application/json','PayPal-Request-Id':key,Prefer:'return=representation'},body:JSON.stringify(body)}),j=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(j.message||'PayPal order failed'),{provider:'paypal',status:r.status});var approve=(j.links||[]).find(x=>x.rel==='approve');return{provider:'paypal',providerRef:j.id,checkout:{kind:'paypal_order',orderId:j.id,approveUrl:approve&&approve.href||''}}}
async function directUpi(input,env,key){if(input.currency!=='INR')throw Object.assign(new Error('Direct UPI supports INR only'),{provider:'direct_upi',status:422});var vpa=String(env.DIRECT_UPI_VPA||''),name=String(env.DIRECT_UPI_NAME||'RoamWise'),note=('RoamWise '+input.productId+' '+key).slice(0,80),url='upi://pay?pa='+encodeURIComponent(vpa)+'&pn='+encodeURIComponent(name)+'&am='+encodeURIComponent(major(input.amountMinor,'INR'))+'&cu=INR&tn='+encodeURIComponent(note);return{provider:'direct_upi',providerRef:key,checkout:{kind:'upi_deeplink',url,requiresManualReconciliation:true}}}
const ADAPTERS={razorpay,cashfree,stripe,paypal,direct_upi:directUpi};

async function createPayment(req,env){var b=await readJson(req),products=catalog(env),p=products[b.productId];if(!p)return out({error:'unknown_product',message:'Checkout product is not configured server-side.'},400,cors(req,env));var currency=String(b.currency||p.currency||'INR').toUpperCase(),amountMinor=productPrice(p,currency);if(amountMinor<=0)return out({error:'unsupported_currency'},400,cors(req,env));var key=idempotency(req),input={productId:String(b.productId),amountMinor,currency,country:String(b.country||'IN').toUpperCase(),method:String(b.method||'card').toLowerCase(),cardOrigin:b.cardOrigin&&String(b.cardOrigin).toUpperCase(),domestic:b.domestic===true,recurring:!!p.recurring,customer:b.customer||null},route=routePayment(input,env);if(!route.candidates.length)return out({error:'no_payment_route',route},503,cors(req,env));var errors=[];for(var c of route.candidates){try{var result=await ADAPTERS[c.provider](input,env,key);await logAttempt(env,{id:key,productId:input.productId,provider:c.provider,amountMinor,currency,status:'created',providerRef:result.providerRef});return out({idempotencyKey:key,product:{id:input.productId,amountMinor,currency},route:{chosen:c,candidates:route.candidates},...result},200,cors(req,env))}catch(e){errors.push({provider:c.provider,status:e.status||0,message:e.message||'provider error'});await logAttempt(env,{id:key+'_'+c.provider,productId:input.productId,provider:c.provider,amountMinor,currency,status:'failed'});if(!shouldFallback(Number(e.status||0))&&Number(e.status||0)!==422)break}}
return out({error:'payment_route_failed',attempts:errors},502,cors(req,env))}

async function quote(req,env){var b=await readJson(req);try{return out(routePayment(b,env),200,cors(req,env))}catch(e){return out({error:e.message},400,cors(req,env))}}
async function webhook(req,env,provider){var raw=await req.text(),event;try{event=JSON.parse(raw)}catch(e){return out({error:'invalid_json'},400)}var ok=false;if(provider==='razorpay')ok=await verifyRazorpay(raw,req.headers,env);else if(provider==='cashfree')ok=await verifyCashfree(raw,req.headers,env);else if(provider==='stripe')ok=await verifyStripe(raw,req.headers,env);else if(provider==='paypal')ok=await verifyPayPal(event,req.headers,env);if(!ok)return out({error:'invalid_signature'},401);var eventId=String(event.id||event.event_id||event.data&&event.data.order&&event.data.order.order_id||crypto.randomUUID()).slice(0,180);if(env.PAYMENTS_DB)try{await env.PAYMENTS_DB.prepare('INSERT OR IGNORE INTO payment_events(event_id, provider, event_type, received_at, payload_json) VALUES(?,?,?,?,?)').bind(eventId,provider,String(event.event||event.type||event.event_type||'unknown').slice(0,120),new Date().toISOString(),raw.slice(0,50000)).run()}catch(e){}if(env.PAYMENT_FULFILLMENT_URL&&env.PAYMENT_FULFILLMENT_SECRET)try{await fetch(env.PAYMENT_FULFILLMENT_URL,{method:'POST',headers:{'content-type':'application/json','authorization':'Bearer '+env.PAYMENT_FULFILLMENT_SECRET},body:JSON.stringify({provider,eventId,event})})}catch(e){}return out({ok:true,eventId})}

export default {async fetch(req,env){var u=new URL(req.url),c=cors(req,env);if(req.method==='OPTIONS')return new Response(null,{status:204,headers:c});if(req.method==='GET'&&u.pathname==='/health')return out({status:'ok',service:'roamwise-payment-router',providers:Object.keys(routePayment({amountMinor:10000,country:'IN',currency:'INR',method:'card'},env).candidates.reduce((a,x)=>(a[x.provider]=true,a),{}))},200,c);if(req.method==='POST'&&u.pathname==='/v1/payments/route')return quote(req,env);if(req.method==='POST'&&u.pathname==='/v1/payments/create')return createPayment(req,env);var m=u.pathname.match(/^\/v1\/webhooks\/(razorpay|cashfree|stripe|paypal)$/);if(req.method==='POST'&&m)return webhook(req,env,m[1]);return out({error:'not_found'},404,c)}};
