const test = require('node:test');
const assert = require('node:assert');
const m = require('../local-help-data.js');

test('every town appears once and belongs to a district', () => {
  const towns = m.rwLocalTowns().map(t => t.town);
  assert.strictEqual(new Set(towns).size, towns.length);
  assert.ok(towns.includes('Almora') && towns.includes('Kausani'));
  assert.strictEqual(m.RW_LOCAL_DISTRICTS.length, 6);
});

test('gateways are real towns in the list', () => {
  const towns = m.rwLocalTowns().map(t => t.town);
  m.RW_LOCAL_GATEWAYS.forEach(g => assert.ok(towns.includes(g), g));
});

test('providers without consent are never returned', () => {
  m.RW_LOCAL_PROVIDERS.push({ id: 'a', cat: 'taxi', town: 'Almora', name: 'No consent', phone: '9876543210' });
  m.RW_LOCAL_PROVIDERS.push({ id: 'b', cat: 'taxi', town: 'Almora', name: 'Consented', phone: '9876543210', consentAt: '2026-10-09', verified: 'called' });
  const r = m.rwLocalFind('taxi', 'Almora');
  assert.deepStrictEqual(r.map(p => p.id), ['b']);
  assert.strictEqual(m.rwLocalCount('Almora'), 1);
  assert.strictEqual(m.rwLocalFind('guide', 'Almora').length, 0);
  assert.strictEqual(m.rwLocalFind('all', 'Kausani').length, 0);
  m.RW_LOCAL_PROVIDERS.length = 0;
});

test('whatsapp and tel links are built safely or omitted', () => {
  assert.strictEqual(m.rwLocalWhatsApp({ phone: '98765 43210' }, 'Hi there'), 'https://wa.me/919876543210?text=Hi%20there');
  assert.strictEqual(m.rwLocalWhatsApp({ phone: '123' }), '');
  assert.strictEqual(m.rwLocalWhatsApp(null), '');
  assert.strictEqual(m.rwLocalTel({ phone: '+91 98765-43210' }), 'tel:+919876543210');
  assert.strictEqual(m.rwLocalTel({ phone: '12' }), '');
});

test('get-listed mailto carries the town and a consent line', () => {
  const u = m.rwLocalListMail('Kausani');
  assert.ok(u.startsWith('mailto:support@roamwise.co.in?'));
  assert.ok(decodeURIComponent(u).includes('Town: Kausani'));
  assert.ok(decodeURIComponent(u).includes('I agree to be listed'));
});

test('rental category exists and old listings age out automatically', () => {
  assert.ok(m.RW_LOCAL_CATEGORIES.some(c => c.id === 'rental'));
  const now = Date.parse('2026-10-09');
  const fresh = { cat: 'taxi', town: 'Almora', name: 'A', consentAt: '2026-01-01', updatedAt: '2026-06-01' };
  const stale = { cat: 'taxi', town: 'Almora', name: 'B', consentAt: '2024-01-01', updatedAt: '2025-06-01' };
  m.RW_LOCAL_PROVIDERS.push(fresh, stale);
  assert.deepStrictEqual(m.rwLocalFind('taxi', 'Almora', now).map(p => p.name), ['A']);
  assert.strictEqual(m.rwLocalFresh({ name: 'no dates' }, now), false);
  m.RW_LOCAL_PROVIDERS.length = 0;
});

test('month label, remove link', () => {
  assert.strictEqual(m.rwLocalMonth({ updatedAt: '2026-03-04' }), 'Mar 2026');
  assert.strictEqual(m.rwLocalMonth({}), '');
  const u = decodeURIComponent(m.rwLocalRemoveMail({ name: 'Ram', id: 'kb-1234abcd' }));
  assert.ok(u.includes('Listing id: kb-1234abcd') && u.includes('Remove my RoamWise'));
});

test('generated listings file is clean and was fresh when generated', () => {
  const fs = require('node:fs'), path = require('node:path');
  const src = fs.readFileSync(path.join(__dirname, '..', 'local-help-listings.js'), 'utf8');
  const gen = /generated by tools\/import-kumaon-bazaar\.py on (\d{4}-\d{2}-\d{2})/i.exec(src);
  assert.ok(gen, 'header with generation date');
  const genMs = Date.parse(gen[1]);
  m.RW_LOCAL_PROVIDERS.length = 0;
  new Function('RW_LOCAL_PROVIDERS', 'window', src)(m.RW_LOCAL_PROVIDERS, {});
  const list = m.RW_LOCAL_PROVIDERS.slice(); m.RW_LOCAL_PROVIDERS.length = 0;
  assert.ok(list.length > 20, 'imported something');
  const towns = new Set(m.rwLocalTowns().map(t => t.town)), cats = new Set(m.RW_LOCAL_CATEGORIES.map(c => c.id));
  const ids = new Set();
  list.forEach(p => {
    assert.ok(!ids.has(p.id), 'unique id ' + p.id); ids.add(p.id);
    assert.ok(towns.has(p.town), 'known town ' + p.town);
    assert.ok(cats.has(p.cat), 'known category ' + p.cat);
    assert.strictEqual(p.verified, 'kb');
    assert.ok(/^[6-9]\d{9}$/.test(p.phone), 'valid mobile for ' + p.id);
    assert.ok(p.name && p.name.length >= 2);
    assert.ok(p.consentAt && p.updatedAt);
    assert.ok(genMs - Date.parse(p.updatedAt) <= 365 * 86400000, 'fresh at generation: ' + p.id);
    assert.ok(p.cat !== 'health' || !/ambulance/i.test(p.svc + p.name), 'no ambulance listings');
    ['govt_id', 'agent_code', 'user_id', 'photo'].forEach(k => assert.ok(!(k in p)));
  });
});

test('google maps link-out is an official search URL, not scraped data', () => {
  const u = new URL(m.rwLocalMapsUrl('taxi', 'Kausani'));
  assert.strictEqual(u.origin + u.pathname, 'https://www.google.com/maps/search/');
  assert.strictEqual(u.searchParams.get('api'), '1');
  assert.strictEqual(u.searchParams.get('query'), 'taxi service near Kausani, Uttarakhand');
  m.RW_LOCAL_CATEGORIES.forEach(c => assert.ok(c.maps, 'maps query for ' + c.id));
});

test('per-entry maxAgeDays is honoured by the freshness rule', () => {
  const now = Date.parse('2026-10-09');
  const p = { consentAt: '2024-01-01', updatedAt: '2024-01-01' };
  assert.equal(m.rwLocalFresh(p, now), false);
  assert.equal(m.rwLocalFresh(Object.assign({ maxAgeDays: 1095 }, p), now), true);
  assert.equal(m.rwLocalFresh({ consentAt: '2022-01-01', maxAgeDays: 1095 }, now), false);
});

test('generated OpenStreetMap file is attributed, clean and fresh when generated', () => {
  const fs = require('node:fs'), path = require('node:path');
  const src = fs.readFileSync(path.join(__dirname, '..', 'local-help-osm.js'), 'utf8');
  const gen = /generated by tools\/import-openstreetmap\.py on (\d{4}-\d{2}-\d{2})/i.exec(src);
  assert.ok(gen, 'header with generation date');
  assert.match(src, /OpenStreetMap contributors/);
  assert.match(src, /ODbL/);
  const genMs = Date.parse(gen[1]);
  const sandbox = { window: {}, RW_LOCAL_PROVIDERS: [] };
  new Function('window', 'RW_LOCAL_PROVIDERS', src)(sandbox.window, sandbox.RW_LOCAL_PROVIDERS);
  const list = sandbox.RW_LOCAL_PROVIDERS;
  assert.ok(list.length > 20);
  const cats = new Set(m.RW_LOCAL_CATEGORIES.map(c => c.id));
  const towns = new Set(m.rwLocalTowns().map(t => t.town));
  const ids = new Set();
  list.forEach(p => {
    assert.ok(!ids.has(p.id), 'unique ' + p.id); ids.add(p.id);
    assert.match(p.id, /^osm-[nwr]\d+$/);
    assert.ok(cats.has(p.cat), 'cat ' + p.cat);
    assert.ok(towns.has(p.town), 'town ' + p.town);
    assert.ok(p.name && p.name.trim().length > 1);
    assert.equal(p.source, 'openstreetmap');
    assert.equal(p.verified, 'osm');
    assert.ok(typeof p.lat === 'number' && typeof p.lon === 'number');
    assert.ok(p.maxAgeDays <= 1095);
    assert.ok(genMs - Date.parse(p.updatedAt) <= p.maxAgeDays * 86400000, 'fresh ' + p.id);
    if (p.phone) assert.match(p.phone, /^[6-9]\d{9}$/);
    assert.ok(!/ambulance/i.test(p.svc + ' ' + p.name));
  });
  assert.match(m.rwLocalPinUrl(list[0]), /^https:\/\/www\.google\.com\/maps\/search\/\?api=1&query=[\d.]+,[\d.]+$/);
});
