(function(){
'use strict';
var CFG=window.RW_PARTNER_CONFIG||{}, Core=window.RWPartnerCore, PILOT=window.RW_MILAN_PILOT;
var $=function(id){return document.getElementById(id)}, esc=Core.esc, money=Core.money;
var db=null,auth=null,unsubs=[];
var PROD_HOST=/^(www\.)?roamwise\.co\.in$/i.test(location.hostname);var LAB=(qs('lab')==='1'||qs('mode')==='demo'||!PROD_HOST);var defaultMode=qs('mode')||(!PROD_HOST?(localStorage.getItem('rw_partner_mode')||'demo'):'live');var S={mode:defaultMode,role:'customer',cat:'stay',ctx:initialTrip(),user:null,partner:null,isAdmin:false,staffRole:'',liveRooms:[],liveBookings:[],travel:null};
function icon(name){return '<svg aria-hidden="true"><use href="#i-'+name+'"></use></svg>'}
var ROLES={customer:{icon:icon('compass'),name:'Explore stays',desc:'Search and request a stay'},owner:{icon:icon('home'),name:'List a property',desc:'Apply to join the collective'},partner:{icon:icon('ops'),name:'Host operations',desc:'Run rooms, guests and earnings'},admin:{icon:icon('shield'),name:'Trust desk',desc:'Review partners and controls'}};
var DKEY='rw_partner_dropin_demo_v1';
function datePlus(n){var d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
function initialTrip(){var checkin=qs('checkin')||'',checkout=qs('checkout')||'',guests=Number(qs('guests'));var validDate=function(v){return /^\d{4}-\d{2}-\d{2}$/.test(v)&&!isNaN(Date.parse(v+'T12:00:00'))&&datePlusFor(v,0)===v};var validRange=validDate(checkin)&&validDate(checkout)&&checkin>=datePlus(0)&&checkout>checkin&&Core.nights(checkin,checkout)<=90;return{destination:(qs('destination')||'').slice(0,100),checkin:validRange?checkin:datePlus(7),checkout:validRange?checkout:datePlus(9),guests:Number.isInteger(guests)&&guests>=1&&guests<=12?guests:2}}
function datePlusFor(v,n){var d=new Date(v+'T12:00:00');d.setDate(d.getDate()+n);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function now(){return new Date().toISOString()}
function uid(p){return p+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,6)}
function qs(k){return new URLSearchParams(location.search).get(k)}
function closeModal(){$('modal').classList.remove('open')} window.RWClose=closeModal;
$('modal').onclick=function(e){if(e.target===$('modal'))closeModal()};
function seed(){return {applications:[{id:'app_demo_1',ownerName:'Aditi Rawat',email:'aditi@example.com',phone:'+91 98765 43210',name:'Kumaon Orchard House',zone:'Almora',area:'Kasardevi',type:'Family homestay',rooms:3,startPrice:2800,hook:'Family-run orchard stay above Almora.',status:'pending',createdAt:now()}],properties:[{id:'demo_binsar',partnerUid:'demo_partner_1',name:'Binsar Ridge Homestay',zone:'Almora',area:'Binsar Road',hook:'Quiet ridge stay with Himalayan views.',verified:'signed',status:'active',commissionPct:7,rating:4.9,reviews:83,rooms:[{id:'room_a',room:'Valley room',price:3200,maxGuests:2,inc:['Breakfast','Wi-Fi'],cancel:'Free cancellation up to 48h before',open:true},{id:'room_b',room:'Family room',price:4600,maxGuests:4,inc:['Breakfast','Parking'],cancel:'Free cancellation up to 72h before',open:true}]},{id:'demo_manali',partnerUid:'demo_partner_2',name:'Cedar House Manali',zone:'Manali',area:'Naggar Road',hook:'Small cedar-and-stone mountain home.',verified:'signed',status:'active',commissionPct:7,rating:4.8,reviews:51,rooms:[{id:'room_c',room:'Cedar room',price:3500,maxGuests:2,inc:['Breakfast'],open:true}]}],bookings:[],travel:{version:1,externalGapThreshold:4,stayCommissionPct:7,providers:{travelpayouts:{enabled:true,stay:'https://www.booking.com/searchresults.html?ss={destination}&checkin={checkin}&checkout={checkout}&group_adults={guests}',flight:'https://www.aviasales.com/search?destination={destination}',car:'https://www.discovercars.com/en/search?location={destination}',experience:'https://www.viator.com/searchResults/all?text={destination}'},expedia:{enabled:true,stay:'https://www.expedia.com/Hotel-Search?destination={destination}&startDate={checkin}&endDate={checkout}'},trawex:{enabled:false,stay:'',flight:'',car:'',experience:''},bookingxml:{enabled:false,stay:'',flight:'',car:'',experience:''}}}}}
function demo(){try{return JSON.parse(localStorage.getItem(DKEY))||seed()}catch(e){return seed()}}
function saveDemo(x){localStorage.setItem(DKEY,JSON.stringify(x))}
function resetDemo(){if(confirm('Reset the complete test workspace?')){localStorage.removeItem(DKEY);render()}}
function clearSubs(){unsubs.forEach(function(f){try{f()}catch(e){}});unsubs=[]}
function initFirebase(){try{if(!firebase.apps.length)firebase.initializeApp(CFG.firebase);db=firebase.firestore();auth=firebase.auth();auth.onAuthStateChanged(function(u){S.user=u||null;loadIdentity().finally(render)})}catch(e){db=null;auth=null}}
async function loadIdentity(){S.partner=null;S.isAdmin=false;S.staffRole='';if(!db||!S.user)return;try{var a=await db.collection('admins').doc(S.user.uid).get();S.isAdmin=a.exists}catch(e){}try{var st=await db.collection('staff').doc(S.user.uid).get();if(st.exists)S.staffRole=(st.data()||{}).role||''}catch(e){}try{var p=await db.collection('partners').doc(S.user.uid).get();if(p.exists){S.partner=p.data()||{};S.partner._id=p.id}}catch(e){}}
function defaultTravel(){return {externalGapThreshold:Number(CFG.commercial&&CFG.commercial.externalGapThreshold||4),stayCommissionPct:Number(CFG.commercial&&CFG.commercial.stayCommissionPct||7),providers:{travelpayouts:{enabled:true,stay:CFG.publicTravel.bookingStay,flight:CFG.publicTravel.flight,car:CFG.publicTravel.car,experience:CFG.publicTravel.experience},expedia:{enabled:true,stay:CFG.publicTravel.expediaStay},trawex:{enabled:false,stay:'',flight:'',car:'',experience:''},bookingxml:{enabled:false,stay:'',flight:'',car:'',experience:''}}}}
async function loadTravel(){if(S.mode==='demo'){S.travel=demo().travel||defaultTravel();return S.travel}S.travel=defaultTravel();if(db)try{var d=await db.collection('config').doc('partnerMarketplace').get();if(d.exists)S.travel=merge(S.travel,d.data()||{})}catch(e){}return S.travel}
function merge(a,b){var out=JSON.parse(JSON.stringify(a||{}));Object.keys(b||{}).forEach(function(k){if(b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k]))out[k]=merge(out[k]||{},b[k]);else out[k]=b[k]});return out}
function setRole(r){clearSubs();S.role=r;render()}
function setMode(m){clearSubs();S.mode=m;localStorage.setItem('rw_partner_mode',m);S.role='customer';render()}
function shell(){var role=ROLES[S.role];$('eyebrow').textContent=S.mode==='demo'?'Safe test workspace':'RoamWise Partner';$('heroTitle').innerHTML=S.role==='customer'?'Plan it. <em>Book it simply.</em>':S.role==='owner'?'Bring your place to <em>RoamWise.</em>':S.role==='partner'?'Your property, <em>under control.</em>':'Keep RoamWise <em>trusted.</em>';$('heroText').textContent=S.role==='customer'?'Our verified stays are shown first. If we need more choice, RoamWise widens the search for you.':S.role==='owner'?'Tell us about your property. We review each place before it receives a RoamWise badge.':S.role==='partner'?'Manage your rooms, prices and booking requests from one simple place.':'Review new properties, bookings and the public travel choices RoamWise can show.';$('modebar').style.display=LAB?'flex':'none';$('modebar').innerHTML=LAB?'<span class="label">Workspace:</span><button class="modechip '+(S.mode==='demo'?'on':'')+'" data-mode="demo">Test everything</button><button class="modechip '+(S.mode==='live'?'on':'')+'" data-mode="live">Use live accounts</button>'+(S.mode==='demo'?'<button class="modechip" id="resetDemo">Reset test</button>':''):'';document.querySelectorAll('[data-mode]').forEach(function(b){b.onclick=function(){setMode(b.dataset.mode)}});if($('resetDemo'))$('resetDemo').onclick=resetDemo;$('rolegrid').innerHTML=Object.keys(ROLES).map(function(k){var r=ROLES[k];return '<button class="role '+(S.role===k?'on':'')+'" data-role="'+k+'"><span class="ic">'+r.icon+'</span><b>'+r.name+'</b><small>'+r.desc+'</small></button>'}).join('');document.querySelectorAll('[data-role]').forEach(function(b){b.onclick=function(){setRole(b.dataset.role)}});$('signOutBtn').style.display=S.mode==='live'&&S.user?'block':'none';$('signOutBtn').onclick=function(){if(auth)auth.signOut()};$('homeBtn').onclick=function(){setRole('customer')};$('modeBtn').style.display=LAB?'block':'none';$('modeBtn').textContent=S.mode==='demo'?'Test mode':'Live mode';$('modeBtn').onclick=function(){setMode(S.mode==='demo'?'live':'demo')}}
async function render(){shell();await loadTravel();if(S.mode==='demo')renderDemo();else renderLive()}
function renderDemo(){if(S.role==='customer')demoCustomer();if(S.role==='owner')demoOwner();if(S.role==='partner')demoPartner();if(S.role==='admin')demoAdmin()}
function demoCustomer(){customerSearchUI(function(){renderSearchResults([],true);if(S.cat!=='stay')renderCustomerTripsDemo()})}
function customerSearchUI(onSearch){$('view').innerHTML='<div class="search"><div class="tabs"><button class="tab '+(S.cat==='stay'?'on':'')+'" data-cat="stay">'+icon('home')+'Stays</button><button class="tab '+(S.cat==='flight'?'on':'')+'" data-cat="flight">'+icon('flight')+'Flights</button><button class="tab '+(S.cat==='car'?'on':'')+'" data-cat="car">'+icon('car')+'Cars</button><button class="tab '+(S.cat==='experience'?'on':'')+'" data-cat="experience">'+icon('spark')+'Things to do</button></div><div class="searchgrid"><div class="field dest"><label>Where</label><input id="dest" value="'+esc(S.ctx.destination)+'" placeholder="Almora, Manali, Bali…"></div><div class="field"><label>From</label><input id="checkin" type="date" value="'+esc(S.ctx.checkin)+'"></div><div class="field"><label>To</label><input id="checkout" type="date" value="'+esc(S.ctx.checkout)+'"></div><div class="field"><label>Guests</label><input id="guests" type="number" min="1" max="12" value="'+S.ctx.guests+'"></div><div class="go"><label style="display:block;height:18px"></label><button class="btn" id="searchBtn">'+(S.cat==='stay'?'Search stays':'Update')+'</button></div></div></div><div id="results" class="results"></div>';document.querySelectorAll('[data-cat]').forEach(function(b){b.onclick=function(){S.cat=b.dataset.cat;customerSearchUI(onSearch);onSearch()}});$('searchBtn').onclick=function(){S.ctx.destination=$('dest').value.trim();S.ctx.checkin=$('checkin').value;S.ctx.checkout=$('checkout').value;S.ctx.guests=Math.max(1,Number($('guests').value||1));onSearch();var r=$('results');if(r&&r.scrollIntoView)r.scrollIntoView({behavior:'smooth',block:'start'})};onSearch()}
function renderSearchResults(direct,isDemo){var h=$('results');if(!h)return;if(window.RWStaysHub){window.RWStaysHub.render(h,S.ctx,S.cat);return}renderMilanWhatsAppCard()}
function milanWhatsAppMessage(){return 'Hello Milan Heights, I found your stay through RoamWise. I am interested in staying in Almora. Check-in: '+S.ctx.checkin+'. Check-out: '+S.ctx.checkout+'. Guests: '+S.ctx.guests+'. Please share available room options, the final total including all applicable taxes, payment method, and booking terms. Please note this enquiry came through RoamWise.'}
function milanWhatsAppUrl(){return 'https://wa.me/917302315845?text='+encodeURIComponent(milanWhatsAppMessage())}
function trackMilanWhatsAppTap(){try{if(typeof window.track==='function'){window.track('kasar_milan_whatsapp_open');return}if(firebase&&firebase.apps&&firebase.apps.length){var day=new Date().toISOString().slice(0,10),inc={kasar_milan_whatsapp_open:firebase.firestore.FieldValue.increment(1)};firebase.firestore().collection('stats').doc(day).set(inc,{merge:true}).catch(function(){})}}catch(e){}}
function renderMilanWhatsAppCard(){var h=$('results');if(h&&window.RWStaysHub)window.RWStaysHub.render(h,S.ctx,'stay')}
function renderCustomerTripsDemo(){var D=demo(),mine=D.bookings||[],wrap=document.createElement('div');wrap.className='card';wrap.style.marginTop='14px';wrap.innerHTML='<h2>My trips</h2><div class="muted">Booking requests made in this test workspace.</div><div class="list">'+(mine.length?mine.map(customerTripRow).join(''):'<div class="empty">No booking requests yet.</div>')+'</div>';$('results').appendChild(wrap)}
function customerTripRow(b){return '<div class="row"><div><strong>'+esc(b.property||'Stay')+'</strong><small>'+esc(b.checkIn||'')+' → '+esc(b.checkOut||'')+' · '+money(b.amount||0)+'</small><span class="pill '+(b.status==='confirmed'||b.status==='completed'?'green':b.status==='declined'?'red':'gold')+'">'+esc(b.status||'requested')+'</span></div><div></div></div>'}
async function renderCustomerTripsLive(){if(!S.user)return;try{var q=await db.collection('roomBookings').where('guestUid','==',S.user.uid).limit(50).get(),arr=[];q.forEach(function(d){var x=d.data()||{};x._id=d.id;arr.push(x)});var wrap=document.createElement('div');wrap.className='card';wrap.style.marginTop='14px';wrap.innerHTML='<h2>My trips</h2><div class="list">'+(arr.length?arr.map(customerTripRow).join(''):'<div class="empty">No booking requests yet.</div>')+'</div>';$('results').appendChild(wrap)}catch(e){}}
function providerCards(cat){var t=S.travel||defaultTravel(),p=t.providers||{},arr=[];function add(key,label,iconName,url){if(p[key]&&p[key].enabled&&url)arr.push({key:key,label:label,icon:icon(iconName),url:url})}if(cat==='stay'){add('travelpayouts','Hotels & stays','home',p.travelpayouts&&p.travelpayouts.stay);add('expedia','More hotels','home',p.expedia&&p.expedia.stay);add('trawex','More local choices','compass',p.trawex&&p.trawex.stay);add('bookingxml','More places','mountain',p.bookingxml&&p.bookingxml.stay)}if(cat==='flight'){add('travelpayouts','Compare flights','flight',p.travelpayouts&&p.travelpayouts.flight);add('expedia','More flights','flight',p.expedia&&p.expedia.flight);add('trawex','More flight choices','compass',p.trawex&&p.trawex.flight);add('bookingxml','Additional flights','mountain',p.bookingxml&&p.bookingxml.flight)}if(cat==='car'){add('travelpayouts','Find a car','car',p.travelpayouts&&p.travelpayouts.car);add('expedia','More cars','car',p.expedia&&p.expedia.car);add('trawex','More car choices','compass',p.trawex&&p.trawex.car);add('bookingxml','Additional cars','mountain',p.bookingxml&&p.bookingxml.car)}if(cat==='experience'){add('travelpayouts','Find things to do','spark',p.travelpayouts&&p.travelpayouts.experience);add('trawex','More experiences','spark',p.trawex&&p.trawex.experience);add('bookingxml','Additional experiences','compass',p.bookingxml&&p.bookingxml.experience)}return arr}
function externalCategory(cat){var a=providerCards(cat);if(!a.length)return '<div class="empty">More choices will appear here when RoamWise connects them.</div>';return '<div class="list">'+a.map(function(x){return '<div class="row"><div><strong>'+x.icon+' '+esc(x.label)+'</strong><small>See live choices for '+esc(S.ctx.destination)+'</small></div><button class="btn secondary" data-external="'+esc(x.key)+'" data-url="'+esc(x.url)+'">See options</button></div>'}).join('')+'</div>'}
function bindExternal(){document.querySelectorAll('[data-external]').forEach(function(b){b.onclick=function(){var url=Core.fillTemplate(b.dataset.url,S.ctx);try{var hist=JSON.parse(localStorage.getItem('rw_partner_clicks')||'[]');hist.unshift({provider:b.dataset.external,category:S.cat,destination:S.ctx.destination,at:now()});localStorage.setItem('rw_partner_clicks',JSON.stringify(hist.slice(0,100)))}catch(e){}if(url)window.open(url,'_blank','noopener,noreferrer')}})}
function openDirectBooking(x,isDemo){var ns=Core.nights(S.ctx.checkin,S.ctx.checkout),amount=Number(x.price||0)*ns,pct=Number(x.commissionPct||S.travel.stayCommissionPct||7);$('modalbox').innerHTML='<div class="modalhead"><div><h2>'+esc(x.name)+'</h2><div class="muted">'+esc(x.room)+' · '+ns+' night'+(ns>1?'s':'')+'</div></div><button class="x" onclick="RWClose()">×</button></div><div class="stats"><div class="stat"><b>'+money(x.price)+'</b><span>Per night</span></div><div class="stat"><b>'+ns+'</b><span>Nights</span></div><div class="stat"><b>'+S.ctx.guests+'</b><span>Guests</span></div><div class="stat"><b>'+money(amount)+'</b><span>Total</span></div></div><div class="fields"><div class="field"><label>Your name</label><input id="bgname" placeholder="Traveller name"></div><div class="field"><label>Email</label><input id="bgemail" type="email" value="'+esc(S.user&&S.user.email||'')+'" placeholder="you@example.com"></div><div class="field"><label>Phone</label><input id="bgphone" placeholder="+91…"></div><div class="field"><label>Note</label><input id="bgnote" placeholder="Arrival time or a question"></div></div><div class="notice"><b>No payment is taken here.</b> The property receives your request and confirms availability.</div><div class="actions"><button class="btn" id="sendBooking">Send booking request</button><button class="btn secondary" onclick="RWClose()">Cancel</button></div>'; $('modal').classList.add('open');$('sendBooking').onclick=async function(){var name=$('bgname').value.trim(),email=$('bgemail').value.trim();if(!name||!email){alert('Add your name and email.');return}var rec={ref:Core.bookingRef(),status:'requested',partnerUid:x.partnerUid,guestUid:S.user&&S.user.uid||'demo_guest',guestName:name,guestEmail:email,guestPhone:$('bgphone').value.trim(),note:$('bgnote').value.trim(),property:x.name,room:x.room,roomId:x.roomId||'',zone:x.zone||'',area:x.area||'',checkIn:S.ctx.checkin,checkOut:S.ctx.checkout,guests:S.ctx.guests,nights:ns,roomPrice:Number(x.price||0),amount:amount,commissionPctSnapshot:pct,at:now(),createdAt:now()};if(isDemo){var D=demo();rec._id=uid('booking');D.bookings.unshift(rec);saveDemo(D);bookingSuccess(rec.ref);return}if(!S.user){authPrompt(function(){closeModal();openDirectBooking(x,false)});return}rec.guestUid=S.user.uid;try{var doc=await db.collection('roomBookings').add(rec);rec._id=doc.id;bookingSuccess(rec.ref)}catch(e){showError('Could not send this request',friendly(e))}}}
function bookingSuccess(ref){$('modalbox').innerHTML='<div class="success"><div class="big">✓</div><h2>Request sent</h2><p class="muted">The property can now confirm or decline your request.</p><div class="code">'+esc(ref)+'</div><div><button class="btn" onclick="RWClose()">Done</button></div></div>'}
function authPrompt(after){$('modalbox').innerHTML='<div class="modalhead"><div><h2>Sign in to continue</h2><div class="muted">Use your RoamWise account or create one here.</div></div><button class="x" onclick="RWClose()">×</button></div>'+authFields('trav')+'<div class="actions"><button class="btn" id="travLogin">Sign in</button><button class="btn secondary" id="travCreate">Create account</button></div><div id="travMsg"></div>';$('modal').classList.add('open');$('travLogin').onclick=function(){doLogin('trav',after)};$('travCreate').onclick=function(){doCreate('trav',after)}}
function authFields(p){return '<div class="fields" style="margin-top:12px"><div class="field full"><label>Email</label><input id="'+p+'Email" type="email" autocomplete="email"></div><div class="field full"><label>Password</label><input id="'+p+'Pass" type="password" autocomplete="current-password"></div></div>'}
async function doLogin(p,after){if(!auth)return;var e=$(p+'Email').value.trim(),pw=$(p+'Pass').value;try{await auth.signInWithEmailAndPassword(e,pw);if(after)after()}catch(x){msg(p+'Msg',friendly(x),true)}}
async function doCreate(p,after){if(!auth)return;var e=$(p+'Email').value.trim(),pw=$(p+'Pass').value;if(pw.length<6){msg(p+'Msg','Password needs at least 6 characters.',true);return}try{await auth.createUserWithEmailAndPassword(e,pw);if(after)after()}catch(x){msg(p+'Msg',friendly(x),true)}}
function msg(id,text,bad){var e=$(id);if(e)e.innerHTML='<div class="notice '+(bad?'bad':'good')+'">'+esc(text)+'</div>'}
function friendly(e){var code=String(e&&e.code||''),s=(e&&e.message)||String(e||'Something went wrong.');if(/email-already-in-use/.test(code))return 'An account already uses this email. Sign in instead, then open Settings → Sign-in & security to add another sign-in option.';if(/account-exists-with-different-credential/.test(code))return 'This email already has a RoamWise sign-in option. Use that option first, then add another in Settings so your trips stay on one account.';if(/permission/i.test(s))return 'This account cannot do that action yet.';if(/credential/i.test(s))return 'Email or password did not match.';return 'Something went wrong. Please try again.'}
function showError(title,text){$('modalbox').innerHTML='<div class="modalhead"><div><h2>'+esc(title)+'</h2></div><button class="x" onclick="RWClose()">×</button></div><div class="notice bad">'+esc(text)+'</div>'; $('modal').classList.add('open')}
function ownerStartCard(title,copy){return '<section class="card rw-owner-start"><span class="eyebrow">ONE PROPERTY · ONE APPLICATION · ONE MOU</span><h2>'+esc(title)+'</h2><p class="muted">'+esc(copy)+'</p><div class="rw-owner-start-steps"><span><b>1</b> Property basics</span><span><b>2</b> Accept V4 MOU</span><span><b>3</b> RoamWise review</span></div><div class="actions"><a class="btn" href="/partner/join/">Start the 3-minute application →</a><a class="btn secondary" href="/creators/match.html?role=property">Match with verified creators</a></div><p class="rw-market-fine">Applying is free. Nothing goes live and no guest payment is taken until verification and booking-flow checks are complete.</p></section>'}
function demoOwner(){var D=demo();$('view').innerHTML='<div class="grid2">'+ownerStartCard('List your property once','Use the same short application as the live site; registration and MOU acceptance are not repeated inside this desk.')+'<aside class="card"><h2>Test applications</h2><div class="list">'+(D.applications.length?D.applications.slice().reverse().map(applicationRow).join(''):'<div class="empty">No test applications yet.</div>')+'</div></aside></div>'}
function applicationRow(a){return '<div class="row"><div><strong>'+esc(a.name)+'</strong><small>'+esc(a.zone)+' · '+esc(a.ownerName)+' · '+a.rooms+' room(s)</small><span class="pill '+(a.status==='approved'?'green':a.status==='rejected'?'red':'gold')+'">'+esc(a.status)+'</span></div><div></div></div>'}
function demoPartner(){var D=demo(),props=D.properties.filter(function(p){return p.status==='active'});if(!props.length){$('view').innerHTML='<div class="empty">No approved properties yet. Apply as a Property owner, then approve it as Admin / staff.</div>';return}var selected=localStorage.getItem('rw_demo_prop')||props[0].id,p=props.find(function(x){return x.id===selected})||props[0],books=D.bookings.filter(function(b){return b.partnerUid===p.partnerUid||b.propertyId===p.id});var totals=Core.partnerTotals(books,p.commissionPct||7,CFG.commercial.completedStatuses);$('view').innerHTML=partnerPortalHtml(p,books,totals,props,true);bindDemoPartner(p,D)}
function partnerPortalHtml(p,books,totals,props,isDemo){return '<div class="stats"><div class="stat"><b>'+books.length+'</b><span>Bookings</span></div><div class="stat"><b>'+books.filter(function(b){return b.status==='requested'}).length+'</b><span>Waiting</span></div><div class="stat"><b>'+money(totals.partner)+'</b><span>Earned</span></div><div class="stat"><b>'+money(totals.commission)+'</b><span>RoamWise</span></div></div><div class="grid2"><section class="card"><div style="display:flex;gap:10px;justify-content:space-between;align-items:start"><div><h2>'+esc(p.name||'Your property')+'</h2><div class="muted">'+esc([p.area,p.zone].filter(Boolean).join(' · '))+'</div></div>'+(props&&props.length>1?'<select id="propSelect" class="navbtn">'+props.map(function(x){return '<option value="'+esc(x.id||x._id)+'" '+((x.id||x._id)===(p.id||p._id)?'selected':'')+'>'+esc(x.name)+'</option>'}).join('')+'</select>':'')+'</div><div class="divider"></div><h3>Booking requests</h3><div class="list">'+(books.length?books.slice().sort(function(a,b){return String(b.at||'').localeCompare(String(a.at||''))}).map(partnerBookingRow).join(''):'<div class="empty">No booking requests yet.</div>')+'</div></section><aside class="card"><h2>Rooms & prices</h2><div class="muted">Prices stay under your control.</div><div class="list" id="roomList">'+((p.rooms||[]).length?(p.rooms||[]).map(function(r){return '<div class="row"><div><strong>'+esc(r.room||'Room')+'</strong><small>'+money(r.price)+' · sleeps '+(r.maxGuests||2)+'</small></div><button class="btn secondary" data-editroom="'+esc(r.id||r._id||'')+'">Edit</button></div>'}).join(''):'<div class="empty">No rooms yet.</div>')+'</div><div class="actions"><button class="btn" id="addRoom">Add room</button><button class="btn secondary" id="editProp">Property details</button></div></aside></div>'}
function partnerBookingRow(b){return '<div class="row"><div><strong>'+esc(b.guestName||'Guest')+' · '+money(b.amount||0)+'</strong><small>'+esc(b.room||'')+' · '+esc(b.checkIn||'')+' → '+esc(b.checkOut||'')+' · '+(b.guests||1)+' guest(s)</small><span class="pill '+(b.status==='confirmed'||b.status==='completed'?'green':b.status==='declined'?'red':'gold')+'">'+esc(b.status||'requested')+'</span></div><div>'+(b.status==='requested'?'<div class="actions"><button class="btn green" data-confirm="'+esc(b._id||b.id)+'">Confirm</button><button class="btn red" data-decline="'+esc(b._id||b.id)+'">Decline</button></div>':'')+'</div></div>'}
function bindDemoPartner(p,D){if($('propSelect'))$('propSelect').onchange=function(){localStorage.setItem('rw_demo_prop',this.value);demoPartner()};document.querySelectorAll('[data-confirm]').forEach(function(b){b.onclick=function(){var x=D.bookings.find(function(z){return (z._id||z.id)===b.dataset.confirm});if(x){x.status='confirmed';x.confirmedAt=now();saveDemo(D);demoPartner()}}});document.querySelectorAll('[data-decline]').forEach(function(b){b.onclick=function(){var x=D.bookings.find(function(z){return (z._id||z.id)===b.dataset.decline});if(x){x.status='declined';x.confirmedAt=now();saveDemo(D);demoPartner()}}});document.querySelectorAll('[data-editroom]').forEach(function(b){b.onclick=function(){editRoomDemo(p,b.dataset.editroom)}});$('addRoom').onclick=function(){editRoomDemo(p,'')};$('editProp').onclick=function(){editPropertyDemo(p)}}
function editRoomDemo(p,rid){var D=demo(),pp=D.properties.find(function(x){return x.id===p.id}),r=(pp.rooms||[]).find(function(x){return x.id===rid})||{id:uid('room'),room:'',price:3000,maxGuests:2,inc:[],cancel:'',open:true};roomModal(r,function(out){if(!rid)pp.rooms.push(out);else Object.assign(r,out);saveDemo(D);closeModal();demoPartner()})}
function editPropertyDemo(p){var D=demo(),pp=D.properties.find(function(x){return x.id===p.id});propertyModal(pp,function(out){Object.assign(pp,out);saveDemo(D);closeModal();demoPartner()})}
function roomModal(r,save){$('modalbox').innerHTML='<div class="modalhead"><div><h2>'+(r.room?'Edit room':'Add room')+'</h2></div><button class="x" onclick="RWClose()">×</button></div><div class="fields"><div class="field"><label>Room name</label><input id="rname" value="'+esc(r.room||'')+'"></div><div class="field"><label>Price / night</label><input id="rprice" type="number" value="'+Number(r.price||0)+'"></div><div class="field"><label>Sleeps</label><input id="rmax" type="number" value="'+Number(r.maxGuests||2)+'"></div><div class="field"><label>Includes</label><input id="rinc" value="'+esc((r.inc||[]).join(', '))+'" placeholder="Breakfast, Wi-Fi"></div><div class="field full"><label>Cancellation</label><input id="rcancel" value="'+esc(r.cancel||'')+'"></div></div><div class="actions"><button class="btn" id="roomSave">Save room</button></div>';$('modal').classList.add('open');$('roomSave').onclick=function(){var out={id:r.id||uid('room'),room:$('rname').value.trim(),price:Math.max(1,Number($('rprice').value||0)),maxGuests:Math.max(1,Number($('rmax').value||1)),inc:$('rinc').value.split(',').map(function(x){return x.trim()}).filter(Boolean),cancel:$('rcancel').value.trim(),open:true};if(!out.room){alert('Add a room name.');return}save(out)}}
function propertyModal(p,save){$('modalbox').innerHTML='<div class="modalhead"><div><h2>Property details</h2></div><button class="x" onclick="RWClose()">×</button></div><div class="fields"><div class="field full"><label>Property name</label><input id="pname" value="'+esc(p.name||'')+'"></div><div class="field"><label>City / destination</label><input id="pzone" value="'+esc(p.zone||'')+'"></div><div class="field"><label>Area</label><input id="parea" value="'+esc(p.area||'')+'"></div><div class="field full"><label>Short description</label><textarea id="phook">'+esc(p.hook||'')+'</textarea></div></div><div class="actions"><button class="btn" id="propSave">Save changes</button></div>';$('modal').classList.add('open');$('propSave').onclick=function(){save({name:$('pname').value.trim(),zone:$('pzone').value.trim(),area:$('parea').value.trim(),hook:$('phook').value.trim(),updatedAt:now()})}}
function demoAdmin(){var D=demo(),pending=D.applications.filter(function(a){return a.status==='pending'}),active=D.properties.filter(function(p){return p.status==='active'}),waiting=D.bookings.filter(function(b){return b.status==='requested'}),completed=D.bookings.filter(function(b){return Core.isCompleted(b.status,CFG.commercial.completedStatuses)});$('view').innerHTML='<div class="stats"><div class="stat"><b>'+pending.length+'</b><span>Waiting review</span></div><div class="stat"><b>'+active.length+'</b><span>Partners</span></div><div class="stat"><b>'+waiting.length+'</b><span>Booking requests</span></div><div class="stat"><b>'+completed.length+'</b><span>Completed stays</span></div></div><div class="grid2"><section class="card"><h2>Property review</h2><div class="muted">Approve a property and it immediately becomes a RoamWise Pick in this test.</div><div class="list">'+(D.applications.length?D.applications.slice().reverse().map(adminApplicationRow).join(''):'<div class="empty">No applications.</div>')+'</div><h2 style="margin-top:18px">Bookings</h2><div class="list">'+(D.bookings.length?D.bookings.map(adminBookingRow).join(''):'<div class="empty">No bookings yet.</div>')+'</div></section><aside class="card"><h2>Travel choices</h2><div class="muted">These settings are private to the team. Travellers only see simple booking choices.</div>'+travelSettingsHtml(D.travel)+'<div class="notice"><b>Keep secret API tokens out of this page.</b> Use public partner links here. APIs that need a secret can be connected later without changing the traveller page.</div></aside></div>';bindDemoAdmin(D)}
function adminApplicationRow(a){return '<div class="row"><div><strong>'+esc(a.name)+'</strong><small>'+esc(a.ownerName)+' · '+esc(a.zone)+' · '+a.rooms+' room(s)</small><span class="pill '+(a.status==='approved'?'green':a.status==='rejected'?'red':'gold')+'">'+esc(a.status)+'</span></div><div>'+(a.status==='pending'?'<div class="actions"><button class="btn green" data-approve="'+a.id+'">Approve</button><button class="btn red" data-reject="'+a.id+'">Reject</button></div>':'')+'</div></div>'}
function adminBookingRow(b){return '<div class="row"><div><strong>'+esc(b.guestName||'Guest')+' · '+esc(b.property||'')+'</strong><small>'+esc(b.checkIn||'')+' → '+esc(b.checkOut||'')+' · '+money(b.amount||0)+'</small><span class="pill '+(b.status==='confirmed'||b.status==='completed'?'green':b.status==='declined'?'red':'gold')+'">'+esc(b.status)+'</span></div><div>'+(b.status==='confirmed'?'<button class="btn green" data-complete="'+esc(b._id||b.id)+'">Mark completed</button>':'')+'</div></div>'}
function travelSettingsHtml(t){t=t||defaultTravel();var p=t.providers||{};function box(k,label,fields){var c=p[k]||{};return '<div class="setup"><div style="display:flex;justify-content:space-between;gap:8px"><b>'+label+'</b><label class="tiny"><input type="checkbox" data-penabled="'+k+'" '+(c.enabled?'checked':'')+'> On</label></div>'+fields.map(function(f){return '<div class="field" style="margin-top:8px"><label>'+f[0]+'</label><input data-pfield="'+k+'|'+f[1]+'" value="'+esc(c[f[1]]||'')+'" placeholder="Paste public partner link"></div>'}).join('')+'</div>'}return '<div class="field" style="margin-top:10px"><label>Show more choices when fewer than</label><input id="gapThreshold" type="number" min="0" max="20" value="'+Number(t.externalGapThreshold||4)+'"></div>'+box('travelpayouts','Travelpayouts',[['Stays link','stay'],['Flights link','flight'],['Cars link','car'],['Things to do link','experience']])+box('expedia','Expedia',[['Stays link','stay'],['Flights link','flight'],['Cars link','car']])+box('trawex','Contracted travel feed',[['Stays link','stay'],['Flights link','flight'],['Cars link','car'],['Things to do link','experience']])+box('bookingxml','Additional contracted feed',[['Stays link','stay'],['Flights link','flight'],['Cars link','car'],['Things to do link','experience']])+'<div class="actions"><button class="btn" id="saveTravel">Save choices</button></div><div id="travelMsg"></div>'}
function readTravelForm(base){var out=JSON.parse(JSON.stringify(base||defaultTravel()));out.externalGapThreshold=Math.max(0,Number($('gapThreshold').value||4));document.querySelectorAll('[data-penabled]').forEach(function(x){var k=x.dataset.penabled;out.providers[k]=out.providers[k]||{};out.providers[k].enabled=x.checked});document.querySelectorAll('[data-pfield]').forEach(function(x){var parts=x.dataset.pfield.split('|');out.providers[parts[0]]=out.providers[parts[0]]||{};out.providers[parts[0]][parts[1]]=x.value.trim()});return out}
function bindDemoAdmin(D){document.querySelectorAll('[data-approve]').forEach(function(b){b.onclick=function(){var a=D.applications.find(function(x){return x.id===b.dataset.approve});if(!a)return;a.status='approved';a.reviewedAt=now();D.properties.push({id:uid('prop'),partnerUid:'demo_'+a.id,name:a.name,zone:a.zone,area:a.area,hook:a.hook,verified:'signed',status:'active',commissionPct:7,rating:4.8,reviews:0,rooms:[{id:uid('room'),room:'Standard room',price:a.startPrice||3000,maxGuests:2,inc:[],open:true}]});saveDemo(D);demoAdmin()}});document.querySelectorAll('[data-reject]').forEach(function(b){b.onclick=function(){var a=D.applications.find(function(x){return x.id===b.dataset.reject});if(a){a.status='rejected';a.reviewedAt=now();saveDemo(D);demoAdmin()}}});document.querySelectorAll('[data-complete]').forEach(function(b){b.onclick=function(){var x=D.bookings.find(function(z){return (z._id||z.id)===b.dataset.complete});if(x){x.status='completed';x.completedAt=now();saveDemo(D);demoAdmin()}}});$('saveTravel').onclick=function(){D.travel=readTravelForm(D.travel);saveDemo(D);msg('travelMsg','Saved for this test workspace.')}}
async function renderLive(){if(S.role==='customer'){liveCustomer();return}if(!db||!auth){$('view').innerHTML='<div class="notice bad"><b>Could not connect.</b> Check internet access and reload.</div>';return}if(S.role==='owner')liveOwner();if(S.role==='partner')livePartner();if(S.role==='admin')liveAdmin()}
function liveCustomer(){customerSearchUI(async function(){renderSearchResults([],false)})}
function liveOwner(){if(!S.user){$('view').innerHTML=ownerStartCard('List your property once','The application includes sign-in, the required details and one acceptance of the current V4 MOU.');return}if(S.partner){if(S.partner.status==='active'){$('view').innerHTML='<section class="card rw-owner-start"><span class="eyebrow">LIVE PROPERTY</span><h2>'+esc(S.partner.name||'Your property')+' is live</h2><p class="muted">Registration is complete. Use Host operations for rooms, booking requests and payments.</p><div class="actions"><button class="btn" id="openHostDesk">Open Host operations →</button><a class="btn secondary" href="/creators/match.html?role=property">Find verified creators</a></div></section>';$('openHostDesk').onclick=function(){setRole('partner')};return}$('view').innerHTML='<section class="card rw-owner-start"><span class="eyebrow">APPLICATION RECEIVED</span><h2>'+esc(S.partner.name||'Your property')+'</h2><p class="muted">Your single application and V4 MOU acceptance are on record. RoamWise is checking contact, public rates, location and property readiness.</p><div class="actions"><a class="btn secondary" href="mailto:founder@roamwise.co.in?subject='+encodeURIComponent('Update property application: '+(S.partner.name||''))+'">Send a correction</a><a class="btn secondary" href="/partner/mou/" target="_blank" rel="noopener">Review the MOU</a></div></section>';return}$('view').innerHTML=ownerStartCard('Ready when you are','You are signed in as '+(S.user.email||'your RoamWise account')+'. Continue in the one canonical application.');}
function setVal(id,v){if($(id)&&v!=null)$(id).value=v}
function livePartner(){if(!S.user){liveLoginCard('Partner sign in','Sign in with the account used for your property application.','prt');return}if(!S.partner){$('view').innerHTML='<div class="notice"><b>No property is attached to this account yet.</b> Open “Property owner” and submit your place first.</div>';return}if(S.partner.status!=='active'){$('view').innerHTML='<div class="notice"><b>'+esc(S.partner.name||'Your property')+' is still being reviewed.</b> This dashboard opens automatically after approval.</div>';return}subscribePartnerLive()}
function liveLoginCard(title,sub,p){$('view').innerHTML='<div class="authshell card"><h2>'+esc(title)+'</h2><p class="muted">'+esc(sub)+'</p>'+authFields(p)+'<div class="actions"><button class="btn" id="'+p+'Login">Sign in</button><button class="btn secondary" id="'+p+'Reset">Forgot password</button></div><div id="'+p+'Msg"></div></div>';$(p+'Login').onclick=function(){doLogin(p)};$(p+'Reset').onclick=async function(){var e=$(p+'Email').value.trim();if(!e){msg(p+'Msg','Enter your email first.',true);return}try{await auth.sendPasswordResetEmail(e);msg(p+'Msg','Password reset link sent.')}catch(x){msg(p+'Msg',friendly(x),true)}}}
function subscribePartnerLive(){clearSubs();var roomsRef=db.collection('partners').doc(S.user.uid).collection('rooms'),booksRef=db.collection('roomBookings').where('partnerUid','==',S.user.uid).limit(100);unsubs.push(roomsRef.onSnapshot(function(q){S.liveRooms=[];q.forEach(function(d){var r=d.data()||{};r._id=d.id;S.liveRooms.push(r)});paintPartnerLive()},function(e){showPartnerLiveError(e)}));unsubs.push(booksRef.onSnapshot(function(q){S.liveBookings=[];q.forEach(function(d){var b=d.data()||{};b._id=d.id;S.liveBookings.push(b)});paintPartnerLive()},function(e){showPartnerLiveError(e)}));paintPartnerLive()}
function showPartnerLiveError(e){$('view').innerHTML='<div class="notice bad"><b>The partner workspace cannot read its live data.</b> '+esc(friendly(e))+'</div>'}
function paintPartnerLive(){var p=Object.assign({},S.partner,{rooms:S.liveRooms}),books=S.liveBookings,totals=Core.partnerTotals(books,Number(p.commissionPct||S.travel.stayCommissionPct||7),CFG.commercial.completedStatuses);$('view').innerHTML=partnerPortalHtml(p,books,totals,null,false);document.querySelectorAll('[data-confirm]').forEach(function(b){b.onclick=function(){liveBookingStatus(b.dataset.confirm,'confirmed')}});document.querySelectorAll('[data-decline]').forEach(function(b){b.onclick=function(){liveBookingStatus(b.dataset.decline,'declined')}});document.querySelectorAll('[data-editroom]').forEach(function(b){b.onclick=function(){editRoomLive(b.dataset.editroom)}});$('addRoom').onclick=function(){editRoomLive('')};$('editProp').onclick=editPropertyLive}
async function liveBookingStatus(id,status){try{await db.collection('roomBookings').doc(id).update({status:status,confirmedAt:now()})}catch(e){showError('Could not update booking',friendly(e))}}
function editRoomLive(rid){var r=S.liveRooms.find(function(x){return x._id===rid})||{room:'',price:3000,maxGuests:2,inc:[],cancel:''};roomModal(r,async function(out){var rec={room:out.room,price:out.price,maxGuests:out.maxGuests,inc:out.inc,cancel:out.cancel,property:S.partner.name||'',zone:S.partner.zone||'',area:S.partner.area||'',partnerUid:S.user.uid,updatedAt:now()};try{var ref=db.collection('partners').doc(S.user.uid).collection('rooms');if(rid)await ref.doc(rid).set(rec,{merge:true});else await ref.add(rec);closeModal()}catch(e){showError('Could not save room',friendly(e))}})}
function editPropertyLive(){propertyModal(S.partner,async function(out){try{await db.collection('partners').doc(S.user.uid).set(out,{merge:true});S.partner=Object.assign(S.partner,out);closeModal();paintPartnerLive()}catch(e){showError('Could not save property',friendly(e))}})}
function partnershipStaffDesk(){var root=$('view');if(!root||!db||S.isAdmin||S.staffRole!=='partnerships')return;root.innerHTML='<section class="card"><span class="eyebrow">PARTNERSHIPS REVIEW DESK</span><h2>Review properties for founder approval</h2><p class="muted">Record a recommendation only. Activation, suspension, payment settings and staff removal remain founder-admin actions.</p><div id="partnershipReviewList" class="list"><div class="empty">Loading applications…</div></div></section>';db.collection('partners').limit(200).get().then(function(s){var rows=[];s.forEach(function(d){var p=d.data()||{};p._id=d.id;rows.push(p)});$('partnershipReviewList').innerHTML=rows.length?rows.map(function(p){var rec=p.partnershipRecommendation||'';return'<article class="row"><div class="grow"><strong>'+esc(p.name||p.email||'Property')+'</strong><div class="meta">'+esc([p.area,p.zone,p.ownerName,p.email].filter(Boolean).join(' · '))+'<br>Status: '+esc(p.status||'pending')+' · MOU: '+esc((p.onboarding||{}).mouVersion||'not recorded')+'</div><select class="input" data-partner-recommend="'+esc(p._id)+'"><option value="">No recommendation</option><option value="ready" '+(rec==='ready'?'selected':'')+'>Recommend founder review</option><option value="correction" '+(rec==='correction'?'selected':'')+'>Needs correction</option><option value="hold" '+(rec==='hold'?'selected':'')+'>Hold for evidence</option></select></div></article>'}).join(''):'<div class="empty">No applications yet.</div>';$$('[data-partner-recommend]').forEach(function(s){s.onchange=function(){var choice=s.value,id=s.dataset.partnerRecommend;if(!choice)return;db.collection('partners').doc(id).set({partnershipRecommendation:choice,partnershipRecommendationNote:choice==='ready'?'Reviewed by partnerships staff':'Follow-up required',partnershipReviewedAt:new Date().toISOString(),partnershipReviewer:S.user.uid,updatedAt:new Date().toISOString()},{merge:true}).then(function(){toast('Recommendation saved for founder review.')}).catch(function(e){toast(e.message,true)})}})}).catch(function(e){toast('Could not load partner applications: '+e.message,true)})}
function liveAdmin(){if(!S.user){liveLoginCard('Team sign in','Founder and staff accounts use the same secure sign-in.','adm');return}if(S.isAdmin){loadAdminLive();return}if(S.staffRole){$('view').innerHTML='<div class="grid2"><section class="card"><h2>Staff access</h2><p class="muted">Signed in as '+esc(S.staffRole)+'. Your current RoamWise permissions keep property approval with the founder account.</p><div class="notice good"><b>Your staff account is working.</b> This protects partner commercial settings from accidental changes.</div></section><aside class="card"><h3>Need to review a property?</h3><p class="muted">Use the founder/admin account for live approvals. In Test mode you can simulate the full staff workflow.</p></aside></div>';return}$('view').innerHTML='<div class="notice bad"><b>This account is not a RoamWise admin or staff account.</b></div>'}
async function loadAdminLive(){var view=$('view');view.innerHTML='<div class="empty">Loading team workspace…</div>';try{var pq=await db.collection('partners').limit(100).get(),bq=await db.collection('roomBookings').limit(100).get(),partners=[],books=[];pq.forEach(function(d){var x=d.data()||{};x._id=d.id;partners.push(x)});bq.forEach(function(d){var x=d.data()||{};x._id=d.id;books.push(x)});paintAdminLive(partners,books)}catch(e){view.innerHTML='<div class="notice bad"><b>Founder account is connected, but partner data is not readable with the currently published rules.</b> '+esc(friendly(e))+'<br><br>The ZIP includes the matching optional rules block if your Firebase console still uses an older rules version.</div>'}}
function paintAdminLive(partners,books){adminCache=partners;var pending=partners.filter(function(p){return p.status!=='active'}),active=partners.filter(function(p){return p.status==='active'});$('view').innerHTML='<div class="stats"><div class="stat"><b>'+pending.length+'</b><span>Waiting review</span></div><div class="stat"><b>'+active.length+'</b><span>Partners</span></div><div class="stat"><b>'+books.filter(function(b){return b.status==='requested'}).length+'</b><span>Booking requests</span></div><div class="stat"><b>'+books.filter(function(b){return Core.isCompleted(b.status,CFG.commercial.completedStatuses)}).length+'</b><span>Completed stays</span></div></div><div class="grid2"><section class="card"><h2>Property review</h2><div class="list">'+(partners.length?partners.map(function(p){return '<div class="row"><div><strong>'+esc(p.name||p.email||'New property')+'</strong><small>'+esc([p.area,p.zone,p.email].filter(Boolean).join(' · '))+'</small><span class="pill '+(p.status==='active'?'green':'gold')+'">'+esc(p.status||'pending')+'</span></div><div><button class="btn" data-livedetail="'+p._id+'">Details</button> '+(p.status==='active'?'<button class="btn red" data-livesuspend="'+p._id+'">Suspend</button>':'<button class="btn green" data-liveapprove="'+p._id+'">Approve</button>')+'</div></div><div id="pd-'+p._id+'" hidden style="margin:-4px 0 10px;padding:14px;border:1px solid var(--line);border-radius:15px;background:rgba(255,255,255,.03)"></div>'}).join(''):'<div class="empty">No partner records yet.</div>')+'</div><h2 style="margin-top:18px">Bookings</h2><div class="list">'+(books.length?books.map(adminBookingRow).join(''):'<div class="empty">No bookings yet.</div>')+'</div></section><aside class="card"><h2>Travel choices</h2><div class="muted">Only public partner links belong here. Travellers never see this setup screen.</div>'+travelSettingsHtml(S.travel)+'<div class="notice"><b>Do not paste secret API keys here.</b> Static website files and public config can be inspected by visitors. Secret-token APIs need a private server connection later.</div></aside></div>';document.querySelectorAll('[data-livedetail]').forEach(function(b){b.onclick=function(){liveDetail(b.dataset.livedetail)}});document.querySelectorAll('[data-liveapprove]').forEach(function(b){b.onclick=function(){liveApprove(b.dataset.liveapprove)}});document.querySelectorAll('[data-livesuspend]').forEach(function(b){b.onclick=function(){liveSuspendPartner(b.dataset.livesuspend)}});document.querySelectorAll('[data-complete]').forEach(function(b){b.onclick=function(){liveComplete(b.dataset.complete)}});$('saveTravel').onclick=saveTravelLive}
async function liveApprove(id){try{var d=await db.collection('partners').doc(id).get(),p=d.exists?d.data()||{}:{},on=p.onboarding||{};if(!on.mouAcceptedAt||on.mouVersion!=='RW-PMOU-2026-09-27-V4')throw Error('Current property MOU is not accepted yet.');location.href='audit/?uid='+encodeURIComponent(id)}catch(e){showError('Could not open property audit',friendly(e))}}
async function liveSuspendPartner(id){if(!confirm('Suspend this property? Its rooms will stop accepting new direct bookings, but booking and settlement history stays intact.'))return;try{var ref=db.collection('partners').doc(id),q=await ref.collection('rooms').limit(100).get(),batch=db.batch();batch.set(ref,{status:'suspended',verified:false,lifecycleStage:'paused',suspendedAt:now()},{merge:true});q.forEach(function(d){batch.set(d.ref,{marketplaceApproved:false,open:false,updatedAt:now()},{merge:true})});await batch.commit();loadAdminLive()}catch(e){showError('Could not suspend property',friendly(e))}}
/* ---- Admin: full partner details, edit, and Stay & do publishing ------------------
   Everything the join form saves lives in Firestore partners/{uid} (admin/owner readable
   only). This panel shows it all, lets the founder edit the public-facing fields, and
   publishes a public-safe entry to config/partners (public-read, admin-write), which the
   homepage "Stay & do" page merges in. The owner's WhatsApp number is only published when
   the founder ticks the box. */
var adminCache=[];
var DET_FIELDS=[['name','Property name','text'],['ownerName','Owner / manager','text'],['phone','WhatsApp / phone','tel'],['zone','City / zone','text'],['area','Area / address','text'],['type','Property type','text'],['roomCount','Rooms','number'],['startPrice','Starting rate / night (₹)','number'],['hook','Short public description','textarea'],['website','Website / booking page','url'],['mapsUrl','Google Maps link','url'],['photoUrl','Main photo URL','url'],['videoUrl','Video URL','url'],['instagramUrl','Instagram URL','url'],['whatsappUrl','WhatsApp link (wa.me)','url'],['advancePct','Pre-book advance (% of stay)','number'],['freeCancelHours','Free cancellation until (hours before check-in)','number'],['lateRefundPct','Refund after that window (%)','number'],['gstin','GSTIN (owner-declared; verify on the GST portal)','text'],['payoutUpi','Payout UPI ID','text'],['payoutHolder','Payout account holder','text'],['payoutIfsc','Payout bank IFSC','text'],['payoutAcctLast4','Account last 4 digits','text']];
function detSlug(n){return String(n||'').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'')}
function detUrlOk(k,v){if(!v)return true;var u;try{u=new URL(v)}catch(e){return false}if(k==='website')return u.protocol==='https:'||u.protocol==='http:';if(u.protocol!=='https:')return false;if(k==='mapsUrl')return /^(www\.google\.com\/maps|maps\.app\.goo\.gl|goo\.gl\/maps)/.test(u.host+u.pathname);if(k==='whatsappUrl')return /^(wa\.me|api\.whatsapp\.com)$/.test(u.host);if(k==='instagramUrl')return /(^|\.)instagram\.com$/.test(u.host);return true}
function detValue(v){if(v==null||v==='')return '—';if(typeof v==='object')return '<pre style="margin:0;white-space:pre-wrap;font-size:11px">'+esc(JSON.stringify(v,null,1))+'</pre>';return esc(String(v))}
/* One-tap WhatsApp messages to the owner, pre-written. wa.me opens the admin's own WhatsApp: nothing is sent by RoamWise. */
function detWaLinks(p,pub){
  var d=String(p.phone||p.ownerWa||'').replace(/\D/g,'');if(d.length===10)d='91'+d;if(d.length<11||d.length>15)return '';
  var nm=p.ownerName?String(p.ownerName).split(' ')[0]:'there',base='https://wa.me/'+d+'?text=',pn=p.name||'your property';
  var msgs=[
    ['Send join steps',pub?'':'Hello '+nm+', thank you for applying to list '+pn+' on RoamWise. To go live we need: 1) your GSTIN if registered (or tell us you are not), 2) a UPI ID for guest payments, 3) two real photos. You can add them here: https://roamwise.co.in/partner/ . Reply here if you need help.'],
    ['Ask for stay outcomes','Hello '+nm+', quick monthly check for '+pn+': please open https://roamwise.co.in/partner/stays/ and mark each RoamWise booking code as completed, cancelled or no-show with the stay value. It takes a minute and keeps our records accurate.']
  ];
  return msgs.filter(function(m){return m[1]}).map(function(m){return '<a class="btn" target="_blank" rel="noopener" href="'+esc(base+encodeURIComponent(m[1]))+'">'+esc(m[0])+' ↗</a>'}).join('');
}
/* Automatic compliance check for the admin panel: public listing facts plus what only the admin can see. */
function detTrustHTML(p,pub){
  if(typeof RWTrust==='undefined')return '';
  var pid='p_'+detSlug(p.name),seed=((window.RW_PARTNER_SEED||[]).filter(function(x){return x.id===pid})[0])||{},l=pub||{},m=l.bookingMode||seed.bookingMode||'',rt='none';
  var wa=String(l.bookingWhatsapp||seed.bookingWhatsapp||'').replace(/\D/g,''),ph=String(l.bookingPhone||'').replace(/\D/g,''),url=l.bookingUrl||seed.bookingUrl||'';
  if(m==='direct')rt='direct';else if(m==='whatsapp'&&wa.length>=11)rt='whatsapp';else if(m==='phone'&&ph.length>=10)rt='phone';else if((m==='ota'||m==='website')&&/^https:/.test(url))rt=m;
  var g=typeof RWGstin!=='undefined'?RWGstin:null,gv=!!(l.gstVerified),
      r=RWTrust.assess({verified:pub?'signed':'',listingReady:!!pub,routeType:rt,area:p.area||l.area||seed.area,mapsUrl:p.mapsUrl||l.mapsUrl||seed.mapsUrl,
        photoCount:(seed.photos||[]).length||Number(l.photoCount)||Number(p.photoCount)||0,gstVerified:gv,advancePct:Number(p.advancePct)||Number(l.advancePct)||0,
        freeCancelHours:Number(p.freeCancelHours)||Number(l.freeCancelHours)||0,payoutReady:!!(l.payoutReady||(g&&g.payoutSummary(p).ready)),supportEmail:l.supportEmail||seed.supportEmail});
  var pill=r.tier==='trusted'?'green':r.tier==='checked'?'green':'gold';
  return '<div style="border:1px solid var(--line);border-radius:10px;padding:10px;margin-bottom:10px"><div style="display:flex;gap:8px;flex-wrap:wrap;align-items:center"><b>RoamWise compliance check</b><span class="pill '+pill+'">'+esc(r.tier.toUpperCase())+' · '+r.score+'/100</span>'
    +r.badges.map(function(b){return '<span class="pill">'+esc(b)+'</span>'}).join('')+'</div>'
    +'<div style="font-size:12px;margin-top:6px">'+r.checks.map(function(c){return (c.ok?'✓ ':c.partial?'~ ':'✗ ')+esc(c.label)+(c.note?' ('+esc(c.note)+')':'')}).join('<br>')+'</div>'
    +(r.missing.length?'<div class="muted" style="font-size:12px;margin-top:6px"><b>To improve:</b><br>'+r.missing.map(function(x){return '• '+esc(x.fix)}).join('<br>')+'</div>':'')
    +'<div class="muted" style="font-size:11px;margin-top:6px">Automatic paperwork check (rules '+esc(r.rulesVersion)+'). It does not inspect the property. Badges refresh on the public page by themselves.</div></div>';
}
async function liveDetail(id){var box=$('pd-'+id);if(!box)return;if(!box.hidden){box.hidden=true;return}
  var p=adminCache.filter(function(x){return x._id===id})[0];if(!p)return;box.hidden=false;box.innerHTML='<div class="empty">Loading…</div>';
  var pid='p_'+detSlug(p.name),pub=null;try{var c=await db.collection('config').doc('partners').get();var l=c.exists&&Array.isArray((c.data()||{}).list)?c.data().list:[];pub=l.filter(function(x){return x&&x.id===pid})[0]||null}catch(e){}
  var editKeys=DET_FIELDS.map(function(f){return f[0]}).concat(['ownerWa']);
  var form=DET_FIELDS.map(function(f){var v=p[f[0]]==null?'':p[f[0]];return '<label style="display:block;font-size:12px"><span class="muted">'+esc(f[1])+'</span>'+(f[2]==='textarea'?'<textarea data-k="'+f[0]+'" rows="3" maxlength="300" style="width:100%;box-sizing:border-box">'+esc(v)+'</textarea>':'<input data-k="'+f[0]+'" type="'+(f[2]==='number'?'number':'text')+'" value="'+esc(v)+'" maxlength="500" style="width:100%;box-sizing:border-box">')+'</label>'}).join('');
  var rest=Object.keys(p).filter(function(k){return k!=='_id'&&editKeys.indexOf(k)<0}).sort().map(function(k){return '<div style="display:grid;grid-template-columns:150px minmax(0,1fr);gap:8px;padding:5px 0;border-top:1px solid var(--line);font-size:12px"><span class="muted">'+esc(k)+'</span><div style="word-break:break-word">'+detValue(p[k])+'</div></div>'}).join('');
  var digits=String(p.phone||p.ownerWa||'').replace(/\D/g,'');
  box.innerHTML='<div style="display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin-bottom:10px"><b>'+esc(p.name||'Property')+'</b><span class="pill '+(pub?'green':'gold')+'">'+(pub?'Live on Stay &amp; do':'Not on Stay &amp; do')+'</span>'+(digits?'<a class="btn" target="_blank" rel="noopener" href="https://wa.me/'+(digits.length===10?'91':'')+digits+'">Open WhatsApp ↗</a>':'')+(p.mapsUrl&&detUrlOk('mapsUrl',p.mapsUrl)?'<a class="btn" target="_blank" rel="noopener" href="'+esc(p.mapsUrl)+'">Google Maps ↗</a>':'')+'<a class="btn" href="audit/?uid='+encodeURIComponent(id)+'">Trust audit</a>'+detWaLinks(p,pub)+'</div>'
   +detTrustHTML(p,pub)
   +'<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,240px),1fr));gap:10px">'+form+'</div>'
   +'<div style="display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin:12px 0"><button class="btn green" data-pdsave="'+id+'">Save changes</button><button class="btn green" data-pdwapub="'+id+'">Owner agreed: go live on WhatsApp</button><button class="btn" data-pdpub="'+id+'">'+(pub?'Update Stay &amp; do listing':'Publish to Stay &amp; do')+'</button>'+(pub?'<button class="btn red" data-pdunpub="'+id+'">Remove from Stay &amp; do</button>':'')+'<label style="font-size:12px"><input type="checkbox" id="pdwa-'+id+'"'+(pub&&(pub.bookingMode==='whatsapp'||pub.bookingMode==='phone')?' checked':'')+'> Show this number to travellers (owner agreed)</label><label style="font-size:12px"><input type="checkbox" id="pdgst-'+id+'"'+(pub&&pub.gstVerified?' checked':'')+'> GST verified on the GST portal (matches this property)</label></div>'
   +'<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,200px),1fr));gap:10px;margin-bottom:8px"><label style="font-size:12px;display:block"><span class="muted">How travellers book</span><select id="pdmode-'+id+'" style="width:100%;box-sizing:border-box"><option value="">Not set (hidden from travellers)</option>'+[['whatsapp','WhatsApp chat (same message as Milan Heights)'],['phone','Phone call']].map(function(o){return '<option value="'+o[0]+'"'+(pub&&pub.bookingMode===o[0]?' selected':'')+'>'+o[1]+'</option>'}).join('')+'</select></label>'
   +'</div><div id="pdx-'+id+'"></div>'
   +'<div id="pdmsg-'+id+'" class="muted" style="min-height:18px"></div>'
   +'<details style="margin-top:8px"><summary class="muted" style="cursor:pointer">Everything else saved for this property</summary><div style="margin-top:6px">'+rest+'</div></details>';
  box.querySelector('[data-pdsave]').onclick=function(){liveDetailSave(id)};box.querySelector('[data-pdpub]').onclick=function(){liveListPublish(id,true)};var wb=box.querySelector('[data-pdwapub]');if(wb)wb.onclick=function(){var m=$('pdmode-'+id),c=$('pdwa-'+id);if(m)m.value='whatsapp';if(c)c.checked=true;liveListPublish(id,true)};var un=box.querySelector('[data-pdunpub]');if(un)un.onclick=function(){liveListPublish(id,false)};detOpsInit(id,p)}
function detMsg(id,t,bad){var m=$('pdmsg-'+id);if(m){m.textContent=t;m.style.color=bad?'#ff8a8a':''}}
async function liveDetailSave(id){var box=$('pd-'+id),u={},bad='';box.querySelectorAll('[data-k]').forEach(function(el){var k=el.getAttribute('data-k'),v=String(el.value||'').trim();if(el.type==='number'){u[k]=v===''?0:Number(v);if(!isFinite(u[k])||u[k]<0||((k==='advancePct'||k==='lateRefundPct')&&u[k]>100)||(k==='freeCancelHours'&&u[k]>720))bad='Please check '+k+'.'}else{if(el.tagName==='INPUT'&&el.type==='text'&&/Url$/.test(k)||k==='website'){if(!detUrlOk(k,v))bad='Please check the '+k+' link (it must be a valid https link of the right kind).'}u[k]=v}});
  if(bad){detMsg(id,bad,true);return}if(!u.name||u.name.length<3){detMsg(id,'Property name is required.',true);return}
  u.ownerWa=u.phone;u.updatedAt=now();u.adminEditedAt=now();detMsg(id,'Saving…');
  try{await db.collection('partners').doc(id).set(u,{merge:true});var i=adminCache.findIndex(function(x){return x._id===id});if(i>=0)Object.assign(adminCache[i],u);detMsg(id,'Saved.')}catch(e){detMsg(id,friendly(e),true)}}
async function liveListPublish(id,on){try{detMsg(id,on?'Publishing…':'Removing…');var d=await db.collection('partners').doc(id).get();if(!d.exists)throw Error('Partner not found.');var p=d.data()||{},o=p.onboarding||{};
  if(on){if(p.status!=='active')throw Error('Approve this property first.');if(!o.mouAcceptedAt)throw Error('The MOU has not been accepted yet.');if(!p.name||!p.zone)throw Error('Property name and city are required.')}
  var ref=db.collection('config').doc('partners'),c=await ref.get(),list=c.exists&&Array.isArray((c.data()||{}).list)?c.data().list.slice():[],pid='p_'+detSlug(p.name);
  list=list.filter(function(x){return x&&x.id!==pid});
  if(on){var e={id:pid,cat:'stay',zone:p.zone,area:p.area||'',name:p.name,verified:'signed',listingReady:true,supportEmail:'founder@roamwise.co.in',partnerUid:id};
    if(p.hook)e.hook=String(p.hook).slice(0,300);['advancePct','freeCancelHours','lateRefundPct'].forEach(function(k){var n=Math.round(Number(p[k]));if(isFinite(n)&&n>0)e[k]=n});var pc=Math.round(Number(p.photoCount));if(pc>0)e.photoCount=Math.min(4,pc);if(p.mapsUrl&&detUrlOk('mapsUrl',p.mapsUrl))e.mapsUrl=p.mapsUrl;
    var wa=$('pdwa-'+id),ms=$('pdmode-'+id),us=$('pdurl-'+id),os=$('pdota-'+id),mode=ms&&ms.value||'',digits=String(p.phone||p.ownerWa||'').replace(/\D/g,'');if(digits.length===10)digits='91'+digits;
    if(!mode&&wa&&wa.checked)mode='whatsapp';
    if(mode==='whatsapp'||mode==='phone'){if(!(wa&&wa.checked))throw Error('Tick the box to confirm the owner agreed to show this number to travellers.');if(!(digits.length>=11&&digits.length<=15))throw Error('A valid phone number is needed for this booking route.');
      e.bookingMode=mode;if(mode==='whatsapp')e.bookingWhatsapp=digits;else e.bookingPhone=digits}
    else if(mode==='ota'||mode==='website'){var bu=us?String(us.value||'').trim():'';if(!detUrlOk('bookingUrl',bu)||!/^https:\/\//.test(bu))throw Error('Enter the booking link as a valid https link.');e.bookingMode=mode;e.bookingUrl=bu;var on=os?String(os.value||'').trim().slice(0,40):'';if(on&&mode==='ota')e.bookingOtaName=on}
    var gv=$('pdgst-'+id);if(gv&&gv.checked){var gr=typeof RWGstin!=='undefined'?RWGstin.validateGstin(p.gstin):{ok:false};if(!gr.ok)throw Error('Save a valid GSTIN before marking GST verified.');e.gstVerified=true;e.gstin=gr.gstin}
    if(typeof RWGstin!=='undefined'&&RWGstin.payoutSummary(p).ready)e.payoutReady=true;
    try{var pp=await db.collection('partnerPublicProfiles').doc(id).get(),b=pp.exists?(pp.data()||{}).badges:null;if(Array.isArray(b)&&b.length)e.badges=b}catch(x){}
    list.push(e)}
  await ref.set({list:list,updatedAt:now()},{merge:true});detMsg(id,on?''+(e.bookingMode?'Published. It appears on Stay & do on the next page load.':'Saved, but hidden from travellers until a booking route is set.')+'':'Removed from Stay & do.');setTimeout(function(){var b=$('pd-'+id);if(b){b.hidden=true;liveDetail(id)}},600)}catch(e){detMsg(id,e&&e.message?e.message:friendly(e),true)}}
async function liveComplete(id){try{await db.collection('roomBookings').doc(id).update({status:'completed',completedAt:now()});loadAdminLive()}catch(e){showError('Could not complete booking',friendly(e))}}
async function saveTravelLive(){var out=readTravelForm(S.travel);try{await db.collection('config').doc('partnerMarketplace').set(out,{merge:true});S.travel=out;msg('travelMsg','Saved for RoamWise.')}catch(e){msg('travelMsg',friendly(e),true)}}
/* ---- Photo upload, booking policy preview, owner nudges (admin only) ---- */
var photoDraft={};
function detPid(id){var p=adminCache.filter(function(x){return x._id===id})[0];return 'p_'+detSlug(p&&p.name)}
function detCompress(file,maxSide,cb){var r=new FileReader();r.onload=function(){var im=new Image();im.onload=function(){var sc=Math.min(1,maxSide/Math.max(im.width,im.height)),w=Math.round(im.width*sc),h=Math.round(im.height*sc),c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(im,0,0,w,h);var q=.82,t='image/webp',u=c.toDataURL(t,q);if(u.indexOf('data:image/webp')!==0){t='image/jpeg';u=c.toDataURL(t,q)}while(u.length>300000&&q>.4){q-=.1;u=c.toDataURL(t,q)}cb(u.length<=300000?u:null)};im.onerror=function(){cb(null)};im.src=r.result};r.onerror=function(){cb(null)};r.readAsDataURL(file)}
function detPhotoRender(id){var box=$('pdph-'+id);if(!box)return;var d=photoDraft[id]||[];box.innerHTML=d.length?d.map(function(x,i){return '<div style="display:inline-block;margin:0 8px 8px 0;vertical-align:top;width:120px"><img alt="" src="'+x.src+'" style="width:120px;height:80px;object-fit:cover;border-radius:8px;display:block"><input data-phcap="'+i+'" type="text" maxlength="80" placeholder="Caption" value="'+esc(x.caption||'')+'" style="width:100%;box-sizing:border-box;font-size:11px;margin-top:4px"><button class="btn red" data-phdel="'+i+'" style="width:100%;margin-top:4px">Remove</button></div>'}).join(''):'<span class="muted">No uploaded photos yet.</span>';box.querySelectorAll('[data-phdel]').forEach(function(b){b.onclick=function(){d.splice(Number(b.getAttribute('data-phdel')),1);detPhotoRender(id)}});box.querySelectorAll('[data-phcap]').forEach(function(i){i.oninput=function(){d[Number(i.getAttribute('data-phcap'))].caption=i.value}})}
async function detPhotoPick(id,files){var d=photoDraft[id]=photoDraft[id]||[];var list=Array.prototype.slice.call(files||[]).filter(function(f){return /^image\//.test(f.type)});if(!list.length){detMsg(id,'Choose image files.',true);return}
  for(var i=0;i<list.length&&d.length<4;i++){var u=await new Promise(function(ok){detCompress(list[i],1280,ok)});if(!u){detMsg(id,'Could not process '+list[i].name+'.',true);continue}d.push({src:u,caption:''})}
  detMsg(id,d.length>=4?'Maximum 4 photos. Press Save photos.':'Press Save photos to publish them.');detPhotoRender(id)}
async function detPatchEntry(pid,fields){var ref=db.collection('config').doc('partners'),c=await ref.get(),l=c.exists&&Array.isArray((c.data()||{}).list)?c.data().list.slice():[],i=l.findIndex(function(x){return x&&x.id===pid});if(i<0)return false;l[i]=Object.assign({},l[i],fields);await ref.set({list:l,updatedAt:now()},{merge:true});return true}
async function detPhotoSave(id){var d=(photoDraft[id]||[]).slice(0,4),pid=detPid(id),p=adminCache.filter(function(x){return x._id===id})[0]||{};detMsg(id,'Saving photos…');
  try{for(var i=0;i<4;i++){var ref=db.collection('config').doc('photo_'+pid+'_'+i);if(i<d.length)await ref.set({src:d[i].src,alt:String(p.name||'Property')+' photo '+(i+1),caption:String(d[i].caption||'').slice(0,80),updatedAt:now()});else await ref.delete().catch(function(){})}
    await db.collection('partners').doc(id).set({photoCount:d.length,updatedAt:now()},{merge:true});var k=adminCache.findIndex(function(x){return x._id===id});if(k>=0)adminCache[k].photoCount=d.length;
    var live=await detPatchEntry(pid,{photoCount:d.length});detMsg(id,d.length+' photo'+(d.length===1?'':'s')+' saved'+(live?' and live on Stay & do.':'. They appear once the property is published.'))}catch(e){detMsg(id,friendly(e),true)}}
function detCalc(id){var out=$('pdcalc-'+id);if(!out||typeof rwStayQuote!=='function')return;var v=function(k){var e=document.querySelector('#pd-'+id+' [data-k="'+k+'"]');return e?e.value:''},n=$('pdcn-'+id),q=rwStayQuote({rate:v('startPrice'),nights:n?n.value:2,policy:{advancePct:v('advancePct'),freeCancelHours:v('freeCancelHours'),lateRefundPct:v('lateRefundPct')},feePct:7}),m=function(x){return '₹'+Number(x).toLocaleString('en-IN')};
  if(!q.ok){out.innerHTML='<span class="muted">Enter a starting rate to preview the numbers.</span>';return}
  var gl='';if(typeof RWGst!=='undefined'){var g=RWGst.stay({nightlyValue:q.rate,nights:q.nights,rooms:1,registered:true});gl=g.rateBps?'<div class="muted">If your property is GST-registered: GST '+(g.rateBps/100)+'% = <b>'+m(g.tax)+'</b> on this stay'+(g.itc==='none'?' (no input credit)':' (input credit available)')+'. Below the registration threshold, charge no GST.</div>':'<div class="muted">Rooms under ₹1,000 a night are GST-exempt.</div>'}
  out.innerHTML=gl+'<div>Stay total <b>'+m(q.total)+'</b> · advance to pre-book <b>'+m(q.advance)+'</b> · pay at hotel <b>'+m(q.balance)+'</b></div><div>If cancelled: '+q.cancellation.map(function(r){return esc(r.label)+' → refund <b>'+m(r.refundOfAdvance)+'</b> ('+r.refundPct+'%)'}).join(' · ')+'</div><div class="muted">RoamWise fee after a completed stay (Partner Free 7%, before any GST on the fee): '+m(q.propertyFee)+', charged to the property, never to the guest. Guest pays the hotel directly, so the hotel makes any refund.</div><div class="muted">'+esc(rwStayPolicyText(q.policy)||'No public policy line until an advance or free-cancellation window is set.')+'</div>'}
async function detOpsInit(id,p){var host=$('pdx-'+id);if(!host)return;var pid='p_'+detSlug(p.name),digits=String(p.phone||p.ownerWa||'').replace(/\D/g,'');if(digits.length===10)digits='91'+digits;
  var ask='Hello'+(p.ownerName?' '+p.ownerName:'')+', this is RoamWise. To show '+(p.name||'your property')+' at its best, please send 4 clear photos here: the building front, a room, the dining area and the view. Thank you!';
  host.innerHTML='<div style="border-top:1px solid var(--line);margin:10px 0;padding-top:10px"><b style="font-size:13px">Photos</b> '+(digits?'<a class="btn" target="_blank" rel="noopener" href="https://wa.me/'+digits+'?text='+encodeURIComponent(ask)+'">Ask owner for photos on WhatsApp ↗</a>':'')+'<div id="pdph-'+id+'" style="margin:8px 0"></div><label class="btn" style="display:inline-block;cursor:pointer">Choose photos<input id="pdpf-'+id+'" type="file" accept="image/*" multiple style="display:none"></label> <button class="btn green" id="pdps-'+id+'">Save photos</button><div class="muted" style="font-size:11px">Up to 4 photos, compressed here before saving. The owner must have shared them for this listing.</div></div>'
   +'<div style="border-top:1px solid var(--line);margin:10px 0;padding-top:10px"><b style="font-size:13px">Pre-book and refund preview</b> <label style="font-size:12px">nights <input id="pdcn-'+id+'" type="number" min="1" max="60" value="2" style="width:56px"></label><div id="pdcalc-'+id+'" style="font-size:12px;line-height:1.6;margin-top:6px"></div></div>';
  $('pdpf-'+id).onchange=function(){detPhotoPick(id,this.files);this.value=''};$('pdps-'+id).onclick=function(){detPhotoSave(id)};
  $('pdcn-'+id).oninput=function(){detCalc(id)};document.querySelectorAll('#pd-'+id+' [data-k="startPrice"],#pd-'+id+' [data-k="advancePct"],#pd-'+id+' [data-k="freeCancelHours"],#pd-'+id+' [data-k="lateRefundPct"]').forEach(function(e){e.oninput=function(){detCalc(id)}});detCalc(id);
  photoDraft[id]=[];var n=Math.min(4,Math.round(Number(p.photoCount))||0);for(var i=0;i<n;i++){try{var d=await db.collection('config').doc('photo_'+pid+'_'+i).get();if(d.exists&&/^data:image\//.test((d.data()||{}).src||''))photoDraft[id].push({src:d.data().src,caption:d.data().caption||''})}catch(e){}}detPhotoRender(id)}
if(qs('mode')==='live'||qs('mode')==='demo')S.mode=qs('mode');if(ROLES[qs('role')])S.role=qs('role');initFirebase();render();setTimeout(function(){if(S.mode==='live'&&S.role==='admin'&&S.staffRole==='partnerships'&&!S.isAdmin)partnershipStaffDesk()},900);
})();
