/* RoamWise Partner Marketplace v2
 * Progressive enhancement over partner/app.js.
 * Keeps secrets out of the static frontend. Direct bookings are authenticated Firestore records;
 * payment collection is pay-at-property, UPI-after-confirmation, or a host-configured public payment link.
 */
(function(){
'use strict';
var $=function(s,r){return (r||document).querySelector(s)}, $$=function(s,r){return Array.from((r||document).querySelectorAll(s));};
var esc=function(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c})};
var now=function(){return new Date().toISOString()}, DEMO=(new URLSearchParams(location.search).get('mode')==='demo'||new URLSearchParams(location.search).get('lab')==='1'&&!/^(www\.)?roamwise\.co\.in$/i.test(location.hostname));
var DKEY='rw_partner_dropin_demo_v1', profileCache={}, pendingRoomId=null, enhancing=false;
function fb(){try{return{db:firebase.firestore(),auth:firebase.auth()}}catch(e){return{db:null,auth:null}}}
function money(n){return '₹'+Math.round(Number(n||0)).toLocaleString('en-IN')}
function nights(a,b){var x=new Date(a+'T12:00:00'),y=new Date(b+'T12:00:00');return Math.max(1,Math.round((y-x)/86400000)||1)}
function ctx(){return{destination:($('#dest')||{}).value||'',checkin:($('#checkin')||{}).value||'',checkout:($('#checkout')||{}).value||'',guests:Math.max(1,Number(($('#guests')||{}).value||1))}}
function modal(html){var m=$('#modal'),b=$('#modalbox');if(!m||!b)return;b.innerHTML=html;m.classList.add('open')}
function close(){var m=$('#modal');if(m)m.classList.remove('open')}
function uid(p){return p+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7)}
function demoData(){try{return JSON.parse(localStorage.getItem(DKEY))||null}catch(e){return null}}
function saveDemo(d){try{localStorage.setItem(DKEY,JSON.stringify(d))}catch(e){}}
function cleanUrl(v){v=String(v||'').trim();if(!v)return'';try{var u=new URL(v);return /^https?:$/.test(u.protocol)?u.href:''}catch(e){return''}}
function validUpi(v){return /^[\w.\-]{2,}@[A-Za-z][A-Za-z0-9.\-]{1,}$/.test(String(v||'').trim())}
function safeImage(v){var u=cleanUrl(v);return u&&/^https:\/\//i.test(u)?u:''}
function currentUser(){try{return firebase.auth().currentUser}catch(e){return null}}
async function partnerProfile(uid){if(!uid)return null;if(profileCache[uid])return profileCache[uid];var F=fb();if(!F.db)return null;try{var d=await F.db.collection('partners').doc(uid).get();if(d.exists){var x=d.data()||{};x._id=d.id;profileCache[uid]=x;return x}}catch(e){}return null}
function paymentModes(p,x){var pub=(x&&x.paymentPublic)||{},pay=(p&&p.payout)||{},out=[{id:'pay_at_property',label:'Pay at property',sub:'No money is taken by RoamWise today.',enabled:true}];if(validUpi(pub.upiId||pay.upiId))out.push({id:'upi_after_confirmation',label:'UPI after host confirms',sub:'Pay only after availability is confirmed.',enabled:true});if(cleanUrl(pub.paymentLink||pay.paymentLink))out.push({id:'secure_link_after_confirmation',label:'Secure payment link after confirmation',sub:'The host’s verified public payment page opens after confirmation.',enabled:true});return out}
function parseBookButton(b){try{return JSON.parse(b.dataset.book||'{}')}catch(e){return null}}
async function enhanceStayCards(){var cards=$$('.result.direct');for(var i=0;i<cards.length;i++){var card=cards[i];if(card.dataset.rwMarket==='1')continue;var btn=$('[data-book]',card),x=btn&&parseBookButton(btn);if(!x)continue;card.dataset.rwMarket='1';card.classList.add('rw-market-result');if(btn)btn.textContent='View & request';var p=await partnerProfile(x.partnerUid),image=safeImage((x&&x.heroImage)||(p&&p.heroImage)),amen=(x.amenities||(p&&p.amenities)||[]);if(typeof amen==='string')amen=amen.split(',').map(function(s){return s.trim()}).filter(Boolean);var pic=$('.pic',card);if(pic){pic.classList.add('rw-market-picture');pic.innerHTML='<span>RW</span>';if(image)pic.style.backgroundImage='url("'+image.replace(/"/g,'%22')+'")'}var body=card.children[1];if(body){var chips=document.createElement('div');chips.className='rw-market-chips';chips.innerHTML='<span>✦ RoamWise verified</span>'+(amen||[]).slice(0,3).map(function(a){return '<span>'+esc(a)+'</span>'}).join('')+(p&&p.bookingPolicy&&p.bookingPolicy.requestToBook===false?'<span>Fast confirmation</span>':'<span>Request to book</span>');body.appendChild(chips)}}}
function bookingHero(x,p){var img=safeImage((x&&x.heroImage)||(p&&p.heroImage));return '<div class="rw-book-hero '+(img?'has':'')+'" '+(img?'style="background-image:url(&quot;'+esc(img)+'&quot;)"':'')+'><div><span>ROAMWISE STAYS</span><h2>'+esc(x.name||'RoamWise stay')+'</h2><p>'+esc([x.room,x.area||x.zone].filter(Boolean).join(' · '))+'</p></div></div>'}
function openBooking(x){var C=ctx(),ns=nights(C.checkin,C.checkout),amount=Number(x.price||0)*ns;modal('<div class="rw-book-loading"><span>✦</span><b>Preparing your stay…</b></div>');partnerProfile(x.partnerUid).then(function(p){renderBooking(x,p,C,ns,amount)})}
function renderBooking(x,p,C,ns,amount){var modes=paymentModes(p,x),cancel=x.cancel||(p&&p.cancellation)||'Cancellation terms are confirmed by the host before payment.';modal('<div class="rw-book-shell">'+bookingHero(x,p)+'<button class="rw-book-x" id="rwBookClose">×</button><div class="rw-book-grid"><section><div class="rw-book-title"><small>REQUEST TO BOOK</small><h3>Your stay, in one clear step.</h3></div><div class="rw-trip-strip"><span><b>'+esc(C.checkin)+'</b>Check-in</span><i>→</i><span><b>'+esc(C.checkout)+'</b>Check-out</span><span><b>'+C.guests+'</b>Guest'+(C.guests>1?'s':'')+'</span></div><div class="rw-book-fields"><label>Name<input id="rwBgName" autocomplete="name" placeholder="Traveller name"></label><label>Email<input id="rwBgEmail" type="email" autocomplete="email" value="'+esc((currentUser()||{}).email||'')+'" placeholder="you@example.com"></label><label>Phone<input id="rwBgPhone" autocomplete="tel" placeholder="+91…"></label><label>Arrival note<textarea id="rwBgNote" placeholder="Arrival time, dietary request, accessibility note…"></textarea></label></div><div class="rw-pay-title"><b>How would you like to pay?</b><small>RoamWise never asks you to send money before the host confirms availability.</small></div><div class="rw-pay-options">'+modes.map(function(m,i){return '<label class="rw-pay-option '+(i===0?'on':'')+'"><input type="radio" name="rwPay" value="'+m.id+'" '+(i===0?'checked':'')+'><span><b>'+esc(m.label)+'</b><small>'+esc(m.sub)+'</small></span><i>✓</i></label>'}).join('')+'</div><div class="rw-book-policy"><b>Cancellation</b><span>'+esc(cancel)+'</span></div><div id="rwBookAuth"></div><button class="rw-book-submit" id="rwBookSubmit">Request this stay →</button><p class="rw-book-fine">Your request is sent to the property. A payment option becomes actionable only after confirmation. RoamWise does not store card numbers.</p></section><aside><div class="rw-price-card"><div><span>'+money(x.price)+'</span><small>per night</small></div><div class="rw-price-row"><span>'+money(x.price)+' × '+ns+' nights</span><b>'+money(amount)+'</b></div><div class="rw-price-row"><span>RoamWise booking fee</span><b>₹0</b></div><div class="rw-price-total"><span>Total stay</span><b>'+money(amount)+'</b></div></div><div class="rw-trust-card"><b>✦ Booking protection</b><p>Verified host identity/status is shown before the stay is listed. Keep payment and confirmation records inside RoamWise.</p></div></aside></div></div>');$('#rwBookClose').onclick=close;$$('input[name="rwPay"]').forEach(function(r){r.onchange=function(){$$('.rw-pay-option').forEach(function(l){l.classList.remove('on')});r.closest('.rw-pay-option').classList.add('on')}});$('#rwBookSubmit').onclick=function(){submitBooking(x,p,C,ns,amount)}}
function authBox(after){var host=$('#rwBookAuth');if(!host)return;host.innerHTML='<div class="rw-auth-inline"><b>Sign in to send a real booking</b><input id="rwAuthEmail" type="email" placeholder="Email"><input id="rwAuthPass" type="password" placeholder="Password (6+ characters)"><div><button id="rwAuthLogin">Sign in</button><button id="rwAuthCreate">Create account</button></div><small id="rwAuthMsg"></small></div>';var F=fb();function go(create){var e=$('#rwAuthEmail').value.trim(),p=$('#rwAuthPass').value;if(!e||p.length<6){$('#rwAuthMsg').textContent='Enter a valid email and password of at least 6 characters.';return}(create?F.auth.createUserWithEmailAndPassword(e,p):F.auth.signInWithEmailAndPassword(e,p)).then(function(){host.innerHTML='<div class="rw-auth-ok">✓ Signed in. Sending your request…</div>';after()}).catch(function(err){$('#rwAuthMsg').textContent=(err&&err.message)||'Could not sign in.'})}$('#rwAuthLogin').onclick=function(){go(false)};$('#rwAuthCreate').onclick=function(){go(true)}}
async function submitBooking(x,p,C,ns,amount){var name=($('#rwBgName')||{}).value.trim(),email=($('#rwBgEmail')||{}).value.trim(),phone=($('#rwBgPhone')||{}).value.trim(),note=($('#rwBgNote')||{}).value.trim(),method=($('input[name="rwPay"]:checked')||{}).value||'pay_at_property';if(!name||!email||!/^\S+@\S+\.\S+$/.test(email)){alert('Add your name and a valid email.');return}var user=currentUser();if(!DEMO&&!user){authBox(function(){submitBooking(x,p,C,ns,amount)});return}var rec={ref:'RW-'+Date.now().toString(36).toUpperCase(),status:'requested',bookingVersion:'marketplace-v2',partnerUid:x.partnerUid||'',propertyId:x.propertyId||'',roomId:x.roomId||'',guestUid:user?user.uid:'demo_guest',guestName:name,guestEmail:email,guestPhone:phone,note:note,property:x.name||'',room:x.room||'',zone:x.zone||'',area:x.area||'',checkIn:C.checkin,checkOut:C.checkout,guests:C.guests,nights:ns,roomPrice:Number(x.price||0),amount:amount,commissionPctSnapshot:Number(x.commissionPct||8),paymentMethod:method,paymentStatus:method==='pay_at_property'?'pay_at_property':'awaiting_host_confirmation',createdAt:now(),at:now()};var b=$('#rwBookSubmit');if(b){b.disabled=true;b.textContent='Sending…'}try{if(DEMO){var d=demoData();if(!d)throw new Error('Demo workspace not ready');rec._id=uid('booking');d.bookings=d.bookings||[];d.bookings.unshift(rec);saveDemo(d)}else{var F=fb(),doc=await F.db.collection('roomBookings').add(rec);rec._id=doc.id}bookingSuccessV2(rec,p)}catch(e){if(b){b.disabled=false;b.textContent='Request this stay →'}alert('Could not create booking: '+((e&&e.message)||e))}}
function bookingSuccessV2(rec,p){var method=rec.paymentMethod==='pay_at_property'?'Pay at property':rec.paymentMethod==='upi_after_confirmation'?'UPI after confirmation':'Secure payment link after confirmation';modal('<div class="rw-book-success"><div class="rw-success-orbit"><span>✓</span></div><small>REQUEST SENT</small><h2>'+esc(rec.ref)+'</h2><p>'+esc(rec.property)+' now has your request. Do not prepay until the host confirms availability.</p><div class="rw-success-steps"><span class="on"><b>1</b>Requested</span><i></i><span><b>2</b>Host confirms</span><i></i><span><b>3</b>'+esc(method)+'</span></div><button class="rw-book-submit" id="rwDone">Done</button></div>');$('#rwDone').onclick=function(){close();setTimeout(enhanceAll,50)}}
function verificationPanel(){if($('#rwVerifyPanel')||!$('#submitOwner'))return;var n=document.createElement('div');n.id='rwVerifyPanel';n.className='rw-onboard-verification';n.innerHTML='<div class="rw-onboard-head"><span>✦</span><div><b>RoamWise verification</b><small>We verify people and properties before the verified badge appears.</small></div></div><div class="rw-verify-grid"><label><input type="checkbox" id="rwOwnerAuth"> I am the owner or authorised to list this property.</label><label><input type="checkbox" id="rwRateAuth"> Rates and room details I provide are accurate.</label><label><input type="checkbox" id="rwWalkAuth"> I can join a video walkthrough if RoamWise requests one.</label><label>Public location / listing URL<input id="rwPublicLocation" placeholder="Google Maps / official website / public listing"></label></div><div class="rw-verify-note">Do not upload Aadhaar, passport or bank documents here. Sensitive KYC is handled separately when required.</div>';var btn=$('#submitOwner');btn.parentElement.insertBefore(n,btn)}
async function enhancedOwnerSubmit(e){if(DEMO||e.target.id!=='submitOwner'||!currentUser())return;e.preventDefault();e.stopImmediatePropagation();var need=['rwOwnerAuth','rwRateAuth','rwWalkAuth'];if(need.some(function(id){return !($('#'+id)||{}).checked})){alert('Complete the three verification confirmations first.');return}var user=currentUser(),doc={email:user.email||($('#oemail')||{}).value.trim(),ownerName:($('#oname')||{}).value.trim(),ownerWa:($('#ophone')||{}).value.trim(),name:($('#oprop')||{}).value.trim(),zone:($('#ozone')||{}).value.trim(),area:($('#oarea')||{}).value.trim(),type:($('#otype')||{}).value,roomCount:Math.max(1,Number(($('#orooms')||{}).value||1)),startPrice:Math.max(1,Number(($('#oprice')||{}).value||1)),website:cleanUrl(($('#oweb')||{}).value),hook:($('#ohook')||{}).value.trim(),status:'pending',verification:{ownerAttestation:true,rateAttestation:true,walkthroughConsent:true,publicLocationUrl:cleanUrl(($('#rwPublicLocation')||{}).value),identity:'pending',property:'pending',payout:'pending',overall:'pending'},bookingPolicy:{requestToBook:true},updatedAt:now()};if(!doc.ownerName||!doc.name||!doc.zone){alert('Add owner name, property name and city.');return}try{var F=fb(),old=await F.db.collection('partners').doc(user.uid).get();if(!old.exists)doc.createdAt=now();await F.db.collection('partners').doc(user.uid).set(doc,{merge:true});location.reload()}catch(err){alert('Could not submit property: '+((err&&err.message)||err))}}
async function hostStudio(){if($('#rwHostStudio')||!$('#addRoom')||DEMO)return;var user=currentUser();if(!user)return;var F=fb(),snap;try{snap=await F.db.collection('partners').doc(user.uid).get()}catch(e){return}if(!snap.exists)return;var p=snap.data()||{},v=p.verification||{},pay=p.payout||{},gallery=Array.isArray(p.gallery)?p.gallery.join('\n'):(p.gallery||''),amen=Array.isArray(p.amenities)?p.amenities.join(', '):(p.amenities||'');var pct=p.status==='active'?66:33;if(p.heroImage)pct+=12;if(amen)pct+=10;if(validUpi(pay.upiId)||cleanUrl(pay.paymentLink))pct+=12;pct=Math.min(100,pct);var box=document.createElement('section');box.id='rwHostStudio';box.className='rw-host-studio';box.innerHTML='<div class="rw-host-cover"><div><small>HOST STUDIO</small><h2>Make '+esc(p.name||'your stay')+' bookable.</h2><p>One profile powers the marketplace cards, guest trust signals and post-confirmation payment choices.</p></div><div class="rw-host-meter"><b>'+pct+'%</b><span><i style="width:'+pct+'%"></i></span><small>marketplace ready</small></div></div><div class="rw-host-verify"><span class="'+(p.status==='active'?'done':'')+'">✓ Account</span><span class="'+(p.status==='active'?'done':'')+'">✓ Property review</span><span class="'+((validUpi(pay.upiId)||cleanUrl(pay.paymentLink))?'done':'')+'">✓ Payout method</span></div><div class="rw-host-fields"><label>Hero image URL<input id="rwHostImage" value="'+esc(p.heroImage||'')+'" placeholder="https://…"></label><label>Gallery image URLs<textarea id="rwHostGallery" placeholder="One https:// URL per line">'+esc(gallery)+'</textarea></label><label>Amenities<input id="rwHostAmenities" value="'+esc(amen)+'" placeholder="Breakfast, Wi-Fi, parking, mountain view"></label><label>Cancellation policy<input id="rwHostCancel" value="'+esc(p.cancellation||'')+'" placeholder="Free cancellation up to 48h before"></label><label>UPI ID <small>optional · shown only as a post-confirmation payment method</small><input id="rwHostUpi" value="'+esc(pay.upiId||'')+'" placeholder="name@bank"></label><label>Public secure payment link <small>optional · Razorpay/other hosted payment page</small><input id="rwHostPayLink" value="'+esc(pay.paymentLink||'')+'" placeholder="https://…"></label><label>House rules<textarea id="rwHostRules" placeholder="Quiet hours, pets, smoking, check-in notes…">'+esc(p.houseRules||'')+'</textarea></label><label>Guest welcome note<textarea id="rwHostWelcome" placeholder="What should guests know before they arrive?">'+esc(p.welcomeNote||'')+'</textarea></label></div><div class="rw-host-actions"><button id="rwHostSave">Save marketplace profile</button><span id="rwHostMsg"></span></div><div class="rw-host-security"><b>Payment security</b> RoamWise stores no card number or secret gateway key here. A public hosted payment link is safe to expose; gateway secrets belong on a private server.</div>';var view=$('#view');view.insertBefore(box,view.firstChild);$('#rwHostSave').onclick=saveHostStudio}
async function saveHostStudio(){var user=currentUser();if(!user)return;var hero=safeImage(($('#rwHostImage')||{}).value),gallery=String(($('#rwHostGallery')||{}).value||'').split(/\n|,/).map(safeImage).filter(Boolean).slice(0,12),amen=String(($('#rwHostAmenities')||{}).value||'').split(',').map(function(s){return s.trim()}).filter(Boolean).slice(0,20),upi=String(($('#rwHostUpi')||{}).value||'').trim(),plink=cleanUrl(($('#rwHostPayLink')||{}).value),doc={heroImage:hero,gallery:gallery,amenities:amen,cancellation:($('#rwHostCancel')||{}).value.trim(),houseRules:($('#rwHostRules')||{}).value.trim(),welcomeNote:($('#rwHostWelcome')||{}).value.trim(),payout:{upiId:validUpi(upi)?upi:'',paymentLink:plink,updatedAt:now()},updatedAt:now()};try{var F=fb();await F.db.collection('partners').doc(user.uid).set(doc,{merge:true});var q=await F.db.collection('partners').doc(user.uid).collection('rooms').limit(100).get(),jobs=[];q.forEach(function(r){jobs.push(r.ref.set({heroImage:hero,amenities:amen,cancel:doc.cancellation,paymentPublic:{upiId:doc.payout.upiId,paymentLink:doc.payout.paymentLink},updatedAt:now()},{merge:true}))});await Promise.all(jobs);profileCache[user.uid]=Object.assign(profileCache[user.uid]||{},doc);$('#rwHostMsg').textContent='✓ Saved and synced to your rooms.'}catch(e){$('#rwHostMsg').textContent='Could not save: '+((e&&e.message)||e)}}
function paymentQueue(){if($('#rwPaymentQueue')||!$('#addRoom')||DEMO)return;var user=currentUser();if(!user)return;var F=fb();F.db.collection('roomBookings').where('partnerUid','==',user.uid).limit(60).get().then(function(q){var arr=[];q.forEach(function(d){var x=d.data()||{};x._id=d.id;if(x.status==='confirmed')arr.push(x)});if(!arr.length)return;var box=document.createElement('section');box.id='rwPaymentQueue';box.className='rw-payment-queue card';box.innerHTML='<h2>Confirmed stays & payment plan</h2><p class="muted">Guests only see the payment method they chose after you confirm the request.</p><div class="rw-pay-queue-list">'+arr.map(function(b){return '<div><span><b>'+esc(b.guestName||'Guest')+'</b><small>'+esc(b.property||'')+' · '+esc(b.checkIn||'')+' · '+money(b.amount||0)+'</small></span><em>'+esc((b.paymentMethod||'pay_at_property').replace(/_/g,' '))+'</em></div>'}).join('')+'</div>';$('#view').appendChild(box)}).catch(function(){})}
function adminTrustNote(){if($('#rwAdminTrust')||!$('#saveTravel'))return;var n=document.createElement('div');n.id='rwAdminTrust';n.className='rw-admin-trust';n.innerHTML='<b>Verification standard</b><span>Before approval: confirm the owner/contact, public location/rates, and walkthrough when needed. Never ask partners to paste identity or gateway secrets into this static dashboard.</span>';var view=$('#view');view.insertBefore(n,view.firstChild)}
function enhanceAll(){if(enhancing)return;enhancing=true;Promise.resolve().then(enhanceStayCards).finally(function(){enhancing=false});verificationPanel();hostStudio();paymentQueue();adminTrustNote()}
document.addEventListener('click',function(e){var b=e.target.closest&&e.target.closest('[data-book]');if(b){var x=parseBookButton(b);if(x){e.preventDefault();e.stopImmediatePropagation();openBooking(x);return}}if(e.target.closest&&e.target.closest('[data-editroom]'))pendingRoomId=e.target.closest('[data-editroom]').dataset.editroom||'';if(e.target.id==='addRoom')pendingRoomId='';enhancedOwnerSubmit(e)},true);
function init(){var view=$('#view');if(view&&window.MutationObserver){var o=new MutationObserver(function(){clearTimeout(init.t);init.t=setTimeout(enhanceAll,80)});o.observe(view,{childList:true,subtree:true})}setTimeout(enhanceAll,250);setTimeout(enhanceAll,1200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
window.RWPartnerMarketplaceV2={enhance:enhanceAll,openBooking:openBooking};
})();