/* RoamWise Creator Network Admin v4 add-on.
 * Adds a founder-controlled registration gate and scalable link-first content queue
 * without removing the legacy Creator Admin tools.
 */
(function(){'use strict';
var CFG={apiKey:'AIzaSyBTfmJvHTmp0mNQqsIhWEwnLLwFKz0ExYQ',authDomain:'roamwisepro.firebaseapp.com',projectId:'roamwisepro',storageBucket:'roamwisepro.firebasestorage.app',messagingSenderId:'1039880917656',appId:'1:1039880917656:web:8b3e18e8a4b1c9f8e2c0d1'};
if(!firebase.apps.length)firebase.initializeApp(CFG);
var auth=firebase.auth(),db=firebase.firestore(),busy=false;
var $=function(s,r){return(r||document).querySelector(s)};
var esc=function(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c})};
var now=function(){return new Date().toISOString()};
function tag(t,k){return'<span class="ca-tag '+(k||'')+'">'+esc(t)+'</span>'}
async function adminOk(u){if(!u||!u.emailVerified)return false;try{return (await db.collection('admins').doc(u.uid).get()).exists}catch(e){return false}}
function appForEmail(apps,email){email=String(email||'').trim().toLowerCase();return apps.find(function(a){return String(a.email||'').trim().toLowerCase()===email})||null}
async function loadClaims(){var out=[];try{var q=await db.collection('creatorAccounts').limit(250).get();q.forEach(function(d){var x=d.data()||{};x.uid=d.id;out.push(x)})}catch(e){}return out}
async function loadApps(){var out=[];try{var q=await db.collection('crm').where('seg','==','creator').limit(250).get();q.forEach(function(d){var x=d.data()||{};x.id=d.id;out.push(x)})}catch(e){}return out}
async function loadSubmissions(){var out=[];try{var q=await db.collectionGroup('submissions').limit(250).get();q.forEach(function(d){var x=d.data()||{};x.id=d.id;var uid=x.ownerUid||((d.ref.parent&&d.ref.parent.parent&&d.ref.parent.parent.id)||'');x.ownerUid=uid;out.push(x)})}catch(e){}return out}
async function loadReviews(uids){var out={};await Promise.all(uids.slice(0,100).map(async function(uid){try{var d=await db.collection('creatorEarnings').doc(uid).get();if(d.exists)out[uid]=d.data()||{}}catch(e){}}));return out}
function ensureShell(){if($('#caV4'))return $('#caV4');var dash=$('#caDash');if(!dash||dash.hidden)return null;var s=document.createElement('section');s.id='caV4';s.innerHTML='<section class="ca-panel"><div class="ca-head"><div><small>REGISTRATION GATE · V4</small><h2>Verified identity claims</h2><p>Only the founder can turn a verified Firebase identity claim into a registered Creator Studio account.</p></div><button id="caV4Refresh" class="ca-action secondary">↻ Refresh</button></div><div id="caV4Claims"><div class="ca-empty">Loading claims…</div></div></section><section class="ca-panel"><div class="ca-head"><div><small>LINK-FIRST CONTENT · V4</small><h2>Creator submission queue</h2><p>RoamWise stores URLs and metadata only. Instagram, YouTube and the creator's blog remain the media host/CDN.</p></div></div><div id="caV4Content"><div class="ca-empty">Loading submissions…</div></div></section>';
dash.appendChild(s);$('#caV4Refresh').onclick=refresh;return s}
async function refresh(){if(busy)return;var u=auth.currentUser;if(!(await adminOk(u)))return;busy=true;var shell=ensureShell();if(!shell){busy=false;return}try{var results=await Promise.all([loadClaims(),loadApps(),loadSubmissions()]),claims=results[0],apps=results[1],subs=results[2],reviews=await loadReviews(Array.from(new Set(subs.map(function(x){return x.ownerUid}).filter(Boolean))));paintClaims(claims,apps);paintSubs(subs,reviews)}catch(e){var c=$('#caV4Claims');if(c)c.innerHTML='<div class="ca-error">'+esc(e.message||e)+'</div>'}finally{busy=false}}
function paintClaims(claims,apps){var h=$('#caV4Claims');if(!h)return;if(!claims.length){h.innerHTML='<div class="ca-empty">No verified identity claims yet.</div>';return}claims.sort(function(a,b){return String(b.createdAt||'').localeCompare(String(a.createdAt||''))});h.innerHTML=claims.map(function(c){var a=appForEmail(apps,c.email),registered=c.registered===true&&c.status==='active';return'<div class="ca-row"><div><h3>'+esc(c.email||c.uid)+'</h3><p>'+esc(a?[a.name,a.handle,a.niche].filter(Boolean).join(' · '):'No matching creator application yet')+'</p><small>UID '+esc(c.uid)+'</small><div class="ca-tags">'+tag(c.emailVerified===true?'Firebase email verified':'email claim incomplete',c.emailVerified===true?'good':'bad')+tag(a?'application matched':'application missing',a?'good':'warn')+tag(registered?'registered':'not registered',registered?'good':'warn')+'</div></div><div class="ca-actions">'+(!registered&&a&&c.emailVerified===true?'<button class="ca-action green" data-v4-register="'+esc(c.uid)+'" data-v4-app="'+esc(a.id)+'">Register creator</button>':'')+(registered?'<button class="ca-action secondary" disabled>Studio allowed</button>':'')+'</div></div>'}).join('');document.querySelectorAll('[data-v4-register]').forEach(function(b){b.onclick=function(){register(b.dataset.v4Register,b.dataset.v4App,b)}})}
async function register(uid,appId,btn){var u=auth.currentUser;if(!(await adminOk(u)))return alert('Founder/admin access required.');btn.disabled=true;btn.textContent='Registering…';try{var claimRef=db.collection('creatorAccounts').doc(uid),appRef=db.collection('crm').doc(appId),claim=await claimRef.get(),app=await appRef.get();if(!claim.exists||!app.exists)throw new Error('Claim or application no longer exists.');var c=claim.data()||{},a=app.data()||{};if(c.emailVerified!==true)throw new Error('Verified Firebase identity is required.');if(String(c.email||'').trim().toLowerCase()!==String(a.email||'').trim().toLowerCase())throw new Error('Application email does not match the verified identity claim.');var stamp=now();await db.runTransaction(async function(tr){tr.set(claimRef,{status:'active',registered:true,applicationId:appId,approvedAt:stamp,registeredBy:u.uid,updatedAt:stamp},{merge:true});tr.set(appRef,{stage:'registered',creatorUid:uid,registeredAt:stamp},{merge:true});tr.set(db.collection('creatorEarnings').doc(uid),{registered:true,referralActive:false,tier:'applied',ratePct:25,verifiedSales:0,verifiedClicks:0,pendingCommission:0,approvedCommission:0,paidCommission:0,payoutStatus:'not scheduled',updatedAt:stamp},{merge:true})});await refresh()}catch(e){alert('Registration failed: '+(e.message||e));btn.disabled=false;btn.textContent='Register creator'}}
function reviewStatus(reviews,uid,id){var x=reviews[uid]&&reviews[uid].contentReviews;return x&&x[id]&&x[id].status||'submitted'}
function paintSubs(subs,reviews){var h=$('#caV4Content');if(!h)return;if(!subs.length){h.innerHTML='<div class="ca-empty">No v4 link submissions yet.</div>';return}subs.sort(function(a,b){return String(b.createdAt||'').localeCompare(String(a.createdAt||''))});h.innerHTML='<div class="ca-content-grid">'+subs.map(function(s){var status=reviewStatus(reviews,s.ownerUid,s.id);return'<article class="ca-content-card"><div class="ca-tags">'+tag(status,status==='approved'?'good':status==='rejected'?'bad':'warn')+tag(s.provider||'link')+tag(s.kind||'content')+'</div><h3>'+esc(s.title||'Untitled')+'</h3><p>'+esc([s.destination,s.ownerUid].filter(Boolean).join(' · '))+'</p><a href="'+esc(s.url||'#')+'" target="_blank" rel="noopener nofollow">Open source content ↗</a><div class="ca-actions">'+(status!=='approved'?'<button class="ca-action green" data-v4-review="approved|'+esc(s.ownerUid)+'|'+esc(s.id)+'">Approve + publish</button>':'')+(status!=='rejected'?'<button class="ca-action secondary" data-v4-review="rejected|'+esc(s.ownerUid)+'|'+esc(s.id)+'">Reject</button>':'')+'</div></article>'}).join('')+'</div>';document.querySelectorAll('[data-v4-review]').forEach(function(b){b.onclick=function(){var p=b.dataset.v4Review.split('|');review(p[1],p[2],p[0],b)}})}
async function review(uid,id,status,btn){var u=auth.currentUser;if(!(await adminOk(u)))return;btn.disabled=true;var subRef=db.collection('creatorContent').doc(uid).collection('submissions').doc(id),earnRef=db.collection('creatorEarnings').doc(uid),pubRef=db.collection('creatorShowcase').doc(uid).collection('posts').doc(id);try{var d=await subRef.get();if(!d.exists)throw new Error('Submission not found.');var s=d.data()||{},stamp=now(),r={status:status,note:status==='approved'?'Approved for the public RoamWise creator showcase.':'Not selected for public featuring.',reviewedAt:stamp,reviewedBy:u.uid};await earnRef.set({registered:true,updatedAt:stamp},{merge:true});var patch={};patch['contentReviews.'+id]=r;await earnRef.update(patch);await subRef.set({reviewStatus:status,updatedAt:stamp},{merge:true});if(status==='approved'){await pubRef.set({creatorUid:uid,sourceId:id,provider:String(s.provider||'').slice(0,30),kind:String(s.kind||'').slice(0,30),providerId:String(s.providerId||'').slice(0,200),title:String(s.title||'').slice(0,160),destination:String(s.destination||'').slice(0,100),url:String(s.url||'').slice(0,700),approvedAt:stamp},{merge:true})}else{try{await pubRef.delete()}catch(e){}}await refresh()}catch(e){alert('Review failed: '+(e.message||e));btn.disabled=false}}
function boot(){auth.onAuthStateChanged(async function(u){if(!(await adminOk(u)))return;var t=setInterval(function(){if(ensureShell()){clearInterval(t);refresh()}},250);setTimeout(function(){clearInterval(t)},10000)})}
boot();window.RWCreatorAdminV4={refresh:refresh,version:'4.0.0'};
})();
