/* RoamWise Creator Network Admin v1.1 — founder/admin only.
 * Applications are matched through creatorAccounts/{uid}, whose Firestore rule
 * binds email to Firebase Auth's verified email token. Editable users/{uid}
 * profile email is never trusted for referral/payout activation.
 */
(function(){'use strict';
var CFG={apiKey:'AIzaSyBTfmJvHTmp0mNQqsIhWEwnLLwFKz0ExYQ',authDomain:'roamwisepro.firebaseapp.com',projectId:'roamwisepro',storageBucket:'roamwisepro.firebasestorage.app',messagingSenderId:'1039880917656',appId:'1:1039880917656:web:8b3e18e8a4b1c9f8e2c0d1'};if(!firebase.apps.length)firebase.initializeApp(CFG);var auth=firebase.auth(),db=firebase.firestore(),S={user:null,apps:[],profiles:[],identities:[],ledger:{},refs:[],ledgerReadable:true,identityReadable:true};
var $=function(s,r){return(r||document).querySelector(s)},esc=function(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c})},now=function(){return new Date().toISOString()},money=function(n){return'₹'+Math.round(Number(n||0)).toLocaleString('en-IN')};
function m(text,bad){$('#caMsg').innerHTML='<div class="'+(bad?'ca-error':'ca-ok')+'">'+esc(text)+'</div>'}
function tag(t,k){return'<span class="ca-tag '+(k||'')+'">'+esc(t)+'</span>'}
function stat(k,v){return'<div class="ca-stat"><small>'+esc(k)+'</small><b>'+esc(v)+'</b></div>'}
function profile(uid){return S.profiles.find(function(x){return x.uid===uid})||null}
function identity(uid){return S.identities.find(function(x){return x.uid===uid})||null}
function ledger(uid){return S.ledger[uid]||null}
function cleanCodePart(v){return String(v||'CREATOR').toUpperCase().normalize('NFKD').replace(/[^A-Z0-9]+/g,'').slice(0,9)||'CREATOR'}
function makeCode(p){var uid=String(p.uid||'').replace(/[^A-Za-z0-9]/g,'').toUpperCase(),base=cleanCodePart(p.creator&&p.creator.displayName||identity(p.uid)&&identity(p.uid).email);return('RW-C-'+base+'-'+uid.slice(-5)).slice(0,32)}
function refForUid(uid){return S.refs.find(function(x){return x&&x.type==='creator'&&x.uid===uid})||null}
async function adminCheck(u){if(!u)return false;try{var d=await db.collection('admins').doc(u.uid).get();return d.exists}catch(e){return false}}
async function loadAll(){var apps=[],profiles=[],identities=[],refs=[];var aq=await db.collection('crm').where('seg','==','creator').limit(150).get();aq.forEach(function(d){var x=d.data()||{};x.id=d.id;apps.push(x)});var uq=await db.collection('users').where('creator.program','==','creator').limit(150).get();uq.forEach(function(d){var x=d.data()||{};profiles.push({uid:d.id,creator:x.creator||{},content:Array.isArray(x.creatorContent)?x.creatorContent:[]})});S.identityReadable=true;try{var iq=await db.collection('creatorAccounts').limit(200).get();iq.forEach(function(d){var x=d.data()||{};if(x.uid===d.id&&x.emailVerified===true)identities.push({uid:d.id,email:String(x.email||'').toLowerCase(),emailVerified:true})})}catch(e){S.identityReadable=false}try{var rd=await db.collection('config').doc('referrers').get();refs=rd.exists&&Array.isArray((rd.data()||{}).list)?rd.data().list:[]}catch(e){}S.ledger={};S.ledgerReadable=true;try{var lq=await db.collection('creatorEarnings').limit(200).get();lq.forEach(function(d){S.ledger[d.id]=d.data()||{}})}catch(e){S.ledgerReadable=false}S.apps=apps;S.profiles=profiles;S.identities=identities;S.refs=refs;paint()}
function paint(){var active=S.profiles.filter(function(p){return !!(ledger(p.uid)&&ledger(p.uid).referralCode)}).length,pending=S.apps.filter(function(a){return a.stage==='new'}).length,submits=0;S.profiles.forEach(function(p){submits+=p.content.length});$('#caStats').innerHTML=stat('New applications',pending)+stat('Verified Studio IDs',S.identities.length)+stat('Activated creators',active)+stat('Content pieces',submits);paintApps();paintCreators();paintContent();if(!S.identityReadable||!S.ledgerReadable)$('#caStats').insertAdjacentHTML('afterend','<div class="ca-error" style="margin-bottom:16px"><b>Creator security rules are not live yet.</b> '+(!S.identityReadable?'Verified creator identities cannot be read. ':'')+(!S.ledgerReadable?'Verified earnings cannot be read. ':'')+'Publish `CREATOR-STUDIO-RULES-PATCH.txt` before activating creators.</div>')}
function matchedIdentity(a){var e=String(a.email||'').trim().toLowerCase();return S.identities.find(function(i){return i.email===e})||null}
function paintApps(){var h=$('#caApps');if(!S.apps.length){h.innerHTML='<div class="ca-empty">No creator applications.</div>';return}h.innerHTML=S.apps.slice().sort(function(a,b){return String(b.createdAt||'').localeCompare(String(a.createdAt||''))}).map(function(a){var i=matchedIdentity(a),p=i&&profile(i.uid),isActive=i&&ledger(i.uid)&&ledger(i.uid).referralCode;return'<div class="ca-row"><div><h3>'+esc(a.name||a.email)+'</h3><p>'+esc([a.handle,a.reach,a.niche].filter(Boolean).join(' · '))+'</p><small>'+esc(a.email||'')+'</small><div class="ca-tags">'+tag(a.stage||'new',a.stage==='approved'?'good':'warn')+tag(i?'Email identity verified':'Waiting for verified email',i?'good':'warn')+tag(p?'Studio profile ready':'Profile incomplete',p?'good':'warn')+(isActive?tag('Code active','good'):'')+'</div></div><div class="ca-actions">'+(i&&p&&!isActive?'<button class="ca-action green" data-activate="'+p.uid+'" data-app="'+a.id+'">Activate creator</button>':'')+(i&&p&&isActive?'<button class="ca-action secondary" data-ledger="'+p.uid+'">Earnings</button>':'')+'</div></div>'}).join('');bindRows()}
function paintCreators(){var h=$('#caCreators');if(!S.profiles.length){h.innerHTML='<div class="ca-empty">No Creator Studio profiles yet.</div>';return}h.innerHTML=S.profiles.map(function(p){var c=p.creator||{},i=identity(p.uid),l=ledger(p.uid),r=refForUid(p.uid),code=l&&l.referralCode||r&&r.code||'',t=l&&l.tier||'applied';return'<div class="ca-row"><div><h3>'+esc(c.displayName||i&&i.email||p.uid)+'</h3><p>'+esc([c.niche,i&&i.email].filter(Boolean).join(' · '))+'</p><small>'+esc(code||'Referral code not activated')+'</small><div class="ca-tags">'+tag(i?'Verified identity':'Unverified identity',i?'good':'warn')+tag(t,code?'good':'warn')+(code?tag((l&&l.ratePct||25)+'%','good'):'')+tag(p.content.length+' content')+'</div></div><div class="ca-actions">'+(i&&!code?'<button class="ca-action green" data-activate="'+p.uid+'">Activate</button>':'')+(code?'<button class="ca-action secondary" data-ledger="'+p.uid+'">Earnings</button><button class="ca-action gold" data-tier="'+p.uid+'|featured">Featured</button>':'')+'</div></div>'}).join('');bindRows()}
function contentStatus(uid,id){var l=ledger(uid),r=l&&l.contentReviews&&l.contentReviews[id];return r&&r.status||'submitted'}
function paintContent(){var arr=[];S.profiles.forEach(function(p){p.content.forEach(function(c){arr.push({p:p,c:c,status:contentStatus(p.uid,c.id)})})});var h=$('#caContent');if(!arr.length){h.innerHTML='<div class="ca-empty">No content submitted yet.</div>';return}h.innerHTML='<div class="ca-content-grid">'+arr.sort(function(a,b){return String(b.c.createdAt||'').localeCompare(String(a.c.createdAt||''))}).map(function(x){var c=x.c,p=x.p,i=identity(p.uid);return'<article class="ca-content-card"><div class="ca-tags">'+tag(x.status,x.status==='approved'?'good':x.status==='rejected'?'bad':'warn')+tag(c.type||'content')+tag(i?'verified creator':'identity pending',i?'good':'warn')+'</div><h3>'+esc(c.title||'Untitled')+'</h3><p>'+esc((p.creator&&p.creator.displayName)||i&&i.email||p.uid)+' · '+esc(c.destination||'')+'</p>'+(c.url?'<a href="'+esc(c.url)+'" target="_blank" rel="noopener">Open content ↗</a>':'')+'<div class="ca-actions">'+(ledger(p.uid)&&x.status!=='approved'?'<button class="ca-action green" data-review="'+p.uid+'|'+c.id+'|approved">Approve</button>':'')+(ledger(p.uid)&&x.status!=='rejected'?'<button class="ca-action secondary" data-review="'+p.uid+'|'+c.id+'|rejected">Reject</button>':'')+'</div></article>'}).join('')+'</div>';bindRows()}
function bindRows(){document.querySelectorAll('[data-activate]').forEach(function(b){b.onclick=function(){activate(b.dataset.activate,b.dataset.app||'')}});document.querySelectorAll('[data-ledger]').forEach(function(b){b.onclick=function(){openLedger(b.dataset.ledger)}});document.querySelectorAll('[data-tier]').forEach(function(b){b.onclick=function(){var x=b.dataset.tier.split('|');setTier(x[0],x[1])}});document.querySelectorAll('[data-review]').forEach(function(b){b.onclick=function(){var x=b.dataset.review.split('|');reviewContent(x[0],x[1],x[2])}})}
async function syncReferrer(tr,uid,nextLedger,refsRef){var rd=await tr.get(refsRef),list=rd.exists&&Array.isArray((rd.data()||{}).list)?(rd.data().list||[]):[],p=profile(uid),i=identity(uid),name=p&&p.creator&&p.creator.displayName||i&&i.email||'RoamWise Creator',code=nextLedger.referralCode;list=list.filter(function(x){return !(x&&x.type==='creator'&&(x.uid===uid||x.code===code))});if(nextLedger.referralActive!==false)list.push({code:code,name:name,type:'creator',rate:Number(nextLedger.ratePct||25)/100,active:true,uid:uid,email:i&&i.email||'',note:'Creator Studio · '+String(nextLedger.tier||'applied')});tr.set(refsRef,{list:list,updatedAt:now()},{merge:true})}
async function activate(uid,appId){var p=profile(uid),i=identity(uid);if(!p)return alert('Creator profile not found.');if(!i||!i.emailVerified)return alert('Activation blocked: this Studio account has no Firebase-verified creator identity.');var a=appId?S.apps.find(function(x){return x.id===appId}):null;if(a&&String(a.email||'').trim().toLowerCase()!==i.email)return alert('Activation blocked: application email does not match the verified Firebase identity.');var earnRef=db.collection('creatorEarnings').doc(uid),refsRef=db.collection('config').doc('referrers'),appRef=a?db.collection('crm').doc(a.id):null;try{await db.runTransaction(async function(tr){var ed=await tr.get(earnRef),prev=ed.exists?(ed.data()||{}):{},code=prev.referralCode||makeCode(p),t=prev.tier||'applied',next=Object.assign({verifiedSales:0,verifiedClicks:0,pendingCommission:0,approvedCommission:0,paidCommission:0,payoutStatus:'not scheduled',contentReviews:{}},prev,{creatorName:p.creator.displayName||i.email,email:i.email,referralCode:code,referralActive:true,tier:t,ratePct:t==='applied'?25:30,activatedAt:prev.activatedAt||now(),lastReconciledAt:prev.lastReconciledAt||now()});await syncReferrer(tr,uid,next,refsRef);tr.set(earnRef,next,{merge:true});if(appRef)tr.set(appRef,{stage:'approved',tier:t,code:code,approvedAt:now(),creatorUid:uid},{merge:true})});await loadAll();alert('Creator activated. Their verified code is now in config/referrers.')}catch(e){alert('Activation failed: '+e.message+'\n\nIf this says permission denied, publish the Creator Studio Firestore rules patch first.')}}
async function setTier(uid,t){if(!/^(applied|partner|featured)$/.test(t)||!identity(uid))return;var earnRef=db.collection('creatorEarnings').doc(uid),refsRef=db.collection('config').doc('referrers');try{await db.runTransaction(async function(tr){var ed=await tr.get(earnRef);if(!ed.exists)throw new Error('Activate this creator first.');var next=Object.assign({},ed.data()||{},{tier:t,ratePct:t==='applied'?25:30,lastReconciledAt:now()});await syncReferrer(tr,uid,next,refsRef);tr.set(earnRef,{tier:t,ratePct:next.ratePct,lastReconciledAt:now()},{merge:true})});await loadAll()}catch(e){alert('Tier update failed: '+e.message)}}
async function reviewContent(uid,id,status){var l=ledger(uid);if(!l||!l.referralCode)return alert('Activate the verified creator before reviewing content.');var ref=db.collection('creatorEarnings').doc(uid),patch={};patch['contentReviews.'+id]={status:status,note:status==='approved'?'Approved for RoamWise creator portfolio':'Not selected for featuring yet',reviewedAt:now()};try{await ref.update(patch);if(status==='approved'&&(l.tier||'applied')==='applied')await setTier(uid,'partner');else await loadAll()}catch(e){alert('Review failed: '+e.message)}}
function openLedger(uid){var p=profile(uid),i=identity(uid),l=ledger(uid)||{};if(!p||!i)return;var b=$('#caModalBox');b.innerHTML='<div class="cs-modal-head"><div><small class="cs-kicker">VERIFIED LEDGER</small><h2>'+esc(p.creator.displayName||i.email)+'</h2></div><button id="caClose">×</button></div><div class="ca-modal-note">Identity: <b>'+esc(i.email)+'</b> · Firebase verified. These money/tier fields are admin-owned; Creator Studio can only read them.</div><div class="ca-edit"><label>Verified sales<input id="leSales" type="number" min="0" value="'+Number(l.verifiedSales||0)+'"></label><label>Verified clicks<input id="leClicks" type="number" min="0" value="'+Number(l.verifiedClicks||0)+'"></label><label>Pending commission<input id="lePending" type="number" min="0" value="'+Number(l.pendingCommission||0)+'"></label><label>Approved commission<input id="leApproved" type="number" min="0" value="'+Number(l.approvedCommission||0)+'"></label><label>Paid commission<input id="lePaid" type="number" min="0" value="'+Number(l.paidCommission||0)+'"></label><label>Payout status<select id="lePayout"><option>not scheduled</option><option>pending</option><option>approved</option><option>paid</option><option>on hold</option></select></label><label>Tier<select id="leTier"><option value="applied">Applied · 25%</option><option value="partner">Partner · 30%</option><option value="featured">Featured · 30%</option></select></label><label>Referral active<select id="leActive"><option value="yes">Active</option><option value="no">Paused</option></select></label></div><button class="ca-save" id="leSave">Save verified ledger</button><div id="leMsg"></div>';$('#caModal').classList.add('open');$('#caClose').onclick=closeModal;$('#lePayout').value=l.payoutStatus||'not scheduled';$('#leTier').value=l.tier||'applied';$('#leActive').value=l.referralActive===false?'no':'yes';$('#leSave').onclick=function(){saveLedger(uid)}}
function closeModal(){$('#caModal').classList.remove('open')}
async function saveLedger(uid){var p=profile(uid),i=identity(uid),old=ledger(uid)||{};if(!p||!i)return;var sales=Math.max(0,Number($('#leSales').value||0)),chosen=$('#leTier').value,auto=sales>=25?'featured':sales>=5&&chosen==='applied'?'partner':chosen,t=auto,active=$('#leActive').value==='yes',next=Object.assign({},old,{creatorName:p.creator.displayName||i.email,email:i.email,referralCode:old.referralCode||makeCode(p),referralActive:active,tier:t,ratePct:t==='applied'?25:30,verifiedSales:sales,verifiedClicks:Math.max(0,Number($('#leClicks').value||0)),pendingCommission:Math.max(0,Number($('#lePending').value||0)),approvedCommission:Math.max(0,Number($('#leApproved').value||0)),paidCommission:Math.max(0,Number($('#lePaid').value||0)),payoutStatus:$('#lePayout').value,lastReconciledAt:now()});var earnRef=db.collection('creatorEarnings').doc(uid),refsRef=db.collection('config').doc('referrers');try{await db.runTransaction(async function(tr){await syncReferrer(tr,uid,next,refsRef);tr.set(earnRef,next,{merge:true})});closeModal();await loadAll()}catch(e){$('#leMsg').innerHTML='<div class="ca-error">'+esc(e.message)+'</div>'}}
async function login(){var e=$('#caEmail').value.trim(),p=$('#caPass').value;if(!e||!p)return m('Enter email and password.',true);try{await auth.signInWithEmailAndPassword(e,p)}catch(x){m(x.message||'Sign in failed.',true)}}
$('#caLogin').onclick=login;$('#caSignOut').onclick=function(){auth.signOut()};$('#caRefresh').onclick=loadAll;$('#caModal').onclick=function(e){if(e.target===this)closeModal()};auth.onAuthStateChanged(async function(u){S.user=u||null;if(!u){$('#caAuth').hidden=false;$('#caDash').hidden=true;$('#caSignOut').hidden=true;return}var ok=await adminCheck(u);if(!ok){await auth.signOut();m('This account is not a RoamWise admin.',true);return}$('#caAuth').hidden=true;$('#caDash').hidden=false;$('#caSignOut').hidden=false;$('#caWho').textContent=u.email||u.uid;loadAll().catch(function(e){alert('Could not load Creator Network admin: '+e.message)})});
window.RWCreatorAdmin={version:'1.1.0'};
})();
