/* RoamWise Creator Network Admin — canonical runtime.
 * Consolidates the former admin.js + admin-v4.js into one Firebase/auth/data lifecycle.
 */
(function(){'use strict';
var CFG={apiKey:'AIzaSyBTfmJvHTmp0mNQqsIhWEwnLLwFKz0ExYQ',authDomain:'roamwisepro.firebaseapp.com',projectId:'roamwisepro',storageBucket:'roamwisepro.firebasestorage.app',messagingSenderId:'1039880917656',appId:'1:1039880917656:web:8b3e18e8a4b1c9f8e2c0d1'};
if(!firebase.apps.length)firebase.initializeApp(CFG);
var auth=firebase.auth(),db=firebase.firestore(),busy=false;
var S={user:null,apps:[],profiles:[],identities:[],claims:[],ledger:{},refs:[],submissions:[],ledgerReadable:true,identityReadable:true};
var $=function(s,r){return(r||document).querySelector(s)},$$=function(s,r){return Array.from((r||document).querySelectorAll(s))};
var esc=function(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c})};
var now=function(){return new Date().toISOString()},money=function(n){return'₹'+Math.round(Number(n||0)).toLocaleString('en-IN')};
function msg(text,bad){$('#caMsg').innerHTML='<div class="'+(bad?'ca-error':'ca-ok')+'">'+esc(text)+'</div>'}
function tag(t,k){return'<span class="ca-tag '+(k||'')+'">'+esc(t)+'</span>'}
function stat(k,v){return'<div class="ca-stat"><small>'+esc(k)+'</small><b>'+esc(v)+'</b></div>'}
function profile(uid){return S.profiles.find(function(x){return x.uid===uid})||null}
function identity(uid){return S.identities.find(function(x){return x.uid===uid})||null}
function claim(uid){return S.claims.find(function(x){return x.uid===uid})||null}
function ledger(uid){return S.ledger[uid]||null}
function appForEmail(email){email=String(email||'').trim().toLowerCase();return S.apps.find(function(a){return String(a.email||'').trim().toLowerCase()===email})||null}
function matchedIdentity(app){return S.identities.find(function(i){return i.email===String(app.email||'').trim().toLowerCase()})||null}
function cleanCodePart(v){return String(v||'CREATOR').toUpperCase().normalize('NFKD').replace(/[^A-Z0-9]+/g,'').slice(0,9)||'CREATOR'}
function makeCode(p){var uid=String(p.uid||'').replace(/[^A-Za-z0-9]/g,'').toUpperCase(),base=cleanCodePart(p.creator&&p.creator.displayName||identity(p.uid)&&identity(p.uid).email);return('RW-C-'+base+'-'+uid.slice(-5)).slice(0,32)}
function refForUid(uid){return S.refs.find(function(x){return x&&x.type==='creator'&&x.uid===uid})||null}
async function adminCheck(u){if(!u||!u.emailVerified)return false;try{return(await db.collection('admins').doc(u.uid).get()).exists}catch(e){return false}}

async function loadAll(){
  if(busy)return;busy=true;
  try{
    var apps=[],profiles=[],identities=[],claims=[],refs=[],subs=[];
    var results=await Promise.all([
      db.collection('crm').where('seg','==','creator').limit(250).get(),
      db.collection('users').where('creator.program','==','creator').limit(250).get(),
      db.collection('creatorAccounts').limit(250).get().catch(function(){return null}),
      db.collection('config').doc('referrers').get().catch(function(){return null}),
      db.collection('creatorEarnings').limit(250).get().catch(function(){return null}),
      db.collectionGroup('submissions').limit(250).get().catch(function(){return null})
    ]);
    results[0].forEach(function(d){var x=d.data()||{};x.id=d.id;apps.push(x)});
    results[1].forEach(function(d){var x=d.data()||{};profiles.push({uid:d.id,creator:x.creator||{},content:Array.isArray(x.creatorContent)?x.creatorContent:[]})});
    S.identityReadable=!!results[2];if(results[2])results[2].forEach(function(d){var x=d.data()||{};x.uid=d.id;claims.push(x);if(x.uid===d.id&&x.emailVerified===true)identities.push({uid:d.id,email:String(x.email||'').toLowerCase(),emailVerified:true,registered:x.registered===true,status:x.status||''})});
    if(results[3]&&results[3].exists)refs=Array.isArray((results[3].data()||{}).list)?results[3].data().list:[];
    S.ledger={};S.ledgerReadable=!!results[4];if(results[4])results[4].forEach(function(d){S.ledger[d.id]=d.data()||{}});
    if(results[5])results[5].forEach(function(d){var x=d.data()||{};x.id=d.id;x.ownerUid=x.ownerUid||((d.ref.parent&&d.ref.parent.parent&&d.ref.parent.parent.id)||'');subs.push(x)});
    S.apps=apps;S.profiles=profiles;S.identities=identities;S.claims=claims;S.refs=refs;S.submissions=subs;paint();
  }finally{busy=false}
}
function ensureExtendedShell(){if($('#caUnified'))return;var dash=$('#caDash');if(!dash||dash.hidden)return;var s=document.createElement('section');s.id='caUnified';s.innerHTML='<section class="ca-panel"><div class="ca-head"><div><small>REGISTRATION GATE</small><h2>Verified identity claims</h2><p>Only an admin can convert a verified Firebase identity claim into a registered Creator Studio account.</p></div></div><div id="caClaims"></div></section><section class="ca-panel"><div class="ca-head"><div><small>LINK-FIRST CONTENT</small><h2>Creator submission queue</h2><p>RoamWise stores URLs and metadata; source platforms remain the media host.</p></div></div><div id="caSubmissions"></div></section>';dash.appendChild(s)}
function paint(){
  ensureExtendedShell();var active=S.profiles.filter(function(p){return!!(ledger(p.uid)&&ledger(p.uid).referralCode)}).length,pending=S.apps.filter(function(a){return a.stage==='new'}).length,content=S.profiles.reduce(function(n,p){return n+p.content.length},0);
  $('#caStats').innerHTML=stat('New applications',pending)+stat('Verified identities',S.identities.length)+stat('Activated creators',active)+stat('Content pieces',content+S.submissions.length);
  paintApps();paintCreators();paintLegacyContent();paintClaims();paintSubmissions();
  if(!S.identityReadable||!S.ledgerReadable)$('#caStats').insertAdjacentHTML('afterend','<div class="ca-error" id="caRulesWarn" style="margin-bottom:16px"><b>Creator security collections are not fully readable.</b> Publish the current Creator Studio Firestore rules before activating or paying creators.</div>')
}
function paintApps(){var h=$('#caApps');if(!S.apps.length){h.innerHTML='<div class="ca-empty">No creator applications.</div>';return}h.innerHTML=S.apps.slice().sort(function(a,b){return String(b.createdAt||'').localeCompare(String(a.createdAt||''))}).map(function(a){var i=matchedIdentity(a),p=i&&profile(i.uid),l=i&&ledger(i.uid),active=!!(l&&l.referralCode);return'<div class="ca-row"><div><h3>'+esc(a.name||a.email)+'</h3><p>'+esc([a.handle,a.reach,a.niche].filter(Boolean).join(' · '))+'</p><small>'+esc(a.email||'')+'</small><div class="ca-tags">'+tag(a.stage||'new',a.stage==='approved'||a.stage==='registered'?'good':'warn')+tag(i?'Email identity verified':'Waiting for verified email',i?'good':'warn')+tag(p?'Studio profile ready':'Profile incomplete',p?'good':'warn')+(active?tag('Code active','good'):'')+'</div></div><div class="ca-actions">'+(i&&p&&!active?'<button class="ca-action green" data-activate="'+p.uid+'" data-app="'+a.id+'">Activate creator</button>':'')+(active?'<button class="ca-action secondary" data-ledger="'+i.uid+'">Earnings</button>':'')+'</div></div>'}).join('');bindActions()}
function paintCreators(){var h=$('#caCreators');if(!S.profiles.length){h.innerHTML='<div class="ca-empty">No Creator Studio profiles yet.</div>';return}h.innerHTML=S.profiles.map(function(p){var c=p.creator||{},i=identity(p.uid),l=ledger(p.uid),r=refForUid(p.uid),code=l&&l.referralCode||r&&r.code||'',tier=l&&l.tier||'applied';return'<div class="ca-row"><div><h3>'+esc(c.displayName||i&&i.email||p.uid)+'</h3><p>'+esc([c.niche,i&&i.email].filter(Boolean).join(' · '))+'</p><small>'+esc(code||'Referral code not activated')+'</small><div class="ca-tags">'+tag(i?'Verified identity':'Unverified identity',i?'good':'warn')+tag(tier,code?'good':'warn')+(code?tag((l&&l.ratePct||25)+'%','good'):'')+tag(p.content.length+' legacy content')+'</div></div><div class="ca-actions">'+(i&&!code?'<button class="ca-action green" data-activate="'+p.uid+'">Activate</button>':'')+(code?'<button class="ca-action secondary" data-ledger="'+p.uid+'">Earnings</button><button class="ca-action gold" data-tier="'+p.uid+'|featured">Featured</button>':'')+'</div></div>'}).join('');bindActions()}
function reviewStatus(uid,id){var x=ledger(uid)&&ledger(uid).contentReviews;return x&&x[id]&&x[id].status||'submitted'}
function paintLegacyContent(){var a=[];S.profiles.forEach(function(p){p.content.forEach(function(c){a.push({p:p,c:c,status:reviewStatus(p.uid,c.id)})})});var h=$('#caContent');if(!a.length){h.innerHTML='<div class="ca-empty">No legacy content submitted.</div>';return}h.innerHTML='<div class="ca-content-grid">'+a.sort(function(x,y){return String(y.c.createdAt||'').localeCompare(String(x.c.createdAt||''))}).map(function(x){var p=x.p,c=x.c,i=identity(p.uid);return'<article class="ca-content-card"><div class="ca-tags">'+tag(x.status,x.status==='approved'?'good':x.status==='rejected'?'bad':'warn')+tag(c.type||'content')+tag(i?'verified creator':'identity pending',i?'good':'warn')+'</div><h3>'+esc(c.title||'Untitled')+'</h3><p>'+esc((p.creator&&p.creator.displayName)||i&&i.email||p.uid)+' · '+esc(c.destination||'')+'</p>'+(c.url?'<a href="'+esc(c.url)+'" target="_blank" rel="noopener">Open content ↗</a>':'')+'<div class="ca-actions">'+(ledger(p.uid)&&x.status!=='approved'?'<button class="ca-action green" data-review="'+p.uid+'|'+c.id+'|approved">Approve</button>':'')+(ledger(p.uid)&&x.status!=='rejected'?'<button class="ca-action secondary" data-review="'+p.uid+'|'+c.id+'|rejected">Reject</button>':'')+'</div></article>'}).join('')+'</div>';bindActions()}
function paintClaims(){var h=$('#caClaims');if(!h)return;if(!S.claims.length){h.innerHTML='<div class="ca-empty">No creator identity claims yet.</div>';return}h.innerHTML=S.claims.slice().sort(function(a,b){return String(b.createdAt||'').localeCompare(String(a.createdAt||''))}).map(function(c){var a=appForEmail(c.email),registered=c.registered===true&&c.status==='active';return'<div class="ca-row"><div><h3>'+esc(c.email||c.uid)+'</h3><p>'+esc(a?[a.name,a.handle,a.niche].filter(Boolean).join(' · '):'No matching application')+'</p><small>UID '+esc(c.uid)+'</small><div class="ca-tags">'+tag(c.emailVerified===true?'Firebase email verified':'email claim incomplete',c.emailVerified===true?'good':'bad')+tag(a?'application matched':'application missing',a?'good':'warn')+tag(registered?'registered':'not registered',registered?'good':'warn')+'</div></div><div class="ca-actions">'+(!registered&&a&&c.emailVerified===true?'<button class="ca-action green" data-register="'+c.uid+'|'+a.id+'">Register creator</button>':'')+'</div></div>'}).join('');bindActions()}
function paintSubmissions(){var h=$('#caSubmissions');if(!h)return;if(!S.submissions.length){h.innerHTML='<div class="ca-empty">No link submissions yet.</div>';return}h.innerHTML='<div class="ca-content-grid">'+S.submissions.slice().sort(function(a,b){return String(b.createdAt||'').localeCompare(String(a.createdAt||''))}).map(function(s){var st=reviewStatus(s.ownerUid,s.id);return'<article class="ca-content-card"><div class="ca-tags">'+tag(st,st==='approved'?'good':st==='rejected'?'bad':'warn')+tag(s.provider||'link')+tag(s.kind||'content')+'</div><h3>'+esc(s.title||'Untitled')+'</h3><p>'+esc([s.destination,s.ownerUid].filter(Boolean).join(' · '))+'</p>'+(s.url?'<a href="'+esc(s.url)+'" target="_blank" rel="noopener nofollow">Open source content ↗</a>':'')+'<div class="ca-actions">'+(st!=='approved'?'<button class="ca-action green" data-sub-review="'+s.ownerUid+'|'+s.id+'|approved">Approve + publish</button>':'')+(st!=='rejected'?'<button class="ca-action secondary" data-sub-review="'+s.ownerUid+'|'+s.id+'|rejected">Reject</button>':'')+'</div></article>'}).join('')+'</div>';bindActions()}
function bindActions(){$$('[data-activate]').forEach(function(b){b.onclick=function(){activate(b.dataset.activate,b.dataset.app||'')}});$$('[data-ledger]').forEach(function(b){b.onclick=function(){openLedger(b.dataset.ledger)}});$$('[data-tier]').forEach(function(b){b.onclick=function(){var x=b.dataset.tier.split('|');setTier(x[0],x[1])}});$$('[data-review]').forEach(function(b){b.onclick=function(){var x=b.dataset.review.split('|');reviewLegacy(x[0],x[1],x[2])}});$$('[data-register]').forEach(function(b){b.onclick=function(){var x=b.dataset.register.split('|');registerCreator(x[0],x[1],b)}});$$('[data-sub-review]').forEach(function(b){b.onclick=function(){var x=b.dataset.subReview.split('|');reviewSubmission(x[0],x[1],x[2],b)}})}
async function syncReferrer(tr,uid,next,refsRef){var rd=await tr.get(refsRef),list=rd.exists&&Array.isArray((rd.data()||{}).list)?rd.data().list:[],p=profile(uid),i=identity(uid),name=p&&p.creator&&p.creator.displayName||i&&i.email||'RoamWise Creator',code=next.referralCode;list=list.filter(function(x){return!(x&&x.type==='creator'&&(x.uid===uid||x.code===code))});if(next.referralActive!==false)list.push({code:code,name:name,type:'creator',rate:Number(next.ratePct||25)/100,active:true,uid:uid,email:i&&i.email||'',note:'Creator Studio · '+String(next.tier||'applied')});tr.set(refsRef,{list:list,updatedAt:now()},{merge:true})}
async function activate(uid,appId){var p=profile(uid),i=identity(uid);if(!p)return alert('Creator profile not found.');if(!i||!i.emailVerified)return alert('Activation blocked: no Firebase-verified creator identity.');var a=appId?S.apps.find(function(x){return x.id===appId}):null;if(a&&String(a.email||'').trim().toLowerCase()!==i.email)return alert('Application email does not match the verified identity.');var earnRef=db.collection('creatorEarnings').doc(uid),refsRef=db.collection('config').doc('referrers'),appRef=a?db.collection('crm').doc(a.id):null;try{await db.runTransaction(async function(tr){var ed=await tr.get(earnRef),prev=ed.exists?(ed.data()||{}):{},code=prev.referralCode||makeCode(p),tier=prev.tier||'applied',next=Object.assign({verifiedSales:0,verifiedClicks:0,pendingCommission:0,approvedCommission:0,paidCommission:0,payoutStatus:'not scheduled',contentReviews:{}},prev,{creatorName:p.creator.displayName||i.email,email:i.email,referralCode:code,referralActive:true,tier:tier,ratePct:tier==='applied'?25:30,activatedAt:prev.activatedAt||now(),lastReconciledAt:now()});await syncReferrer(tr,uid,next,refsRef);tr.set(earnRef,next,{merge:true});if(appRef)tr.set(appRef,{stage:'approved',tier:tier,code:code,approvedAt:now(),creatorUid:uid},{merge:true})});await loadAll()}catch(e){alert('Activation failed: '+e.message)}}
async function registerCreator(uid,appId,btn){var u=auth.currentUser;if(!(await adminCheck(u)))return;btn.disabled=true;try{var claimRef=db.collection('creatorAccounts').doc(uid),appRef=db.collection('crm').doc(appId),cDoc=await claimRef.get(),aDoc=await appRef.get();if(!cDoc.exists||!aDoc.exists)throw Error('Claim or application not found.');var c=cDoc.data()||{},a=aDoc.data()||{};if(c.emailVerified!==true)throw Error('Verified Firebase identity is required.');if(String(c.email||'').trim().toLowerCase()!==String(a.email||'').trim().toLowerCase())throw Error('Application email does not match the verified claim.');var stamp=now();await db.runTransaction(async function(tr){tr.set(claimRef,{status:'active',registered:true,applicationId:appId,approvedAt:stamp,registeredBy:u.uid,updatedAt:stamp},{merge:true});tr.set(appRef,{stage:'registered',creatorUid:uid,registeredAt:stamp},{merge:true});tr.set(db.collection('creatorEarnings').doc(uid),{registered:true,referralActive:false,tier:'applied',ratePct:25,verifiedSales:0,verifiedClicks:0,pendingCommission:0,approvedCommission:0,paidCommission:0,payoutStatus:'not scheduled',updatedAt:stamp},{merge:true})});await loadAll()}catch(e){alert('Registration failed: '+(e.message||e));btn.disabled=false}}
async function setTier(uid,tier){if(!/^(applied|partner|featured)$/.test(tier)||!identity(uid))return;var earnRef=db.collection('creatorEarnings').doc(uid),refsRef=db.collection('config').doc('referrers');try{await db.runTransaction(async function(tr){var d=await tr.get(earnRef);if(!d.exists)throw Error('Activate this creator first.');var next=Object.assign({},d.data()||{},{tier:tier,ratePct:tier==='applied'?25:30,lastReconciledAt:now()});await syncReferrer(tr,uid,next,refsRef);tr.set(earnRef,{tier:tier,ratePct:next.ratePct,lastReconciledAt:now()},{merge:true})});await loadAll()}catch(e){alert('Tier update failed: '+e.message)}}
async function reviewLegacy(uid,id,status){var l=ledger(uid);if(!l||!l.referralCode)return alert('Activate the creator before reviewing content.');var patch={};patch['contentReviews.'+id]={status:status,note:status==='approved'?'Approved for RoamWise creator portfolio':'Not selected for featuring yet',reviewedAt:now(),reviewedBy:S.user.uid};try{await db.collection('creatorEarnings').doc(uid).update(patch);await loadAll()}catch(e){alert('Review failed: '+e.message)}}
async function reviewSubmission(uid,id,status,btn){var u=auth.currentUser;if(!(await adminCheck(u)))return;btn.disabled=true;var subRef=db.collection('creatorContent').doc(uid).collection('submissions').doc(id),earnRef=db.collection('creatorEarnings').doc(uid),pubRef=db.collection('creatorShowcase').doc(uid).collection('posts').doc(id);try{var d=await subRef.get();if(!d.exists)throw Error('Submission not found.');var s=d.data()||{},stamp=now(),r={status:status,note:status==='approved'?'Approved for the public RoamWise creator showcase.':'Not selected for public featuring.',reviewedAt:stamp,reviewedBy:u.uid};await earnRef.set({registered:true,updatedAt:stamp},{merge:true});var patch={};patch['contentReviews.'+id]=r;await earnRef.update(patch);await subRef.set({reviewStatus:status,updatedAt:stamp},{merge:true});if(status==='approved')await pubRef.set({creatorUid:uid,sourceId:id,provider:String(s.provider||'').slice(0,30),kind:String(s.kind||'').slice(0,30),providerId:String(s.providerId||'').slice(0,200),title:String(s.title||'').slice(0,160),destination:String(s.destination||'').slice(0,100),url:String(s.url||'').slice(0,700),approvedAt:stamp},{merge:true});else try{await pubRef.delete()}catch(e){}await loadAll()}catch(e){alert('Review failed: '+(e.message||e));btn.disabled=false}}
function openLedger(uid){var p=profile(uid),i=identity(uid),l=ledger(uid)||{};if(!p||!i)return;var b=$('#caModalBox');b.innerHTML='<div class="cs-modal-head"><div><small class="cs-kicker">VERIFIED LEDGER</small><h2>'+esc(p.creator.displayName||i.email)+'</h2></div><button id="caClose">×</button></div><div class="ca-modal-note">Identity: <b>'+esc(i.email)+'</b> · Firebase verified. Money/tier fields are admin-owned.</div><div class="ca-edit"><label>Verified sales<input id="leSales" type="number" min="0" value="'+Number(l.verifiedSales||0)+'"></label><label>Verified clicks<input id="leClicks" type="number" min="0" value="'+Number(l.verifiedClicks||0)+'"></label><label>Pending commission<input id="lePending" type="number" min="0" value="'+Number(l.pendingCommission||0)+'"></label><label>Approved commission<input id="leApproved" type="number" min="0" value="'+Number(l.approvedCommission||0)+'"></label><label>Paid commission<input id="lePaid" type="number" min="0" value="'+Number(l.paidCommission||0)+'"></label><label>Payout status<select id="lePayout"><option>not scheduled</option><option>pending</option><option>approved</option><option>paid</option><option>on hold</option></select></label><label>Tier<select id="leTier"><option value="applied">Applied · 25%</option><option value="partner">Partner · 30%</option><option value="featured">Featured · 30%</option></select></label><label>Referral active<select id="leActive"><option value="yes">Active</option><option value="no">Paused</option></select></label></div><button class="ca-save" id="leSave">Save verified ledger</button><div id="leMsg"></div>';$('#caModal').classList.add('open');$('#caClose').onclick=closeModal;$('#lePayout').value=l.payoutStatus||'not scheduled';$('#leTier').value=l.tier||'applied';$('#leActive').value=l.referralActive===false?'no':'yes';$('#leSave').onclick=function(){saveLedger(uid)}}
function closeModal(){$('#caModal').classList.remove('open')}
async function saveLedger(uid){var p=profile(uid),i=identity(uid),old=ledger(uid)||{};if(!p||!i)return;var sales=Math.max(0,Number($('#leSales').value||0)),chosen=$('#leTier').value,tier=sales>=25?'featured':sales>=5&&chosen==='applied'?'partner':chosen,active=$('#leActive').value==='yes',next=Object.assign({},old,{creatorName:p.creator.displayName||i.email,email:i.email,referralCode:old.referralCode||makeCode(p),referralActive:active,tier:tier,ratePct:tier==='applied'?25:30,verifiedSales:sales,verifiedClicks:Math.max(0,Number($('#leClicks').value||0)),pendingCommission:Math.max(0,Number($('#lePending').value||0)),approvedCommission:Math.max(0,Number($('#leApproved').value||0)),paidCommission:Math.max(0,Number($('#lePaid').value||0)),payoutStatus:$('#lePayout').value,lastReconciledAt:now()});var earnRef=db.collection('creatorEarnings').doc(uid),refsRef=db.collection('config').doc('referrers');try{await db.runTransaction(async function(tr){await syncReferrer(tr,uid,next,refsRef);tr.set(earnRef,next,{merge:true})});closeModal();await loadAll()}catch(e){$('#leMsg').innerHTML='<div class="ca-error">'+esc(e.message)+'</div>'}}
async function login(){var email=$('#caEmail').value.trim(),pass=$('#caPass').value;if(!email||!pass)return msg('Enter email and password.',true);try{await auth.signInWithEmailAndPassword(email,pass)}catch(e){msg(e.message||'Sign in failed.',true)}}
$('#caLogin').onclick=login;$('#caSignOut').onclick=function(){auth.signOut()};$('#caRefresh').onclick=loadAll;$('#caModal').onclick=function(e){if(e.target===this)closeModal()};
auth.onAuthStateChanged(async function(u){S.user=u||null;if(!u){$('#caAuth').hidden=false;$('#caDash').hidden=true;$('#caSignOut').hidden=true;return}var ok=await adminCheck(u);if(!ok){await auth.signOut();msg('This account must be a verified RoamWise admin.',true);return}$('#caAuth').hidden=true;$('#caDash').hidden=false;$('#caSignOut').hidden=false;$('#caWho').textContent=u.email||u.uid;loadAll().catch(function(e){alert('Could not load Creator Network admin: '+e.message)})});
window.RWCreatorAdmin={version:'5.0.0-canonical',refresh:loadAll};
})();
