(function () {
  'use strict';
  var CFG={apiKey:'AIzaSyBTfmJvHTmp0mNQqsIhWEwnLLwFKz0ExYQ',authDomain:'roamwisepro.firebaseapp.com',projectId:'roamwisepro',storageBucket:'roamwisepro.firebasestorage.app',messagingSenderId:'1039880917656',appId:'1:1039880917656:web:8b3e18e8a4b1c9f8e2c0d1'};
  if (!firebase.apps.length) firebase.initializeApp(CFG);
  var auth=firebase.auth(),actor=null,campaigns=[],$=function(s){return document.querySelector(s)},apiBase=function(){return String(window.RW_CONFIG&&window.RW_CONFIG.creatorProtectionUrl||'').replace(/\/+$/,'')};
  var esc=function(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})};
  var money=function(minor){return'₹'+Math.round(Number(minor||0)/100).toLocaleString('en-IN')};
  var rupees=function(s){return Math.max(0,Math.round(Number($(s).value||0)))};
  function message(selector,text,bad){$(selector).innerHTML='<div class="cp-message'+(bad?' bad':'')+'">'+esc(text)+'</div>'}
  async function call(path,options){if(!apiBase())throw Error('Protected campaign API is not activated yet. You can preview the workflow, but no money can move.');var user=auth.currentUser;if(!user)throw Error('Sign in first');var init=Object.assign({method:'GET'},options||{}),token=await user.getIdToken();init.headers=Object.assign({'authorization':'Bearer '+token,'content-type':'application/json','x-idempotency-key':crypto.randomUUID()},init.headers||{});var response=await fetch(apiBase()+path,init),result=await response.json().catch(function(){return{}});if(!response.ok)throw Error(result.message||result.error||'Request failed');return result}
  function quote(){var kind=$('#bcKind').value,creator=kind==='barter'?0:rupees('#bcFee'),travel=kind==='barter'?0:rupees('#bcTravel'),protectedValue=creator+travel,fee=Math.round(protectedValue*.15),tax=Math.round(fee*.18),total=protectedValue+fee+tax;$('#bcFee').disabled=kind==='barter';$('#bcTravel').disabled=kind==='barter';$('#brandQuote').innerHTML='<span class="cp-eyebrow">LIVE QUOTE</span><div class="cp-breakdown"><div><span>Creator contractual fee</span><b>'+money(creator*100)+'</b></div><div><span>Travel reimbursement</span><b>'+money(travel*100)+'</b></div><div><span>RoamWise service fee · 15%</span><b>'+money(fee*100)+'</b></div><div><span>GST on service fee · 18%</span><b>'+money(tax*100)+'</b></div><div><span>Estimated payment today</span><b>'+money(total*100)+'</b></div></div><p class="cp-card-note">The creator receives the full protected fee + reimbursement. The server quote is authoritative; tax rates remain deployment-configurable if RoamWise’s treatment changes.</p>'}
  function payload(){var deliverables=$('#bcDeliverables').value.split(',').map(function(v,i){return{id:'d'+(i+1),label:v.trim(),quantity:1}}).filter(function(v){return v.label});return{title:$('#bcTitle').value,destination:$('#bcDestination').value,description:$('#bcDescription').value,kind:$('#bcKind').value,creatorSlots:1,creatorFeeMinor:rupees('#bcFee')*100,travelReimbursementMinor:rupees('#bcTravel')*100,deliverables:deliverables,usageRights:$('#bcRights').value,exclusivityDays:rupees('#bcExclusive'),accommodationNights:rupees('#bcNights'),mealsIncluded:$('#bcMeals').checked,applicationDeadline:$('#bcDeadline').value,travelStart:$('#bcStart').value}}
  async function login(create){var email=$('#brandEmail').value.trim(),password=$('#brandPassword').value;if(!email||password.length<6)return message('#brandAuthMsg','Enter a valid email and 6+ character password.',true);try{var credential=create?await auth.createUserWithEmailAndPassword(email,password):await auth.signInWithEmailAndPassword(email,password);if(create){await credential.user.sendEmailVerification();message('#brandAuthMsg','Account created. Verify the email, then sign in again.')}}catch(error){message('#brandAuthMsg',error.message,true)}}
  async function onboard(){try{var result=await call('/v1/creator-protection/onboard',{method:'POST',body:JSON.stringify({role:'brand',displayName:$('#brandName').value,phone:$('#brandPhone').value})});message('#brandOnboardMsg',result.message);await load()}catch(error){message('#brandOnboardMsg',error.message,true)}}
  async function createCampaign(event){event.preventDefault();try{var result=await call('/v1/creator-protection/campaigns',{method:'POST',body:JSON.stringify(payload())});message('#brandCampaignMsg','Draft '+result.id+' created. Review it, then publish for creator applications.');await loadCampaigns()}catch(error){message('#brandCampaignMsg',error.message,true)}}
  function campaignActions(c){var controls='';if(c.status==='draft')controls+='<button class="cp-tab on" data-action="publish">Publish</button>';if(c.status==='published')controls+='<button class="cp-tab" data-apps>Review applications</button>';if(c.status==='offer_accepted')controls+='<button class="cp-tab on" data-action="fund">Fund securely</button>';if(c.status==='submitted')controls+='<button class="cp-tab on" data-action="approve">Approve work</button>';if(c.status==='approved')controls+='<button class="cp-tab on" data-action="release">Release payment</button>';if(['funded','in_progress','submitted','approved'].includes(c.status))controls+='<button class="cp-tab" data-action="dispute">Raise issue</button>';return controls}
  function render(){var root=$('#brandCampaigns');if(!campaigns.length){root.innerHTML='<div class="cp-empty">No protected campaign contracts yet.</div>';return}root.innerHTML=campaigns.map(function(c){var funded=['funded','in_progress','submitted','approved','release_pending','paid','disputed'].includes(c.status);return'<article class="cp-mini-card" data-card="'+esc(c.id)+'"><div class="cp-card-top"><span class="cp-badge '+(funded?'funded':'')+'">'+(funded?'<i></i> FUNDED':esc(String(c.status).replace(/_/g,' ').toUpperCase()))+'</span><span class="cp-kind">'+esc(c.kind.toUpperCase())+'</span></div><h3>'+esc(c.title)+'</h3><p>'+esc(c.destination)+' · '+esc(c.travel_start||'dates open')+'</p><div class="cp-mini-money">'+money(c.creator_fee_minor)+'</div><p>Travel '+money(c.travel_reimbursement_minor)+' · Total brand payment '+money(c.total_payable_minor)+'</p><div class="cp-actions">'+campaignActions(c)+'</div><div class="cp-applications"></div></article>'}).join('');root.querySelectorAll('[data-action]').forEach(function(button){button.onclick=function(){var card=button.closest('[data-card]');act(card.dataset.card,button.dataset.action)}});root.querySelectorAll('[data-apps]').forEach(function(button){button.onclick=function(){var card=button.closest('[data-card]');applications(card.dataset.card,card.querySelector('.cp-applications'))}})}
  async function applications(id,root){try{var result=await call('/v1/creator-protection/campaigns/'+encodeURIComponent(id)+'/applications');var list=result.applications||[];root.innerHTML=list.length?list.map(function(a){return'<div class="cp-message"><b>'+esc(a.display_name||a.email)+'</b><br>'+esc(a.note||'No pitch note')+'<br><button class="cp-tab on" data-accept="'+esc(a.creator_uid)+'">Accept creator</button></div>'}).join(''):'<div class="cp-message">No applications yet.</div>';root.querySelectorAll('[data-accept]').forEach(function(button){button.onclick=function(){accept(id,button.dataset.accept)}})}catch(error){root.innerHTML='<div class="cp-message bad">'+esc(error.message)+'</div>'}}
  async function accept(id,creatorUid){try{await call('/v1/creator-protection/campaigns/'+encodeURIComponent(id)+'/accept',{method:'POST',body:JSON.stringify({creatorUid:creatorUid})});await loadCampaigns()}catch(error){alert(error.message)}}
  async function openFundingCheckout(checkout){if(checkout.kind!=='cashfree_session'||!checkout.paymentSessionId)throw Error('The funding provider did not return a usable checkout session.');if(typeof Cashfree!=='function')throw Error('Cashfree checkout could not be loaded. Refresh and try again.');var cashfree=Cashfree({mode:checkout.environment==='production'?'production':'sandbox'}),result=await cashfree.checkout({paymentSessionId:checkout.paymentSessionId,redirectTarget:'_modal'});if(result&&result.error)throw Error(result.error.message||'Funding was not completed.');alert('Funding submitted. RoamWise will show FUNDED only after the signed provider webhook confirms payment.')}
  async function act(id,action){try{var payload={};if(action==='dispute'){var reason=prompt('Describe the payment, travel or deliverable issue. This freezes release:');if(!reason)return;payload={reason:reason,evidence:[]}}var result=await call('/v1/creator-protection/campaigns/'+encodeURIComponent(id)+'/'+action,{method:'POST',body:JSON.stringify(payload)});if(action==='fund'&&result.checkout)await openFundingCheckout(result.checkout);await loadCampaigns()}catch(error){alert(error.message)}}
  async function loadCampaigns(){if(!apiBase()||!actor||actor.role!=='brand'||actor.status!=='active'){campaigns=[];return render()}try{var result=await call('/v1/creator-protection/campaigns');campaigns=result.campaigns||[];render()}catch(error){message('#brandCampaignMsg',error.message,true)}}
  async function load(){if(!auth.currentUser||!auth.currentUser.emailVerified)return;$('#brandAuth').hidden=true;$('#brandDesk').hidden=false;$('#brandSignOut').hidden=false;if(!apiBase()){$('#brandStatus').textContent='PROVIDER ONBOARDING MODE';actor={role:'guest',status:'unregistered'};return render()}try{actor=await call('/v1/creator-protection/me');$('#brandStatus').textContent=(actor.role+' · '+actor.status).toUpperCase();$('#brandName').value=actor.displayName||'';$('#brandPhone').value=actor.phone||'';await loadCampaigns()}catch(error){message('#brandOnboardMsg',error.message,true)}}
  $('#brandLogin').onclick=function(){login(false)};$('#brandCreate').onclick=function(){login(true)};$('#brandSignOut').onclick=function(){auth.signOut()};$('#brandOnboard').onclick=onboard;$('#brandCampaignForm').onsubmit=createCampaign;$('#brandRefresh').onclick=loadCampaigns;['#bcKind','#bcFee','#bcTravel'].forEach(function(s){$(s).oninput=quote});quote();
  auth.onAuthStateChanged(function(user){if(!user||!user.emailVerified){$('#brandAuth').hidden=false;$('#brandDesk').hidden=true;$('#brandSignOut').hidden=true;if(user&&!user.emailVerified)message('#brandAuthMsg','Verify '+user.email+' before continuing.',true);return}load()});
})();
