/* Creator Studio insights: safe, read-only, and optional. Missing Firestore docs render honest empty states. */
(function(){
'use strict';
var esc=function(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]||c})};
var host=function(){return document.getElementById('creatorInsights')};
var fallback={trends:[{label:'Short video + original voice',value:86,note:'Prioritise original Reels, Shorts and useful local context.'},{label:'Wellness and slow travel',value:74,note:'Yoga, calm stays and low-crowd itineraries remain strong RoamWise fits.'},{label:'Creator-led discovery',value:68,note:'Clear destination hooks and saveable guides beat generic hotel posts.'},{label:'WhatsApp conversion',value:61,note:'Use one tap to ask, verify dates and move to a human booking desk.'}],stats:{activeCreators:0,openBriefs:0,verifiedMatches:0,completedCampaigns:0},leaders:[]};
function render(data){var h=host();if(!h)return;var t=(data.trends||fallback.trends).slice(0,6),max=Math.max.apply(null,t.map(function(x){return Number(x.value||0)}).concat([1])),s=data.stats||fallback.stats,l=data.leaders||[];h.innerHTML='<div class="ci-grid"><article class="ci-card"><span class="cs-kicker">LATEST CREATOR TRENDS</span><h2>What is working now</h2><p class="ci-muted">Updated from RoamWise signals and current creator-platform direction. Treat these as guidance, not guaranteed reach.</p><div class="ci-bars">'+t.map(function(x){return '<div class="ci-bar"><span>'+esc(x.label)+'</span><div class="ci-track"><div class="ci-fill" style="width:'+Math.round(Number(x.value||0)/max*100)+'%"></div></div><b>'+Math.round(Number(x.value||0))+'</b></div><div class="ci-muted">'+esc(x.note||'')+'</div>'}).join('')+'</div></article><article class="ci-card"><span class="cs-kicker">NETWORK SNAPSHOT</span><h2>Verified activity</h2><div class="ci-list"><div class="ci-row"><span>Active creators</span><b>'+esc(s.activeCreators||0)+'</b></div><div class="ci-row"><span>Open briefs</span><b>'+esc(s.openBriefs||0)+'</b></div><div class="ci-row"><span>Verified matches</span><b>'+esc(s.verifiedMatches||0)+'</b></div><div class="ci-row"><span>Completed campaigns</span><b>'+esc(s.completedCampaigns||0)+'</b></div></div><p class="ci-muted">Only admin verified records are counted. Empty values mean no public aggregate has been published yet.</p></article></div><article class="ci-card" style="margin-top:16px"><span class="cs-kicker">LEADERBOARD</span><h2>Creator contribution leaderboard</h2><p class="ci-muted">Rank is based on verified useful work, completed collaborations and attributed stays, never self-reported followers alone.</p><div class="ci-list">'+(l.length?l.slice(0,10).map(function(x,i){return '<div class="ci-row"><span class="ci-rank">'+(i+1)+'</span><span>'+esc(x.name||'Creator')+' <span class="ci-status">'+esc(x.tier||'applied')+'</span></span><b>'+esc(x.points||0)+' XP</b></div>'}).join(''):'<div class="ci-muted">Leaderboard will appear after RoamWise publishes the first verified creator aggregate.</div>')+'</div></article>'}
async function readDoc(path){try{if(!window.firebase||!firebase.firestore)return null;var snap=await firebase.firestore().doc(path).get();return snap.exists?(snap.data()||{}):null}catch(_){return null}}
async function load(){render(fallback);var data={trends:fallback.trends,stats:fallback.stats,leaders:[]},pub=await readDoc('publicCreatorInsights/current');if(pub)data=Object.assign(data,pub);var auth=window.firebase&&firebase.auth?firebase.auth().currentUser:null;if(auth){var own=await readDoc('creatorAnalytics/'+auth.uid);if(own)data.stats=Object.assign({},data.stats,own)}render(data)}
window.addEventListener('error',function(e){if(String(e.filename||'').indexOf('studio.js')>=0){var h=host();if(h)h.innerHTML='<div class="ci-card"><h2>Creator pulse is available in safe mode</h2><p class="ci-muted">Your profile tools remain usable. Insights will retry when the data service responds.</p></div>'}});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load);else load();
})();