(function () {
  'use strict';
  var auth=firebase.auth(),root=document.querySelector('#caProtectionActors'),statusRoot=document.querySelector('#caProtectionStatus'),refresh=document.querySelector('#caProtectionRefresh');
  var esc=function(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})};
  var apiBase=function(){return String(window.RW_CONFIG&&window.RW_CONFIG.creatorProtectionUrl||'').replace(/\/+$/,'')};
  async function call(path,options){var user=auth.currentUser;if(!user)throw Error('Sign in first');var token=await user.getIdToken(),init=Object.assign({method:'GET'},options||{});init.headers=Object.assign({'authorization':'Bearer '+token,'content-type':'application/json','x-idempotency-key':crypto.randomUUID()},init.headers||{});var response=await fetch(apiBase()+path,init),result=await response.json().catch(function(){return{}});if(!response.ok)throw Error(result.error||'Creator Protection request failed');return result}
  function showStatus(text,bad){statusRoot.innerHTML='<div class="'+(bad?'ca-error':'ca-ok')+'">'+esc(text)+'</div>'}
  function paint(actors){if(!actors.length){root.innerHTML='<div class="ca-empty">No pending payment-protection accounts.</div>';return}root.innerHTML=actors.map(function(a){return'<div class="ca-row" data-actor="'+esc(a.uid)+'" data-role="'+esc(a.role)+'"><div><h3>'+esc(a.display_name||a.email)+'</h3><p>'+esc(a.role)+' · '+esc(a.email)+'</p><small>UID '+esc(a.uid)+'</small><div class="ca-tags"><span class="ca-tag warn">KYC pending</span>'+(a.minimum_paid_minor?'<span class="ca-tag">Minimum ₹'+Math.round(a.minimum_paid_minor/100).toLocaleString('en-IN')+'</span>':'')+'</div></div><div class="ca-actions ca-provider"><input aria-label="Provider vendor ID" placeholder="'+(a.role==='creator'?'Creator beneficiary/vendor ID':'Brand provider ID (optional)')+'" maxlength="100"><button class="ca-action green" data-approve>Approve + activate</button><button class="ca-action secondary" data-suspend>Suspend</button></div></div>'}).join('');root.querySelectorAll('[data-approve]').forEach(function(button){button.onclick=function(){update(button.closest('[data-actor]'),true)}});root.querySelectorAll('[data-suspend]').forEach(function(button){button.onclick=function(){update(button.closest('[data-actor]'),false)}})}
  async function load(){if(!apiBase()){root.innerHTML='<div class="ca-empty">Set <code>creatorProtectionUrl</code> after deploying the protected campaign worker.</div>';statusRoot.innerHTML='';return}try{var config=await call('/v1/creator-protection/config'),result=await call('/v1/creator-protection/actors?status=pending');showStatus(config.protectedHoldActive?'Provider contract gate is active: '+config.selectedProvider:'Fund movement is disabled until provider approval.');paint(result.actors||[])}catch(error){showStatus(error.message,true)}}
  async function update(row,approved){var vendor=row.querySelector('input').value.trim();if(approved&&row.dataset.role==='creator'&&!vendor)return showStatus('Enter the creator’s provider vendor or beneficiary ID before activation.',true);try{await call('/v1/creator-protection/actors/'+encodeURIComponent(row.dataset.actor)+'/approve',{method:'POST',body:JSON.stringify({approved:approved,providerVendorId:vendor})});showStatus(approved?'Account activated.':'Account suspended.');await load()}catch(error){showStatus(error.message,true)}}
  if(refresh)refresh.onclick=load;
  auth.onAuthStateChanged(function(user){if(user&&user.emailVerified)load()});
})();
