/* RoamWise Creator Studio v4.0
 * Access contract:
 *   verified Firebase email -> creatorAccounts identity claim -> founder registration -> Studio.
 * Creators cannot self-register, self-award referral codes, tiers, money or review status.
 * Media is link-first: Instagram/YouTube/blog providers host bytes; RoamWise stores tiny metadata.
 */
(function(){'use strict';
var CFG={apiKey:'AIzaSyBTfmJvHTmp0mNQqsIhWEwnLLwFKz0ExYQ',authDomain:'roamwisepro.firebaseapp.com',projectId:'roamwisepro',storageBucket:'roamwisepro.firebasestorage.app',messagingSenderId:'1039880917656',appId:'1:1039880917656:web:8b3e18e8a4b1c9f8e2c0d1'};
if(!firebase.apps.length)firebase.initializeApp(CFG);
var auth=firebase.auth(),db=firebase.firestore(),S={user:null,account:null,creator:{},content:[],ledger:null,ledgerReadable:true,registered:false};
var $=function(s,r){return(r||document).querySelector(s)};
var esc=function(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c})};
var now=function(){return new Date().toISOString()};
var money=function(n){return'₹'+Math.round(Number(n||0)).toLocaleString('en-IN')};
function safeUrl(v){v=String(v||'').trim();if(!v)return'';try{var u=new URL(v);return /^https:$/.test(u.protocol)?u.href:''}catch(e){return''}}
function msg(text,bad){var h=$('#csAuthMsg');if(!h)return;h.className='cs-msg'+(bad?' bad':'');h.textContent=text}
function authView(on){$('#csAuth').hidden=!!on;$('#csDash').hidden=!on;$('#csSignOut').hidden=!on}
function verifyView(on){$('#csLoginFields').hidden=!!on;$('#csVerifyBox').hidden=!on;if(on)$('#csSignOut').hidden=false}
function setv(id,v){var e=$(id);if(e)e.value=v||''}
function tier(){var t=String(S.ledger&&S.ledger.tier||'applied').toLowerCase();return /^(applied|partner|featured)$/.test(t)?t:'applied'}
function rate(){if(S.ledger&&Number.isFinite(Number(S.ledger.ratePct)))return Number(S.ledger.ratePct);return tier()==='applied'?25:30}
function activeCode(){var l=S.ledger||{};return l.referralActive!==false&&l.referralCode?String(l.referralCode):''}
function refLink(){var c=activeCode();return c?'https://roamwise.co.in/?ref='+encodeURIComponent(c):''}
function reviewFor(id){var r=S.ledger&&S.ledger.contentReviews;return r&&r[id]&&typeof r[id]==='object'?r[id]:null}
function gateBox(){var old=$('#csRegistrationGate');if(old)old.remove();var app=$('#csApp'),box=document.createElement('section');box.id='csRegistrationGate';box.className='cs-auth';box.innerHTML='<div class="cs-auth-art"><div class="cs-moon"></div><div class="cs-grid"></div><div class="cs-auth-copy"><small>CREATOR REGISTRATION</small><h1>Application first. <em>Studio second.</em></h1><p>Signing into RoamWise does not automatically make an account a creator. Your verified email must be matched to an approved Creator Network application.</p></div></div><div class="cs-auth-form"><span class="cs-kicker">REGISTRATION PENDING</span><h2>Your identity is verified</h2><p id="csGateText">RoamWise has recorded this verified account claim. A founder review must register it before Creator Studio opens.</p><div class="cs-msg"><b>What happens next</b><br>1. Apply with this same email.<br>2. RoamWise checks the application and public creator presence.<br>3. Registration is activated; then profile, referral and content tools unlock.</div><div class="cs-auth-actions"><a href="./" style="display:inline-flex;align-items:center;justify-content:center;text-decoration:none">Open creator application</a><button id="csGateRefresh">Check registration</button></div><p style="font-size:12px;color:#777d8b">Signed in as <b>'+esc(S.user&&S.user.email||'')+'</b>. No referral, payout or creator privileges are created by this claim.</p></div>';
app.appendChild(box);$('#csAuth').hidden=true;$('#csDash').hidden=true;$('#csSignOut').hidden=false;$('#csGateRefresh').onclick=function(){load().catch(function(e){msg(e.message||'Could not refresh.',true)})}}
async function ensureIdentityClaim(){if(!S.user||!S.user.emailVerified)return null;await S.user.reload();S.user=auth.currentUser;await S.user.getIdToken(true);var ref=db.collection('creatorAccounts').doc(S.user.uid),snap=await ref.get(),email=String(S.user.email||'').toLowerCase();if(!snap.exists){var claim={uid:S.user.uid,email:email,emailVerified:true,status:'claimed',registered:false,createdAt:now(),updatedAt:now()};await ref.set(claim);S.account=claim;return claim}var a=snap.data()||{};S.account=a;if(String(a.email||'').toLowerCase()!==email)throw new Error('Creator registration email does not match this Firebase account.');try{await ref.set({email:email,emailVerified:true,updatedAt:now()},{merge:true})}catch(e){}return a}
function isRegistered(a){return !!(a&&a.registered===true&&a.status==='active')}
async function ensureCreatorRecord(data){var c=data.creator||{};if(c.program==='creator')return c;var fresh={program:'creator',accountEmail:S.user.email||'',displayName:'',niche:'',bio:'',socials:{},payoutPreference:'UPI',registeredAt:(S.account&&S.account.approvedAt)||now(),updatedAt:now()};await db.collection('users').doc(S.user.uid).set({creator:fresh},{merge:true});return fresh}
async function loadContent(){S.content=[];try{var q=await db.collection('creatorContent').doc(S.user.uid).collection('submissions').orderBy('createdAt','desc').limit(100).get();q.forEach(function(d){var x=d.data()||{};x.id=d.id;S.content.push(x)})}catch(e){S.content=[]}}
async function load(){var account=await ensureIdentityClaim();S.registered=isRegistered(account);if(!S.registered){gateBox();return}var gate=$('#csRegistrationGate');if(gate)gate.remove();var snap=await db.collection('users').doc(S.user.uid).get(),data=snap.exists?(snap.data()||{}):{};S.creator=await ensureCreatorRecord(data);await loadContent();S.ledger=null;S.ledgerReadable=true;try{var e=await db.collection('creatorEarnings').doc(S.user.uid).get();S.ledger=e.exists?(e.data()||{}):null}catch(err){S.ledgerReadable=false}paint()}
function stat(k,v,n){return'<div class="cs-stat"><small>'+esc(k)+'</small><b>'+esc(v)+'</b><span>'+esc(n||'')+'</span></div>'}
function ledgerCard(k,v){return'<div class="cs-ledger-card"><small>'+esc(k)+'</small><b>'+esc(v)+'</b></div>'}
function paint(){var c=S.creator,l=S.ledger||{},t=tier(),code=activeCode(),sales=Number(l.verifiedSales||0);authView(true);verifyView(false);$('#csHello').textContent=c.displayName?c.displayName+' · your Creator Studio':'Your RoamWise Creator Studio';$('#csTierLine').textContent=t==='featured'?'Featured creator · highest verified milestone':t==='partner'?'Partner creator · 30% verified commission tier':code?'Applied creator · 25% verified commission tier':'Registered creator · referral activation pending';$('#csCode').textContent=code||'PENDING';$('#csRate').textContent=code?(rate()+'% verified commission'):'Registered · code review';$('#csRefLink').value=refLink();$('#csCopyLink').disabled=!code;$('#csCopyLink2').disabled=!code;$('#csStats').innerHTML=stat('Verified sales',sales.toLocaleString('en-IN'),'completed, non-refunded')+stat('Pending commission',money(l.pendingCommission),'inside payout hold')+stat('Paid to date',money(l.paidCommission),'verified payouts')+stat('Linked content',S.content.length.toLocaleString('en-IN'),'metadata only · media stays on source');$('#csPartnerTier').classList.toggle('on',t==='partner'||t==='featured');$('#csFeaturedTier').classList.toggle('on',t==='featured');$('#csProfileStatus').textContent=t==='featured'?'Featured':t==='partner'?'Partner':code?'Active':'Registered';$('#csRefNote').textContent=code?'This code is active in RoamWise referral attribution. Verified sales and money remain admin-owned.':'Your creator registration is active. Complete your profile and submit useful public work while RoamWise reviews referral activation.';setv('#csName',c.displayName||S.user.displayName||'');setv('#csNiche',c.niche||'');setv('#csInstagram',c.socials&&c.socials.instagram);setv('#csYoutube',c.socials&&c.socials.youtube);setv('#csTiktok',c.socials&&c.socials.tiktok);setv('#csWebsite',c.socials&&c.socials.website);setv('#csPayoutPref',c.payoutPreference||'UPI');setv('#csBio',c.bio||'');paintContent();paintLedger()}
async function saveProfile(){if(!S.registered)return;var name=$('#csName').value.trim();if(!name){$('#csProfileMsg').textContent='Add your display name.';return}var c={program:'creator',accountEmail:S.user.email||'',displayName:name.slice(0,120),niche:$('#csNiche').value.trim().slice(0,120),bio:$('#csBio').value.trim().slice(0,800),socials:{instagram:safeUrl($('#csInstagram').value),youtube:safeUrl($('#csYoutube').value),tiktok:safeUrl($('#csTiktok').value),website:safeUrl($('#csWebsite').value)},payoutPreference:$('#csPayoutPref').value,registeredAt:S.creator.registeredAt||(S.account&&S.account.approvedAt)||now(),updatedAt:now()};try{await db.collection('users').doc(S.user.uid).set({creator:c},{merge:true});S.creator=c;$('#csProfileMsg').textContent='✓ Saved';setTimeout(function(){if($('#csProfileMsg'))$('#csProfileMsg').textContent=''},1600);paint()}catch(e){$('#csProfileMsg').textContent='Could not save: '+e.message}}
function providerInfo(raw){var url=safeUrl(raw);if(!url)return null;var u=new URL(url),h=u.hostname.toLowerCase().replace(/^www\./,'');if(h==='instagram.com'||h.endsWith('.instagram.com')){var m=u.pathname.match(/^\/(reel|reels|p)\/([^/?#]+)/i);if(!m)return{provider:'instagram',kind:'profile',id:u.pathname.replace(/^\/+|\/+$/g,''),url:url};return{provider:'instagram',kind:m[1].toLowerCase()==='p'?'post':'reel',id:m[2],url:'https://www.instagram.com/'+m[1]+'/'+m[2]+'/'}}if(h==='youtu.be'){var id=u.pathname.split('/').filter(Boolean)[0];return id?{provider:'youtube',kind:'video',id:id,url:'https://www.youtube.com/watch?v='+encodeURIComponent(id)}:null}if(h==='youtube.com'||h.endsWith('.youtube.com')){var id=u.searchParams.get('v'),sm=u.pathname.match(/^\/shorts\/([^/?#]+)/);if(sm)id=sm[1];if(id)return{provider:'youtube',kind:sm?'short':'video',id:id,url:'https://www.youtube.com/watch?v='+encodeURIComponent(id)};return{provider:'youtube',kind:'profile',id:u.pathname,url:url}}return{provider:'blog',kind:'article',id:'url_'+hash(url),url:url}}
function hash(s){var h=2166136261;for(var i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(36)}
function icon(p){return p==='youtube'?'▶':p==='instagram'?'▣':p==='blog'?'✎':'◆'}
function paintContent(){var h=$('#csContentList');if(!S.content.length){h.innerHTML='<div class="cs-content-empty"><b>No linked work yet.</b><br>Paste an Instagram Reel/post, YouTube/Shorts video or public blog URL. RoamWise stores the link and small metadata only — upload the media to its original platform, not to us.</div>';return}h.innerHTML=S.content.map(function(x){var r=reviewFor(x.id),status=r&&r.status||x.reviewStatus||'submitted',note=r&&r.note?'<small>'+esc(r.note)+'</small>':'';return'<div class="cs-content-row"><div class="cs-content-icon">'+icon(x.provider)+'</div><div><b>'+esc(x.title||'Untitled')+'</b><small>'+esc([x.provider,x.kind,x.destination].filter(Boolean).join(' · '))+'</small><a href="'+esc(x.url)+'" target="_blank" rel="noopener nofollow">Open source content ↗</a>'+note+'</div><span class="cs-content-status '+esc(status)+'">'+esc(status)+'</span></div>'}).join('')}
function openContent(){var b=$('#csModalBox');b.innerHTML='<div class="cs-modal-head"><div><small class="cs-kicker">LINK-FIRST CONTENT VAULT</small><h2>Submit public work</h2></div><button id="csModalClose">×</button></div><div class="cs-content-form"><div class="cs-msg"><b>Keep media on the platform built to stream it.</b><br>Use Instagram for Reels/posts, YouTube for videos/Shorts and your public blog for articles. RoamWise saves only the URL and metadata, which keeps Creator Studio fast and scalable.</div><label>Public Instagram / YouTube / blog URL<input id="ccUrl" placeholder="https://instagram.com/reel/… or https://youtube.com/watch?v=…"></label><label>Title<input id="ccTitle" maxlength="160" placeholder="7 days through Spiti without the crowds"></label><label>Destination<input id="ccDest" maxlength="100" placeholder="Spiti Valley"></label><label>Why should RoamWise feature it?<textarea id="ccNote" maxlength="500"></textarea></label><button class="cs-content-save" id="ccSave">Submit link for review</button><div id="ccMsg"></div></div>';$('#csModal').classList.add('open');$('#csModalClose').onclick=closeModal;$('#ccSave').onclick=saveContent}
function closeModal(){$('#csModal').classList.remove('open')}
async function saveContent(){if(!S.registered)return;var title=$('#ccTitle').value.trim(),p=providerInfo($('#ccUrl').value);if(!title||!p){$('#ccMsg').innerHTML='<div class="cs-msg bad">Add a title and a valid HTTPS Instagram, YouTube or public blog URL.</div>';return}var id='cnt_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7),rec={ownerUid:S.user.uid,provider:p.provider,kind:p.kind,providerId:String(p.id||'').slice(0,200),title:title.slice(0,160),destination:$('#ccDest').value.trim().slice(0,100),url:p.url,note:$('#ccNote').value.trim().slice(0,500),reviewStatus:'submitted',visibility:'private',createdAt:now(),updatedAt:now()};try{await db.collection('creatorContent').doc(S.user.uid).collection('submissions').doc(id).set(rec);rec.id=id;S.content.unshift(rec);closeModal();paintContent()}catch(e){$('#ccMsg').innerHTML='<div class="cs-msg bad">'+esc(e.message)+'</div>'}}
function paintLedger(){var h=$('#csPayoutDetails'),l=S.ledger;if(!l){h.innerHTML='<div class="cs-ledger-grid">'+ledgerCard('Verified sales','0')+ledgerCard('Pending','₹0')+ledgerCard('Approved','₹0')+ledgerCard('Paid','₹0')+'</div><div class="cs-ledger-warning"><b>'+(S.ledgerReadable?'Referral/earnings activation is still pending.':'The verified ledger rule is not available yet.')+'</b> Creator registration and link submissions remain separate from money state.</div>';$('#csLedgerNote').textContent='Earnings, code activation and tier are admin-owned and read-only.';return}h.innerHTML='<div class="cs-ledger-grid">'+ledgerCard('Verified sales',Number(l.verifiedSales||0).toLocaleString('en-IN'))+ledgerCard('Pending',money(l.pendingCommission))+ledgerCard('Approved',money(l.approvedCommission))+ledgerCard('Paid',money(l.paidCommission))+'</div><div class="cs-ledger-warning">Tier: <b>'+esc(tier())+' · '+rate()+'%</b> · payout status: <b>'+esc(l.payoutStatus||'not scheduled')+'</b>. Only completed, non-refunded attributed sales count.</div>';$('#csLedgerNote').textContent='Verified by RoamWise · creator cannot edit these numbers.'}
function copy(){var u=refLink();if(!u)return alert('Your referral code is not active yet.');if(navigator.clipboard)navigator.clipboard.writeText(u).then(function(){var b=$('#csCopyLink'),old=b.textContent;b.textContent='✓ Copied';setTimeout(function(){b.textContent=old},1300)}).catch(function(){prompt('Copy your referral link',u)});else prompt('Copy your referral link',u)}
async function sendVerification(){var u=auth.currentUser;if(!u)return;try{await u.sendEmailVerification();msg('Verification email sent to '+(u.email||'your inbox')+'. Open it, then come back and choose “I verified — continue”.')}catch(e){msg(e.message||'Could not send verification email.',true)}}
async function reloadVerification(){var u=auth.currentUser;if(!u)return;try{await u.reload();u=auth.currentUser;await u.getIdToken(true);if(!u.emailVerified)return msg('Email is still unverified. Open the Firebase verification link first.',true);S.user=u;verifyView(false);authView(true);await load()}catch(e){msg(e.message||'Could not refresh verification.',true)}}
async function authGo(create){var e=$('#csEmail').value.trim(),p=$('#csPass').value;if(!e||p.length<6)return msg('Enter a valid email and password of at least 6 characters.',true);msg(create?'Creating account…':'Signing in…');try{var cred=create?await auth.createUserWithEmailAndPassword(e,p):await auth.signInWithEmailAndPassword(e,p);if(create&&cred.user&&!cred.user.emailVerified){await cred.user.sendEmailVerification();msg('Account created. Verification email sent. This creates a RoamWise login only — Creator Studio still requires Creator Network registration.')}}catch(x){msg((x&&x.message)||'Could not sign in.',true)}}
function bind(){var pre=new URLSearchParams(location.search).get('email');if(pre)setv('#csEmail',pre);$('#csLogin').onclick=function(){authGo(false)};$('#csCreate').onclick=function(){authGo(true)};$('#csReset').onclick=function(){var e=$('#csEmail').value.trim();if(!e)return msg('Enter your email first.',true);auth.sendPasswordResetEmail(e).then(function(){msg('Password reset link sent.')}).catch(function(x){msg(x.message,true)})};$('#csVerifySend').onclick=sendVerification;$('#csVerifyReload').onclick=reloadVerification;$('#csSignOut').onclick=function(){auth.signOut()};$('#csSaveProfile').onclick=saveProfile;$('#csAddContent').onclick=openContent;$('#csCopyLink').onclick=copy;$('#csCopyLink2').onclick=copy;$('#csModal').onclick=function(e){if(e.target===this)closeModal()}}
bind();auth.onAuthStateChanged(function(u){S.user=u||null;if(!u){var gate=$('#csRegistrationGate');if(gate)gate.remove();S.account=null;S.creator={};S.content=[];S.ledger=null;S.registered=false;verifyView(false);authView(false);return}if(!u.emailVerified){authView(false);verifyView(true);msg('Verify '+(u.email||'your email')+'. A verified RoamWise login still does not grant Creator Studio until your Creator Network application is registered.');return}authView(true);verifyView(false);load().catch(function(e){var d=$('#csDash');if(d)d.insertAdjacentHTML('afterbegin','<div class="cs-msg bad">Could not load Creator Studio: '+esc(e.message)+'</div>')})});
window.RWCreatorStudio={version:'4.0.0',providerInfo:providerInfo};
})();
