/* RoamWise Creator Studio v2 — stable auth/event lifecycle.
 * Creator-editable profile/content: users/{uid}. Verified money/tier: creatorEarnings/{uid}, read-only to this client.
 */
(function(){'use strict';
var CFG={apiKey:'AIzaSyBTfmJvHTmp0mNQqsIhWEwnLLwFKz0ExYQ',authDomain:'roamwisepro.firebaseapp.com',projectId:'roamwisepro',storageBucket:'roamwisepro.firebasestorage.app',messagingSenderId:'1039880917656',appId:'1:1039880917656:web:8b3e18e8a4b1c9f8e2c0d1'};
if(!firebase.apps.length)firebase.initializeApp(CFG);var auth=firebase.auth(),db=firebase.firestore(),S={user:null,creator:{},content:[],ledger:null};
var $=function(s,r){return (r||document).querySelector(s)},esc=function(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c})},now=function(){return new Date().toISOString()},money=function(n){return'₹'+Math.round(Number(n||0)).toLocaleString('en-IN')};
function safeUrl(v){v=String(v||'').trim();if(!v)return'';try{var u=new URL(v);return /^https?:$/.test(u.protocol)?u.href:''}catch(e){return''}}
function msg(text,bad){var h=$('#csAuthMsg');if(!h)return;h.className='cs-msg'+(bad?' bad':'');h.textContent=text}
function codeFor(uid){return'RW-C-'+String(uid||'CREATOR').replace(/[^A-Za-z0-9]/g,'').toUpperCase().slice(0,10)}
function tier(){var t=String(S.ledger&&S.ledger.tier||'applied').toLowerCase();return /^(applied|partner|featured)$/.test(t)?t:'applied'}
function rate(){return tier()==='applied'?25:30}
function refLink(){return'https://roamwise.co.in/?ref='+encodeURIComponent(S.creator.referralCode||codeFor(S.user&&S.user.uid))}
function setv(id,v){var e=$(id);if(e)e.value=v||''}
function authView(on){$('#csAuth').hidden=!!on;$('#csDash').hidden=!on;$('#csSignOut').hidden=!on}
async function load(){var snap=await db.collection('users').doc(S.user.uid).get(),data=snap.exists?(snap.data()||{}):{};S.creator=data.creator||{};S.content=Array.isArray(data.creatorContent)?data.creatorContent.slice(0,50):[];if(!S.creator.referralCode){S.creator=Object.assign({},S.creator,{referralCode:codeFor(S.user.uid),program:'creator',status:S.creator.status||'applied',appliedAt:S.creator.appliedAt||now(),updatedAt:now()});await db.collection('users').doc(S.user.uid).set({email:S.user.email||'',creator:S.creator},{merge:true})}try{var e=await db.collection('creatorEarnings').doc(S.user.uid).get();S.ledger=e.exists?(e.data()||{}):null}catch(_){S.ledger=null}paint()}
function stat(k,v,n){return'<div class="cs-stat"><small>'+esc(k)+'</small><b>'+esc(v)+'</b><span>'+esc(n||'')+'</span></div>'}
function ledgerCard(k,v){return'<div class="cs-ledger-card"><small>'+esc(k)+'</small><b>'+esc(v)+'</b></div>'}
function paint(){var c=S.creator,l=S.ledger||{},t=tier(),sales=Number(l.verifiedSales||0);authView(true);$('#csHello').textContent=c.displayName?c.displayName+' · your Creator Studio':'Your RoamWise Creator Studio';$('#csTierLine').textContent=t==='featured'?'Featured creator · lifetime-Pro milestone tier':t==='partner'?'Partner creator · 30% verified commission tier':'Applied creator · publish useful travel work and grow verified referrals';$('#csCode').textContent=c.referralCode;$('#csRate').textContent=rate()+'% verified commission';$('#csRefLink').value=refLink();$('#csStats').innerHTML=stat('Verified sales',sales.toLocaleString('en-IN'),'completed, non-refunded')+stat('Pending commission',money(l.pendingCommission),'inside payout hold')+stat('Paid to date',money(l.paidCommission),'verified payouts')+stat('Verified clicks',l.verifiedClicks==null?'—':Number(l.verifiedClicks).toLocaleString('en-IN'),S.ledger?'attributed traffic':'feed not connected');$('#csPartnerTier').classList.toggle('on',t==='partner'||t==='featured');$('#csFeaturedTier').classList.toggle('on',t==='featured');$('#csProfileStatus').textContent=c.status||'Applied';setv('#csName',c.displayName||S.user.displayName||'');setv('#csNiche',c.niche||'');setv('#csInstagram',c.socials&&c.socials.instagram);setv('#csYoutube',c.socials&&c.socials.youtube);setv('#csTiktok',c.socials&&c.socials.tiktok);setv('#csWebsite',c.socials&&c.socials.website);setv('#csBio',c.bio||'');paintContent();paintLedger()}
async function saveProfile(){var name=$('#csName').value.trim();if(!name){$('#csProfileMsg').textContent='Add your display name.';return}var c=Object.assign({},S.creator,{displayName:name,niche:$('#csNiche').value.trim().slice(0,120),bio:$('#csBio').value.trim().slice(0,800),socials:{instagram:safeUrl($('#csInstagram').value),youtube:safeUrl($('#csYoutube').value),tiktok:safeUrl($('#csTiktok').value),website:safeUrl($('#csWebsite').value)},referralCode:S.creator.referralCode||codeFor(S.user.uid),program:'creator',status:S.creator.status||'applied',updatedAt:now()});try{await db.collection('users').doc(S.user.uid).set({email:S.user.email||'',creator:c},{merge:true});S.creator=c;$('#csProfileMsg').textContent='✓ Saved';setTimeout(function(){if($('#csProfileMsg'))$('#csProfileMsg').textContent=''},1600);paint()}catch(e){$('#csProfileMsg').textContent='Could not save: '+e.message}}
function icon(t){return t==='video'?'▶':t==='reel'?'▣':t==='blog'?'✎':t==='itinerary'?'⌖':'◆'}
function paintContent(){var h=$('#csContentList');if(!S.content.length){h.innerHTML='<div class="cs-content-empty">No submissions yet. Add an itinerary, Reel, YouTube video or blog post you want RoamWise to review.</div>';return}h.innerHTML=S.content.slice().sort(function(a,b){return String(b.createdAt||'').localeCompare(String(a.createdAt||''))}).map(function(x){return'<div class="cs-content-row"><div class="cs-content-icon">'+icon(x.type)+'</div><div><b>'+esc(x.title||'Untitled')+'</b><small>'+esc([x.type,x.destination].filter(Boolean).join(' · '))+'</small>'+(x.url?'<a href="'+esc(x.url)+'" target="_blank" rel="noopener">Open content ↗</a>':'')+'</div><span class="cs-content-status '+esc(x.status||'submitted')+'">'+esc(x.status||'submitted')+'</span></div>'}).join('')}
function openContent(){var b=$('#csModalBox');b.innerHTML='<div class="cs-modal-head"><div><small class="cs-kicker">CONTENT VAULT</small><h2>Submit a new piece</h2></div><button id="csModalClose">×</button></div><div class="cs-content-form"><label>Content type<select id="ccType"><option value="itinerary">Itinerary</option><option value="reel">Instagram Reel / Short</option><option value="video">YouTube video</option><option value="blog">Blog post</option><option value="other">Other travel content</option></select></label><label>Title<input id="ccTitle" placeholder="7 days through Spiti without the crowds"></label><label>Destination<input id="ccDest" placeholder="Spiti Valley"></label><label>Public URL<input id="ccUrl" placeholder="https://…"></label><label>Why should RoamWise feature it?<textarea id="ccNote"></textarea></label><button class="cs-content-save" id="ccSave">Submit for review</button><div id="ccMsg"></div></div>';$('#csModal').classList.add('open');$('#csModalClose').onclick=closeModal;$('#ccSave').onclick=saveContent}
function closeModal(){$('#csModal').classList.remove('open')}
async function saveContent(){var title=$('#ccTitle').value.trim(),url=safeUrl($('#ccUrl').value);if(!title||!url){$('#ccMsg').innerHTML='<div class="cs-msg bad">Add a title and valid public URL.</div>';return}var rec={id:'cnt_'+Date.now().toString(36),type:$('#ccType').value,title:title.slice(0,160),destination:$('#ccDest').value.trim().slice(0,100),url:url,note:$('#ccNote').value.trim().slice(0,500),status:'submitted',createdAt:now()},arr=[rec].concat(S.content).slice(0,50);try{await db.collection('users').doc(S.user.uid).set({creatorContent:arr,creator:Object.assign({},S.creator,{lastContentAt:now(),updatedAt:now()})},{merge:true});S.content=arr;closeModal();paintContent()}catch(e){$('#ccMsg').innerHTML='<div class="cs-msg bad">'+esc(e.message)+'</div>'}}
function paintLedger(){var h=$('#csPayoutDetails'),l=S.ledger;if(!l){h.innerHTML='<div class="cs-ledger-grid">'+ledgerCard('Verified sales','0')+ledgerCard('Pending','₹0')+ledgerCard('Approved','₹0')+ledgerCard('Paid','₹0')+'</div><div class="cs-ledger-warning"><b>Verified earnings feed not connected yet.</b> Your code is ready for attribution, but Creator Studio never derives money from creator-editable data. An admin-owned creatorEarnings record will populate these totals after reconciliation is connected.</div>';$('#csLedgerNote').textContent='Earnings and tier are intentionally read-only.';return}h.innerHTML='<div class="cs-ledger-grid">'+ledgerCard('Verified sales',Number(l.verifiedSales||0).toLocaleString('en-IN'))+ledgerCard('Pending',money(l.pendingCommission))+ledgerCard('Approved',money(l.approvedCommission))+ledgerCard('Paid',money(l.paidCommission))+'</div><div class="cs-ledger-warning">Tier: <b>'+esc(tier())+' · '+rate()+'%</b> · payout status: <b>'+esc(l.payoutStatus||'not scheduled')+'</b>. Only completed, non-refunded sales count.</div>'}
function copy(){var u=refLink();if(navigator.clipboard)navigator.clipboard.writeText(u).then(function(){var b=$('#csCopyLink'),old=b.textContent;b.textContent='✓ Copied';setTimeout(function(){b.textContent=old},1300)}).catch(function(){prompt('Copy your referral link',u)});else prompt('Copy your referral link',u)}
async function authGo(create){var e=$('#csEmail').value.trim(),p=$('#csPass').value;if(!e||p.length<6)return msg('Enter a valid email and password of at least 6 characters.',true);msg(create?'Creating account…':'Signing in…');try{if(create)await auth.createUserWithEmailAndPassword(e,p);else await auth.signInWithEmailAndPassword(e,p)}catch(x){msg(x.message||'Could not sign in.',true)}}
function bind(){ $('#csLogin').onclick=function(){authGo(false)};$('#csCreate').onclick=function(){authGo(true)};$('#csReset').onclick=function(){var e=$('#csEmail').value.trim();if(!e)return msg('Enter your email first.',true);auth.sendPasswordResetEmail(e).then(function(){msg('Password reset link sent.')}).catch(function(x){msg(x.message,true)})};$('#csSignOut').onclick=function(){auth.signOut()};$('#csSaveProfile').onclick=saveProfile;$('#csAddContent').onclick=openContent;$('#csCopyLink').onclick=copy;$('#csCopyLink2').onclick=copy;$('#csModal').onclick=function(e){if(e.target===this)closeModal()}}
bind();auth.onAuthStateChanged(function(u){S.user=u||null;if(!u){S.creator={};S.content=[];S.ledger=null;authView(false);return}authView(true);load().catch(function(e){var d=$('#csDash');d.insertAdjacentHTML('afterbegin','<div class="cs-msg bad">Could not load Creator Studio: '+esc(e.message)+'</div>')})});
window.RWCreatorStudio={version:'2.0.0'};
})();