/* RoamWise Creator Studio v3.1
 * Creator-editable profile/content stays in users/{uid}. Verified identity is
 * anchored in creatorAccounts/{uid} using Firebase's email_verified token.
 * Money, tier, referral activation and review status are read-only from
 * creatorEarnings/{uid}; this client never writes them.
 */
(function(){'use strict';
var CFG={apiKey:'AIzaSyBTfmJvHTmp0mNQqsIhWEwnLLwFKz0ExYQ',authDomain:'roamwisepro.firebaseapp.com',projectId:'roamwisepro',storageBucket:'roamwisepro.firebasestorage.app',messagingSenderId:'1039880917656',appId:'1:1039880917656:web:8b3e18e8a4b1c9f8e2c0d1'};
if(!firebase.apps.length)firebase.initializeApp(CFG);
var auth=firebase.auth(),db=firebase.firestore(),S={user:null,creator:{},content:[],ledger:null,ledgerReadable:true,identityReady:false};
var $=function(s,r){return(r||document).querySelector(s)},esc=function(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c})},now=function(){return new Date().toISOString()},money=function(n){return'₹'+Math.round(Number(n||0)).toLocaleString('en-IN')};
function safeUrl(v){v=String(v||'').trim();if(!v)return'';try{var u=new URL(v);return /^https?:$/.test(u.protocol)?u.href:''}catch(e){return''}}
function msg(text,bad){var h=$('#csAuthMsg');if(!h)return;h.className='cs-msg'+(bad?' bad':'');h.textContent=text}
function authView(on){$('#csAuth').hidden=!!on;$('#csDash').hidden=!on;$('#csSignOut').hidden=!on}
function verifyView(on){$('#csLoginFields').hidden=!!on;$('#csVerifyBox').hidden=!on;if(on)$('#csSignOut').hidden=false}
function setv(id,v){var e=$(id);if(e)e.value=v||''}
function tier(){var t=String(S.ledger&&S.ledger.tier||'applied').toLowerCase();return /^(applied|partner|featured)$/.test(t)?t:'applied'}
function rate(){if(S.ledger&&Number.isFinite(Number(S.ledger.ratePct)))return Number(S.ledger.ratePct);return tier()==='applied'?25:30}
function activeCode(){var l=S.ledger||{};return l.referralActive!==false&&l.referralCode?String(l.referralCode):''}
function refLink(){var c=activeCode();return c?'https://roamwise.co.in/?ref='+encodeURIComponent(c):''}
function reviewFor(id){var r=S.ledger&&S.ledger.contentReviews;return r&&r[id]&&typeof r[id]==='object'?r[id]:null}
async function ensureVerifiedIdentity(){S.identityReady=false;if(!S.user||!S.user.emailVerified)return false;try{await S.user.getIdToken(true);var ref=db.collection('creatorAccounts').doc(S.user.uid),snap=await ref.get(),base={uid:S.user.uid,email:S.user.email||'',emailVerified:true,updatedAt:now()};if(!snap.exists)base.createdAt=now();await ref.set(base,{merge:true});S.identityReady=true;return true}catch(e){S.identityReady=false;return false}}
async function ensureCreatorRecord(data){var c=data.creator||{};if(c.program==='creator')return c;var fresh=Object.assign({},c,{program:'creator',accountEmail:S.user.email||'',appliedAt:c.appliedAt||now(),updatedAt:now()});await db.collection('users').doc(S.user.uid).set({email:S.user.email||'',creator:fresh},{merge:true});return fresh}
async function load(){await ensureVerifiedIdentity();var snap=await db.collection('users').doc(S.user.uid).get(),data=snap.exists?(snap.data()||{}):{};S.creator=await ensureCreatorRecord(data);S.content=Array.isArray(data.creatorContent)?data.creatorContent.slice(0,50):[];S.ledger=null;S.ledgerReadable=true;try{var e=await db.collection('creatorEarnings').doc(S.user.uid).get();S.ledger=e.exists?(e.data()||{}):null}catch(err){S.ledgerReadable=false;S.ledger=null}paint()}
function stat(k,v,n){return'<div class="cs-stat"><small>'+esc(k)+'</small><b>'+esc(v)+'</b><span>'+esc(n||'')+'</span></div>'}
function ledgerCard(k,v){return'<div class="cs-ledger-card"><small>'+esc(k)+'</small><b>'+esc(v)+'</b></div>'}
function paint(){var c=S.creator,l=S.ledger||{},t=tier(),code=activeCode(),sales=Number(l.verifiedSales||0);authView(true);verifyView(false);$('#csHello').textContent=c.displayName?c.displayName+' · your Creator Studio':'Your RoamWise Creator Studio';$('#csTierLine').textContent=t==='featured'?'Featured creator · highest verified milestone':t==='partner'?'Partner creator · 30% verified commission tier':code?'Applied creator · 25% verified commission tier':'Application/account review · build your profile while RoamWise activates attribution';$('#csCode').textContent=code||'PENDING';$('#csRate').textContent=code?(rate()+'% verified commission'):'Review in progress';$('#csRefLink').value=refLink();$('#csCopyLink').disabled=!code;$('#csCopyLink2').disabled=!code;$('#csStats').innerHTML=stat('Verified sales',sales.toLocaleString('en-IN'),'completed, non-refunded')+stat('Pending commission',money(l.pendingCommission),'inside payout hold')+stat('Paid to date',money(l.paidCommission),'verified payouts')+stat('Verified clicks',l.verifiedClicks==null?'—':Number(l.verifiedClicks).toLocaleString('en-IN'),S.ledger?'attributed traffic':'feed not connected');$('#csPartnerTier').classList.toggle('on',t==='partner'||t==='featured');$('#csFeaturedTier').classList.toggle('on',t==='featured');$('#csProfileStatus').textContent=t==='featured'?'Featured':t==='partner'?'Partner':code?'Active':S.identityReady?'Verified · review':'Verified email · identity rule pending';$('#csRefNote').textContent=code?'This code is active in RoamWise referral attribution. Verified sales and money remain admin-owned.':S.identityReady?'Your Firebase-verified email is matched securely. RoamWise can activate a checkout-recognised code after application review.':'Your email is verified, but the creator identity rule has not been published yet. Profile/content work normally; referral activation stays safely disabled.';setv('#csName',c.displayName||S.user.displayName||'');setv('#csNiche',c.niche||'');setv('#csInstagram',c.socials&&c.socials.instagram);setv('#csYoutube',c.socials&&c.socials.youtube);setv('#csTiktok',c.socials&&c.socials.tiktok);setv('#csWebsite',c.socials&&c.socials.website);setv('#csPayoutPref',c.payoutPreference||'UPI');setv('#csBio',c.bio||'');paintContent();paintLedger()}
async function saveProfile(){var name=$('#csName').value.trim();if(!name){$('#csProfileMsg').textContent='Add your display name.';return}var c={program:'creator',accountEmail:S.user.email||'',displayName:name.slice(0,120),niche:$('#csNiche').value.trim().slice(0,120),bio:$('#csBio').value.trim().slice(0,800),socials:{instagram:safeUrl($('#csInstagram').value),youtube:safeUrl($('#csYoutube').value),tiktok:safeUrl($('#csTiktok').value),website:safeUrl($('#csWebsite').value)},payoutPreference:$('#csPayoutPref').value,appliedAt:S.creator.appliedAt||now(),updatedAt:now()};try{await db.collection('users').doc(S.user.uid).set({email:S.user.email||'',creator:c},{merge:true});S.creator=c;$('#csProfileMsg').textContent='✓ Saved';setTimeout(function(){if($('#csProfileMsg'))$('#csProfileMsg').textContent=''},1600);paint()}catch(e){$('#csProfileMsg').textContent='Could not save: '+e.message}}
function icon(t){return t==='video'?'▶':t==='reel'?'▣':t==='blog'?'✎':t==='itinerary'?'⌖':'◆'}
function paintContent(){var h=$('#csContentList');if(!S.content.length){h.innerHTML='<div class="cs-content-empty">No submissions yet. Add an itinerary, Reel, YouTube video or blog post you want RoamWise to review.</div>';return}h.innerHTML=S.content.slice().sort(function(a,b){return String(b.createdAt||'').localeCompare(String(a.createdAt||''))}).map(function(x){var r=reviewFor(x.id),status=r&&r.status||'submitted',note=r&&r.note?'<small>'+esc(r.note)+'</small>':'';return'<div class="cs-content-row"><div class="cs-content-icon">'+icon(x.type)+'</div><div><b>'+esc(x.title||'Untitled')+'</b><small>'+esc([x.type,x.destination].filter(Boolean).join(' · '))+'</small>'+(x.url?'<a href="'+esc(x.url)+'" target="_blank" rel="noopener">Open content ↗</a>':'')+note+'</div><span class="cs-content-status '+esc(status)+'">'+esc(status)+'</span></div>'}).join('')}
function openContent(){var b=$('#csModalBox');b.innerHTML='<div class="cs-modal-head"><div><small class="cs-kicker">CONTENT VAULT</small><h2>Submit a new piece</h2></div><button id="csModalClose">×</button></div><div class="cs-content-form"><label>Content type<select id="ccType"><option value="itinerary">Itinerary</option><option value="reel">Instagram Reel / Short</option><option value="video">YouTube video</option><option value="blog">Blog post</option><option value="other">Other travel content</option></select></label><label>Title<input id="ccTitle" maxlength="160" placeholder="7 days through Spiti without the crowds"></label><label>Destination<input id="ccDest" maxlength="100" placeholder="Spiti Valley"></label><label>Public URL<input id="ccUrl" placeholder="https://…"></label><label>Why should RoamWise feature it?<textarea id="ccNote" maxlength="500"></textarea></label><button class="cs-content-save" id="ccSave">Submit for review</button><div id="ccMsg"></div></div>';$('#csModal').classList.add('open');$('#csModalClose').onclick=closeModal;$('#ccSave').onclick=saveContent}
function closeModal(){$('#csModal').classList.remove('open')}
async function saveContent(){var title=$('#ccTitle').value.trim(),url=safeUrl($('#ccUrl').value);if(!title||!url){$('#ccMsg').innerHTML='<div class="cs-msg bad">Add a title and valid public URL.</div>';return}var rec={id:'cnt_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,6),type:$('#ccType').value,title:title.slice(0,160),destination:$('#ccDest').value.trim().slice(0,100),url:url,note:$('#ccNote').value.trim().slice(0,500),createdAt:now()},arr=[rec].concat(S.content).slice(0,50);try{await db.collection('users').doc(S.user.uid).set({creatorContent:arr,creator:Object.assign({},S.creator,{lastContentAt:now(),updatedAt:now()})},{merge:true});S.content=arr;closeModal();paintContent()}catch(e){$('#ccMsg').innerHTML='<div class="cs-msg bad">'+esc(e.message)+'</div>'}}
function paintLedger(){var h=$('#csPayoutDetails'),l=S.ledger;if(!l){h.innerHTML='<div class="cs-ledger-grid">'+ledgerCard('Verified sales','0')+ledgerCard('Pending','₹0')+ledgerCard('Approved','₹0')+ledgerCard('Paid','₹0')+'</div><div class="cs-ledger-warning"><b>'+(S.ledgerReadable?'Your verified ledger has not been activated yet.':'The verified ledger is waiting for the Creator Studio Firestore rule to be published.')+'</b> Profile and content tools still work; RoamWise never invents earnings from creator-editable data.</div>';$('#csLedgerNote').textContent='Earnings, code activation and tier are intentionally read-only.';return}h.innerHTML='<div class="cs-ledger-grid">'+ledgerCard('Verified sales',Number(l.verifiedSales||0).toLocaleString('en-IN'))+ledgerCard('Pending',money(l.pendingCommission))+ledgerCard('Approved',money(l.approvedCommission))+ledgerCard('Paid',money(l.paidCommission))+'</div><div class="cs-ledger-warning">Tier: <b>'+esc(tier())+' · '+rate()+'%</b> · payout status: <b>'+esc(l.payoutStatus||'not scheduled')+'</b>'+(l.lastReconciledAt?' · reconciled '+esc(String(l.lastReconciledAt)):'')+'. Only completed, non-refunded sales count.</div>';$('#csLedgerNote').textContent='Verified by RoamWise · creator cannot edit these numbers.'}
function copy(){var u=refLink();if(!u){alert('Your referral code is not active yet. Complete your profile and wait for RoamWise review.');return}if(navigator.clipboard)navigator.clipboard.writeText(u).then(function(){var b=$('#csCopyLink'),old=b.textContent;b.textContent='✓ Copied';setTimeout(function(){b.textContent=old},1300)}).catch(function(){prompt('Copy your referral link',u)});else prompt('Copy your referral link',u)}
async function sendVerification(){var u=auth.currentUser;if(!u)return;try{await u.sendEmailVerification();msg('Verification email sent to '+(u.email||'your inbox')+'. Open it, then come back and choose “I verified — continue”.')}catch(e){msg(e.message||'Could not send verification email.',true)}}
async function reloadVerification(){var u=auth.currentUser;if(!u)return;try{await u.reload();u=auth.currentUser;await u.getIdToken(true);if(!u.emailVerified)return msg('Email is still unverified. Open the Firebase verification link first.',true);S.user=u;verifyView(false);authView(true);await load()}catch(e){msg(e.message||'Could not refresh verification.',true)}}
async function authGo(create){var e=$('#csEmail').value.trim(),p=$('#csPass').value;if(!e||p.length<6)return msg('Enter a valid email and password of at least 6 characters.',true);msg(create?'Creating account…':'Signing in…');try{var cred=create?await auth.createUserWithEmailAndPassword(e,p):await auth.signInWithEmailAndPassword(e,p);if(create&&cred.user&&!cred.user.emailVerified){await cred.user.sendEmailVerification();msg('Account created. Verification email sent — verify it before Creator Studio opens.')}}catch(x){msg((x&&x.message)||'Could not sign in.',true)}}
function bind(){var pre=new URLSearchParams(location.search).get('email');if(pre)setv('#csEmail',pre);$('#csLogin').onclick=function(){authGo(false)};$('#csCreate').onclick=function(){authGo(true)};$('#csReset').onclick=function(){var e=$('#csEmail').value.trim();if(!e)return msg('Enter your email first.',true);auth.sendPasswordResetEmail(e).then(function(){msg('Password reset link sent.')}).catch(function(x){msg(x.message,true)})};$('#csVerifySend').onclick=sendVerification;$('#csVerifyReload').onclick=reloadVerification;$('#csSignOut').onclick=function(){auth.signOut()};$('#csSaveProfile').onclick=saveProfile;$('#csAddContent').onclick=openContent;$('#csCopyLink').onclick=copy;$('#csCopyLink2').onclick=copy;$('#csModal').onclick=function(e){if(e.target===this)closeModal()}}
bind();auth.onAuthStateChanged(function(u){S.user=u||null;if(!u){S.creator={};S.content=[];S.ledger=null;S.identityReady=false;verifyView(false);authView(false);return}if(!u.emailVerified){authView(false);verifyView(true);msg('Verify '+(u.email||'your email')+' before Creator Studio can create a payout/referral identity.');return}authView(true);verifyView(false);load().catch(function(e){var d=$('#csDash');d.insertAdjacentHTML('afterbegin','<div class="cs-msg bad">Could not load Creator Studio: '+esc(e.message)+'</div>')})});
window.RWCreatorStudio={version:'3.1.0'};
})();
