/* RoamWise Creator Studio v1
 * Creator-editable data lives in users/{uid} (already protected by existing rules).
 * Verified earnings/tier are read-only from creatorEarnings/{uid}; creators never write them.
 */
(function(){
'use strict';
var CFG={apiKey:'AIzaSyBTfmJvHTmp0mNQqsIhWEwnLLwFKz0ExYQ',authDomain:'roamwisepro.firebaseapp.com',projectId:'roamwisepro',storageBucket:'roamwisepro.firebasestorage.app',messagingSenderId:'1039880917656',appId:'1:1039880917656:web:8b3e18e8a4b1c9f8e2c0d1'};
if(!firebase.apps.length)firebase.initializeApp(CFG);var auth=firebase.auth(),db=firebase.firestore(),S={user:null,doc:{},creator:{},content:[],ledger:null};
var $=function(s,r){return (r||document).querySelector(s)}, $$=function(s,r){return Array.from((r||document).querySelectorAll(s));}, esc=function(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c})};
var now=function(){return new Date().toISOString()}, money=function(n){return '₹'+Math.round(Number(n||0)).toLocaleString('en-IN')};
function msg(text,bad){var h=$('#csAuthMsg');if(!h)return;h.className='cs-msg'+(bad?' bad':'');h.textContent=text}
function safeUrl(v){v=String(v||'').trim();if(!v)return'';try{var u=new URL(v);return /^https?:$/.test(u.protocol)?u.href:''}catch(e){return''}}
function codeFor(uid){var clean=String(uid||'CREATOR').replace(/[^A-Za-z0-9]/g,'').toUpperCase();return 'RW-C-'+clean.slice(0,10)}
function referralLink(){return 'https://roamwise.co.in/?ref='+encodeURIComponent(S.creator.referralCode||codeFor(S.user&&S.user.uid))}
function showAuth(){$('#csAuth').hidden=false;$('#csDash').hidden=true;$('#csSignOut').hidden=true}
function showDash(){$('#csAuth').hidden=true;$('#csDash').hidden=false;$('#csSignOut').hidden=false}
async function load(){if(!S.user)return;var snap=await db.collection('users').doc(S.user.uid).get();S.doc=snap.exists?(snap.data()||{}):{};S.creator=S.doc.creator||{};S.content=Array.isArray(S.doc.creatorContent)?S.doc.creatorContent.slice(0,50):[];if(!S.creator.referralCode){S.creator.referralCode=codeFor(S.user.uid);await db.collection('users').doc(S.user.uid).set({creator:Object.assign({},S.creator,{referralCode:S.creator.referralCode,program:'creator',appliedAt:S.creator.appliedAt||now(),updatedAt:now()})},{merge:true})}try{var e=await db.collection('creatorEarnings').doc(S.user.uid).get();S.ledger=e.exists?(e.data()||{}):null}catch(err){S.ledger=null}render()}
function verifiedTier(){var t=String(S.ledger&&S.ledger.tier||'applied').toLowerCase();return ['applied','partner','featured'].includes(t)?t:'applied'}
function rate(){var t=verifiedTier();return t==='applied'?25:30}
function stat(label,value,note){return '<div class="cs-stat"><small>'+esc(label)+'</small><b>'+esc(value)+'</b><span>'+esc(note||'')+'</span></div>'}
function render(){showDash();var c=S.creator,l=S.ledger||{},tier=verifiedTier(),sales=Number(l.verifiedSales||0),pending=Number(l.pendingCommission||0),paid=Number(l.paidCommission||0),clicks=l.verifiedClicks==null?'—':Number(l.verifiedClicks).toLocaleString('en-IN');$('#csHello').textContent=c.displayName?c.displayName+' · your Creator Studio':'Your RoamWise Creator Studio';$('#csTierLine').textContent=tier==='featured'?'Featured creator · lifetime-Pro milestone tier':tier==='partner'?'Partner creator · 30% verified commission tier':'Applied creator · build useful content and verified referrals';$('#csCode').textContent=c.referralCode||codeFor(S.user.uid);$('#csRate').textContent=rate()+'% verified commission';$('#csRefLink').value=referralLink();$('#csStats').innerHTML=stat('Verified sales',sales.toLocaleString('en-IN'),'completed, non-refunded')+stat('Pending commission',money(pending),'inside payout hold')+stat('Paid to date',money(paid),'verified payouts')+stat('Verified clicks',clicks,S.ledger?'attributed traffic':'feed not connected');$('#csPartnerTier').classList.toggle('on',tier==='partner'||tier==='featured');$('#csFeaturedTier').classList.toggle('on',tier==='featured');$('#csProfileStatus').textContent=c.status||'Applied';set('#csName',c.displayName||S.user.displayName||'');set('#csNiche',c.niche||'');set('#csInstagram',c.socials&&c.socials.instagram||'');set('#csYoutube',c.socials&&c.socials.youtube||'');set('#csTiktok',c.socials&&c.socials.tiktok||'');set('#csWebsite',c.socials&&c.socials.website||'');set('#csBio',c.bio||'');renderContent();renderLedger()}
function set(id,v){var e=$(id);if(e)e.value=v||''}
async function saveProfile(){var name=$('#csName').value.trim(),niche=$('#csNiche').value.trim(),socials={instagram:safeUrl($('#csInstagram').value),youtube:safeUrl($('#csYoutube').value),tiktok:safeUrl($('#csTiktok').value),website:safeUrl($('#csWebsite').value)},bio=$('#csBio').value.trim().slice(0,800);if(!name){$('#csProfileMsg').textContent='Add your display name.';return}var creator=Object.assign({},S.creator,{displayName:name,niche:niche,socials:socials,bio:bio,referralCode:S.creator.referralCode||codeFor(S.user.uid),program:'creator',status:S.creator.status||'applied',updatedAt:now()});try{await db.collection('users').doc(S.user.uid).set({email:S.user.email||'',creator:creator},{merge:true});S.creator=creator;$('#csProfileMsg').textContent='✓ Saved';setTimeout(function(){$('#csProfileMsg').textContent=''},1800);render()}catch(e){$('#csProfileMsg').textContent='Could not save: '+e.message}}
function contentIcon(type){return type==='video'?'▶':type==='reel'?'▣':type==='blog'?'✎':type==='itinerary'?'⌖':'◆'}
function renderContent(){var h=$('#csContentList');if(!S.content.length){h.innerHTML='<div class="cs-content-empty">No submissions yet. Add an itinerary, Reel, YouTube video or blog post you want RoamWise to review.</div>';return}h.innerHTML=S.content.slice().sort(function(a,b){return String(b.createdAt||'').localeCompare(String(a.createdAt||''))}).map(function(x){return '<div class="cs-content-row"><div class="cs-content-icon">'+contentIcon(x.type)+'</div><div><b>'+esc(x.title||'Untitled')+'</b><small>'+esc([x.type,x.destination].filter(Boolean).join(' · '))+'</small>'+(x.url?'<a href="'+esc(x.url)+'" target="_blank" rel="noopener">Open content ↗</a>':'')+'</div><span class="cs-content-status '+esc(x.status||'submitted')+'">'+esc(x.status||'submitted')+'</span></div>'}).join('')}
function openContentModal(){var m=$('#csModal'),b=$('#csModalBox');b.innerHTML='<div class="cs-modal-head"><div><small class="cs-kicker">CONTENT VAULT</small><h2>Submit a new piece</h2></div><button id="csModalClose">×</button></div><div class="cs-content-form"><label>Content type<select id="ccType"><option value="itinerary">Itinerary</option><option value="reel">Instagram Reel / Short</option><option value="video">YouTube video</option><option value="blog">Blog post</option><option value="other">Other travel content</option></select></label><label>Title<input id="ccTitle" placeholder="e.g. 7 days through Spiti without the crowds"></label><label>Destination<input id="ccDest" placeholder="Spiti Valley"></label><label>Public URL<input id="ccUrl" placeholder="https://…"></label><label>Why should RoamWise feature it?<textarea id="ccNote" placeholder="What is useful, original or local about this piece?"></textarea></label><button class="cs-content-save" id="ccSave">Submit for review</button><div id="ccMsg"></div></div>';m.classList.add('open');$('#csModalClose').onclick=closeModal;$('#ccSave').onclick=saveContent}
function closeModal(){$('#csModal').classList.remove('open')}
async function saveContent(){var title=$('#ccTitle').value.trim(),url=safeUrl($('#ccUrl').value);if(!title||!url){$('#ccMsg').innerHTML='<div class="cs-msg bad">Add a title and a valid public URL.</div>';return}var rec={id:'cnt_'+Date.now().toString(36),type:$('#ccType').value,title:title,destination:$('#ccDest').value.trim(),url:url,note:$('#ccNote').value.trim().slice(0,500),status:'submitted',createdAt:now()};var arr=[rec].concat(S.content).slice(0,50);try{await db.collection('users').doc(S.user.uid).set({creatorContent:arr,creator:Object.assign({},S.creator,{lastContentAt:now(),updatedAt:now()})},{merge:true});S.content=arr;closeModal();renderContent()}catch(e){$('#ccMsg').innerHTML='<div class="cs-msg bad">Could not save: '+esc(e.message)+'</div>'}}
function renderLedger(){var h=$('#csPayoutDetails'),l=S.ledger;if(!l){h.innerHTML='<div class="cs-ledger-grid">'+ledgerCard('Verified sales','0')+ledgerCard('Pending','₹0')+ledgerCard('Approved','₹0')+ledgerCard('Paid','₹0')+'</div><div class="cs-ledger-warning"><b>Verified earnings feed not connected to this account yet.</b> Your referral code is active for attribution, but this dashboard will not invent earnings from client-side data. Once RoamWise creates the admin-owned <code>creatorEarnings/'+esc(S.user.uid)+'</code> aggregate, the verified totals appear here automatically.</div>';$('#csLedgerNote').textContent='No writable earnings counter is exposed to creators.';return}h.innerHTML='<div class="cs-ledger-grid">'+ledgerCard('Verified sales',Number(l.verifiedSales||0).toLocaleString('en-IN'))+ledgerCard('Pending',money(l.pendingCommission))+ledgerCard('Approved',money(l.approvedCommission))+ledgerCard('Paid',money(l.paidCommission))+'</div><div class="cs-ledger-warning">Commission tier: <b>'+esc(verifiedTier())+' · '+rate()+'%</b> · payout status: <b>'+esc(l.payoutStatus||'not scheduled')+'</b>'+(l.lastReconciledAt?' · reconciled '+esc(String(l.lastReconciledAt)):'')+'. Completed, non-refunded sales are authoritative.</div>'}
function ledgerCard(k,v){return '<div class="cs-ledger-card"><small>'+esc(k)+'</small><b>'+esc(v)+'</b></div>'}
function copyLink(){var url=referralLink();navigator.clipboard&&navigator.clipboard.writeText(url).then(function(){var old=$('#csCopyLink').textContent;$('#csCopyLink').textContent='✓ Copied';setTimeout(function(){$('#csCopyLink').textContent=old},1500)}).catch(function(){prompt('Copy your referral link',url)})}
async function authGo(create){var email=$('#csEmail').value.trim(),pass=$('#csPass').value;if(!email||pass.length<6){msg('Enter a valid email and a password of at least 6 characters.',true);return}msg(create?'Creating account…':'Signing in…');try{if(create)await auth.createUserWithEmailAndPassword(email,pass);else await auth.signInWithEmailAndPassword(email,pass)}catch(e){msg((e&&e.message)||'Could not sign in.',true)}}
function bind(){$('#csLogin').onclick=function(){authGo(false)};$('#csCreate').onclick=function(){authGo(true)};$('#csReset').onclick=function(){var e=$('#csEmail').value.trim();if(!e)return msg('Enter your email first.',true);auth.sendPasswordResetEmail(e).then(function(){msg('Password reset link sent.')}).catch(function(x){msg(x.message,true)})};$('#csSignOut').onclick=function(){auth.signOut()};$('#csSaveProfile').onclick=saveProfile;$('#csAddContent').onclick=openContentModal;$('#csCopyLink').onclick=copyLink;$('#csCopyLink2').onclick=copyLink;$('#csModal').addEventListener('click',function(e){if(e.target===this)closeModal()})}
bind();auth.onAuthStateChanged(async function(u){S.user=u||null;if(!u){S.doc={};S.creator={};S.content=[];S.ledger=null;showAuth();return}showDash();$('#csDash').innerHTML=$('#csDash').innerHTML;try{await load()}catch(e){console.error(e);var d=$('#csDash');d.hidden=false;d.insertAdjacentHTML('afterbegin','<div class="cs-msg bad">Could not load Creator Studio: '+esc(e.message)+'</div>')}});
})();